### ISSUE TITLE
Can't get apiman to work

### ISSUE THREAD

**Issue by viniciusccarvalho** [apiman/apiman#111]
Hi guys, I tried to give it for a spin, and I found a bunch of issues.

When downloading and following the docs from apiman.io, the standalone version, fails as wildfly fails to find anypath on Could not find resource for full path: http://localhost:8080/apimanui/, I tried Could not find resource for full path: http://localhost:8080/apiman/ with no luck.

The docker image seems to have some issues with SSL redirects :(

So I tried grabbing the source code and running mvn to install and run. I got the console up :) great, time to test. 

But when I tried to create an org, I get a permission error 403 non authorized. Although the previous screen seems to indicate that I'm an admin.

I'm really looking forward to try apiman, anything else I could try to get it running?

**Comment by msavy** [comment]
Hi,

This seems to be related to this issue: https://issues.jboss.org/browse/APIMAN-384

If you try using Firefox does it work?

I'm still working on getting to the bottom of this one right now as my initial suspicion seems to have been incorrect - it's slightly odd as it functions in FF, but not some other browsers.

**Comment by msavy** [comment]
Could you please try the following for a temporary work-around:

Edit your standalone.xml file (whichever one you're using, might be apiman-standalone.xml) and disable keycloak's cors:

```
- <kc:enable-cors>true</kc:enable-cors>
+ <kc:enable-cors>false</kc:enable-cors>
```

**Comment by msavy** [comment]
BTW, I can't replicate the issues you describe for docker with SSL redirects. Perhaps try flushing everything out and trying again?

```
bash-3.2$ docker pull jboss/apiman-wildfly
Pulling repository jboss/apiman-wildfly
086ec99a7c53: Download complete
511136ea3c5a: Download complete
782cf93a8f16: Download complete
7d3f07f8de5f: Download complete
1ef0a50fe8b1: Download complete
20a1abe1d9bf: Download complete
cd5bb934bb67: Download complete
379edb00ab07: Download complete
4d37cbbfc67d: Download complete
2ea8562cac7c: Download complete
7759146eab1a: Download complete
b17a20d6f5f8: Download complete
e02bdb6c4ed5: Download complete
72d585299bb5: Download complete
90832e1f0bb9: Download complete
29879a2466f6: Download complete
5eb76cdb1e3e: Download complete
76383cc105a6: Download complete
5e5341f9514e: Download complete
c1abaf3a478a: Download complete
03e8e57fd9be: Download complete
792aed4c2570: Download complete
c30d548518ac: Download complete
Status: Downloaded newer image for jboss/apiman-wildfly:latest
bash-3.2$ docker run -it -p 8080:8080 jboss/apiman-wildfly
=========================================================================

  JBoss Bootstrap Environment

  JBOSS_HOME: /opt/jboss/wildfly

  JAVA: /usr/lib/jvm/java/bin/java

  JAVA_OPTS:  -server -Xms64m -Xmx512m -XX:MaxPermSize=256m -Djava.net.preferIPv4Stack=true -Djboss.modules.system.pkgs=org.jboss.byteman -Djava.awt.headless=true

=========================================================================
```

Please let me know what the exact error you see is, if it reoccurs.

**Comment by viniciusccarvalho** [comment]
I switched to firefox, and I was able to at least to see the next window, but I got an exception:

io.apiman.manager.api.rest.contract.exceptions.SystemErrorException: No auto-grant roles have been configured.  Please create at least one auto-grant role.
	at io.apiman.manager.api.rest.impl.OrganizationResourceImpl.create(OrganizationResourceImpl.java:191)
	at io.apiman.manager.api.rest.impl.OrganizationResourceImpl$Proxy$_$$_WeldClientProxy.create(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:137)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:296)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:250)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:237)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:356)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:179)
	at org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.service(ServletContainerDispatcher.java:220)
	at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:56)
	at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:51)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:85)
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:130)
	at io.apiman.manager.api.security.impl.DefaultSecurityContextFilter.doFilter(DefaultSecurityContextFilter.java:56)
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:60)
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:132)
	at io.apiman.common.servlet.DisableCachingFilter.doFilter(DisableCachingFilter.java:59)
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:60)
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:132)
	at org.overlord.commons.i18n.server.filters.LocaleFilter.doFilter(LocaleFilter.java:61)
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:60)
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:132)
	at io.undertow.servlet.handlers.FilterHandler.handleRequest(FilterHandler.java:85)
	at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:61)
	at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)
	at org.wildfly.extension.undertow.security.SecurityContextAssociationHandler.handleRequest(SecurityContextAssociationHandler.java:78)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at org.keycloak.adapters.undertow.UndertowAuthenticatedActionsHandler.handleRequest(UndertowAuthenticatedActionsHandler.java:66)
	at io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:131)
	at io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:56)
	at io.undertow.server.handlers.DisableCacheHandler.handleRequest(DisableCacheHandler.java:33)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.security.handlers.AuthenticationConstraintHandler.handleRequest(AuthenticationConstraintHandler.java:51)
	at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:45)
	at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:63)
	at io.undertow.servlet.handlers.security.ServletSecurityConstraintHandler.handleRequest(ServletSecurityConstraintHandler.java:56)
	at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:58)
	at io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:70)
	at io.undertow.security.handlers.SecurityInitialHandler.handleRequest(SecurityInitialHandler.java:76)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at org.wildfly.extension.undertow.security.jacc.JACCContextIdHandler.handleRequest(JACCContextIdHandler.java:61)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at org.keycloak.adapters.undertow.ServletPreAuthActionsHandler.handleRequest(ServletPreAuthActionsHandler.java:69)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:261)
	at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:247)
	at io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:76)
	at io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:166)
	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:197)
	at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:759)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by msavy** [comment]
BTW, if you're using server-all with standalone.xml your workaround will need to be <enable-cors>false</enable-cors> (i.e. without the kc: prefix). If you're using standalone-apiman.xml, such as in docker, it will be <kc:enable-cors>false</enable-cors>.

Let me know how it goes.

**Comment by viniciusccarvalho** [comment]
Hi, firefox did work now. Thanks. I'll give it a try on docker soon and I'll let you know.

Regards

**Comment by EricWittmann** [comment]
This one just means that the default config data wasn't installed.  I don't
know off hand why not (did you switch from jpa to elasticsearch?).
Basically the system can be completely configured via the amin ui.  But the
docker image and the overlay download come with some pre configured stuff.
Like roles, a gateway, and some policy definitions.  If that data is
missing you should either try a fresh reinstall or configure it all
manually via the UI as the admin user (not too hard to do and I think it's
at least somewhat documented in the user guide!).

**Comment by EricWittmann** [comment]
I originally messed up the 1.1.0.Final release (accidentally excluding the
default config data from the zip).  It's since been fixed but perhaps the
docker image still has the old image.  Marc can you perhaps force a rebuild
of the docker image if that is the case?

**Comment by msavy** [comment]
@EricWittmann He deleted that message, I presume he sorted it out. I tested the docker image, it works fine. Seed data and all.

**Comment by msavy** [comment]
@EricWittmann @viniciusccarvalho I've tracked down the source of the problem. It seems to be some weirdness with KeyCloak CORS possibly in addition to some quirky browser behaviour with webkit + CORS. 

You can see my progress so far here and see a more satisfactory workaround - https://issues.jboss.org/browse/APIMAN-384

**Comment by msavy** [comment]
Filed KC issue at https://issues.jboss.org/browse/KEYCLOAK-1208 - let's see what comes of it.

**Comment by msavy** [comment]
This can be closed now. There's a bug with KC, but the original problem is that their CORS model is slightly different to what we'd expected, so we'll be coming up with an alternative solution to that
