### ISSUE TITLE
Cannot find module dateformat

### ISSUE THREAD

**Issue by mahom1985** [apiman/apiman#116]
Build is failing this morning:
`
[10:45:33] Error: Cannot find module 'dateformat'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (C:\dev\apiman-github\apiman\manager\ui\hawtio\node_modules\gulp-notify\node_modules\gulp-util\index.js:5:9)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
`

`
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:0.0.23:gulp (gulp build) on project apiman-manager-ui-hawtio: Failed to run task: 'gulp build --no-color' failed. (error code 1) -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.github.eirslett:frontend-maven-plugin:0.0.23:gulp (gulp build) on project apiman-manager-ui-hawtio: Failed to run task
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:120)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:347)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:154)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:582)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:214)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:158)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoFailureException: Failed to run task
        at com.github.eirslett.maven.plugins.frontend.mojo.GulpMojo.execute(GulpMojo.java:71)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:132)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
        ... 19 more
Caused by: com.github.eirslett.maven.plugins.frontend.lib.TaskRunnerException: 'gulp build --no-color' failed. (error code 1)
        at com.github.eirslett.maven.plugins.frontend.lib.NodeTaskExecutor.execute(NodeTaskExecutor.java:38)
        at com.github.eirslett.maven.plugins.frontend.mojo.GulpMojo.execute(GulpMojo.java:69)
        ... 21 more
`

**Comment by EricWittmann** [comment]
That's weird.  When is the last time you were able to build it successfully?  Perhaps this is a transient error with gulp/node.js?  It seems to be building OK for us and on the CI machine.

**Comment by mahom1985** [comment]
I still get the same error.

Last time was around 8 commits ago (I'm sorry, not sure, i had a fork, but trashed it and started fresh today).

I'm assuming that there are no prerequisites to run "mvn clean install", like installing node, or anything else, correct?

**Comment by EricWittmann** [comment]
I don't think there should be - my understanding is that the maven plugin grabs everything it needs to run gulp and bower.

To confirm that, I just ran the build on a clean centos machine I have and it ran fine. :(

Can you try enabling maven debug, doing another clean install, and then creating a gist?

**Comment by mahom1985** [comment]
I'll post the link to the gist shortly.

My suspicion is that npm is not installing dateformat globally so it can't find it later

**Comment by mahom1985** [comment]
https://gist.githubusercontent.com/mahom1985/3db05e0b101be5dbaa5b/raw/gistfile1.txt

**Comment by EricWittmann** [comment]
The strange thing about that is that dateformat has been used for awhile - so I don't think there's anything *new* (relatively speaking) that could have caused this.  I guess I'm wondering if you've ever been able to build apiman since we converted the UI from GWT to angular... 

Might be hard to say. :)

**Comment by mahom1985** [comment]
In the project root directory, i just ran:
`
npm install dateformat
`
and now mvn clean install works fine.

**Comment by EricWittmann** [comment]
OK that's.... good?  :)  I'll mark this as resolved and hope we don't have anyone else run into the same issue.

**Comment by mahom1985** [comment]
:), thanks

**Comment by EricWittmann** [comment]
Glad I could "help".  ;)
