### ISSUE TITLE
VertX Gateway Component Not Found For BufferFactoryComponentImpl 

### ISSUE THREAD

**Issue by shekarnode** [apiman/apiman#1321]
Hi Eric/Marc,

I am trying to use a custom policy in VertX gateway along with BufferFactoryComponentImpl for creating a buffer.

ApiVersion : apiman-distro-vertx-1.5.7.Final

following is the code for creating buffer:
```
final BufferFactoryComponentImpl bufferFactory  = context.getComponent(BufferFactoryComponentImpl.class);
private IApimanBuffer readBuffer = bufferFactory.createBuffer();

```

I'am getting following error.

```
** ERROR: Component not found: io.apiman.gateway.platforms.vertx3.components.BufferFactoryComponentImpl **
io.apiman.gateway.engine.beans.exceptions.ComponentNotFoundException: Component not found: 

io.apiman.gateway.platforms.vertx3.components.BufferFactoryComponentImpl
----------------
** ERROR: Component not found: io.apiman.gateway.platforms.vertx3.components.BufferFactoryComponentImpl **
io.apiman.gateway.engine.beans.exceptions.ComponentNotFoundException: Component not found: io.apiman.gateway.platforms.vertx3.components.BufferFactoryComponentImpl
	at io.apiman.gateway.engine.impl.ConfigDrivenComponentRegistry.createAndRegisterComponent(ConfigDrivenComponentRegistry.java:116)
	at io.apiman.gateway.engine.impl.ConfigDrivenComponentRegistry.getComponent(ConfigDrivenComponentRegistry.java:72)
	at io.apiman.gateway.engine.policy.PolicyContextImpl.getComponent(PolicyContextImpl.java:91)

```

**Comment by msavy** [comment]
You likely want to do:

`final IBufferFactoryComponent bufferFactory  = context.getComponent(IBufferFactoryComponent.class);`

Does that work for you?
