### ISSUE TITLE
Issue related to ES while updating to Apiman vertx 2.1.0 

### ISSUE THREAD

**Issue by shekarnode** [apiman/apiman#1499]
Hi all,

I'm trying to upgrade Apiman vertx gateway to 2.1.0  but i m facing  problem with elastic search earlier i was using apiman vertx 1.5.7  and after switching getting below error:
Elastic version used 5.x:

```
INFO: Use cached Elasticsearch client with client key es:xxx.xxx.xxx.xxx:45795/apiman_gateway
** ERROR: ElasticsearchStatusException[method [HEAD], host [http://xxx.xxx.xxx.xxx:45795], URI [/apiman_gateway_clients?ignore_throttled=false&ignore_unavailable=false&expand_wildcards=open%2Cclosed&allow_no_indices=false], status line [HTTP/1.1 400 Bad Request]]; nested: ResponseException[method [HEAD], host [http://xxx.xxx.xxx.xxx:45795], URI [/apiman_gateway_clients?ignore_throttled=false&ignore_unavailable=false&expand_wildcards=open%2Cclosed&allow_no_indices=false], status line [HTTP/1.1 400 Bad Request]]; **
java.lang.RuntimeException: ElasticsearchStatusException[method [HEAD], host [http://xxx.xxx.xxx.xxx:45795], URI [/apiman_gateway_clients?ignore_throttled=false&ignore_unavailable=false&expand_wildcards=open%2Cclosed&allow_no_indices=false], status line [HTTP/1.1 400 Bad Request]]; nested: ResponseException[method [HEAD], host [http://xxx.xxx.xxx.xxx:45795], URI [/apiman_gateway_clients?ignore_throttled=false&ignore_unavailable=false&expand_wildcards=open%2Cclosed&allow_no_indices=false], status line [HTTP/1.1 400 Bad Request]];
	at io.apiman.common.es.util.AbstractClientFactory.initializeIndices(AbstractClientFactory.java:107)
	at io.apiman.common.es.util.DefaultEsClientFactory.createEsClient(DefaultEsClientFactory.java:141)
	at io.apiman.common.es.util.DefaultEsClientFactory.createClient(DefaultEsClientFactory.java:74)
	at io.apiman.common.es.util.AbstractEsComponent.createClient(AbstractEsComponent.java:68)
	at io.apiman.common.es.util.AbstractEsComponent.getClient(AbstractEsComponent.java:58)
	at io.apiman.gateway.engine.es.PollCachingEsRegistry.checkCacheVersion(PollCachingEsRegistry.java:216)
	at io.apiman.gateway.engine.es.PollCachingEsRegistry$6.run(PollCachingEsRegistry.java:190)
	at java.lang.Thread.run(Thread.java:826)
Caused by: ElasticsearchStatusException[method [HEAD], host [http://xxx.xxx.xxx.xxx:45795], URI [/apiman_gateway_clients?ignore_throttled=false&ignore_unavailable=false&expand_wildcards=open%2Cclosed&allow_no_indices=false], status line [HTTP/1.1 400 Bad Request]]; nested: ResponseException[method [HEAD], host [http://xxx.xxx.xxx.xxx:45795], URI [/apiman_gateway_clients?ignore_throttled=false&ignore_unavailable=false&expand_wildcards=open%2Cclosed&allow_no_indices=false], status line [HTTP/1.1 400 Bad Request]];
	at org.elasticsearch.client.RestHighLevelClient.parseResponseException(RestHighLevelClient.java:1907)
	at org.elasticsearch.client.RestHighLevelClient.internalPerformRequest(RestHighLevelClient.java:1667)
	at org.elasticsearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:1639)
	at org.elasticsearch.client.IndicesClient.exists(IndicesClient.java:963)
	at io.apiman.common.es.util.AbstractClientFactory.initializeIndices(AbstractClientFactory.java:98)
	... 7 more
Caused by: org.elasticsearch.client.ResponseException: method [HEAD], host [http://xxx.xxx.xxx.xxx:45795], URI [/apiman_gateway_clients?ignore_throttled=false&ignore_unavailable=false&expand_wildcards=open%2Cclosed&allow_no_indices=false], status line [HTTP/1.1 400 Bad Request]
	at org.elasticsearch.client.RestClient.convertResponse(RestClient.java:326)
	at org.elasticsearch.client.RestClient.performRequest(RestClient.java:296)
	at org.elasticsearch.client.RestClient.performRequest(RestClient.java:270)
	at org.elasticsearch.client.RestHighLevelClient.internalPerformRequest(RestHighLevelClient.java:1654)
	... 10 more
```

**Comment by shekarnode** [comment]
Hi all,

I'm trying to upgrade Apiman vertx gateway to 2.1.0  but i m faci+ng  problem wi+th elastic search earlier i was usi+ng api+man vertx 1.5.7  and after switching getting below error:
Elastic version used 5.x:

```
INFO: Use cached Elasticsearch client with client key es:xxx.xxx.xxx.xxx:45795/apiman_gateway
** ERROR: ElasticsearchStatusException[method [HEAD], host [http://xxx.xxx.xxx.xxx:45795], URI [/apiman_gateway_clients?ignore_throttled=false&ignore_unavailable=false&expand_wildcards=open%2Cclosed&allow_no_indices=false], status line [HTTP/1.1 400 Bad Request]]; nested: ResponseException[method [HEAD], host [http://xxx.xxx.xxx.xxx:45795], URI [/apiman_gateway_clients?ignore_throttled=false&ignore_unavailable=false&expand_wildcards=open%2Cclosed&allow_no_indices=false], status line [HTTP/1.1 400 Bad Request]]; **
java.lang.RuntimeException: ElasticsearchStatusException[method [HEAD], host [http://xxx.xxx.xxx.xxx:45795], URI [/apiman_gateway_clients?ignore_throttled=false&ignore_unavailable=false&expand_wildcards=open%2Cclosed&allow_no_indices=false], status line [HTTP/1.1 400 Bad Request]]; nested: ResponseException[method [HEAD], host [http://xxx.xxx.xxx.xxx:45795], URI [/apiman_gateway_clients?ignore_throttled=false&ignore_unavailable=false&expand_wildcards=open%2Cclosed&allow_no_indices=false], status line [HTTP/1.1 400 Bad Request]];
	at io.apiman.common.es.util.AbstractClientFactory.initializeIndices(AbstractClientFactory.java:107)
	at io.apiman.common.es.util.DefaultEsClientFactory.createEsClient(DefaultEsClientFactory.java:141)
	at io.apiman.common.es.util.DefaultEsClientFactory.createClient(DefaultEsClientFactory.java:74)
	at io.apiman.common.es.util.AbstractEsComponent.createClient(AbstractEsComponent.java:68)
	at io.apiman.common.es.util.AbstractEsComponent.getClient(AbstractEsComponent.java:58)
	at io.apiman.gateway.engine.es.PollCachingEsRegistry.checkCacheVersion(PollCachingEsRegistry.java:216)
	at io.apiman.gateway.engine.es.PollCachingEsRegistry$6.run(PollCachingEsRegistry.java:190)
	at java.lang.Thread.run(Thread.java:826)
Caused by: ElasticsearchStatusException[method [HEAD], host [http://xxx.xxx.xxx.xxx:45795], URI [/apiman_gateway_clients?ignore_throttled=false&ignore_unavailable=false&expand_wildcards=open%2Cclosed&allow_no_indices=false], status line [HTTP/1.1 400 Bad Request]]; nested: ResponseException[method [HEAD], host [http://xxx.xxx.xxx.xxx:45795], URI [/apiman_gateway_clients?ignore_throttled=false&ignore_unavailable=false&expand_wildcards=open%2Cclosed&allow_no_indices=false], status line [HTTP/1.1 400 Bad Request]];
	at org.elasticsearch.client.RestHighLevelClient.parseResponseException(RestHighLevelClient.java:1907)
	at org.elasticsearch.client.RestHighLevelClient.internalPerformRequest(RestHighLevelClient.java:1667)
	at org.elasticsearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:1639)
	at org.elasticsearch.client.IndicesClient.exists(IndicesClient.java:963)
	at io.apiman.common.es.util.AbstractClientFactory.initializeIndices(AbstractClientFactory.java:98)
	... 7 more
Caused by: org.elasticsearch.client.ResponseException: method [HEAD], host [http://xxx.xxx.xxx.xxx:45795], URI [/apiman_gateway_clients?ignore_throttled=false&ignore_unavailable=false&expand_wildcards=open%2Cclosed&allow_no_indices=false], status line [HTTP/1.1 400 Bad Request]
	at org.elasticsearch.client.RestClient.convertResponse(RestClient.java:326)
	at org.elasticsearch.client.RestClient.performRequest(RestClient.java:296)
	at org.elasticsearch.client.RestClient.performRequest(RestClient.java:270)
	at org.elasticsearch.client.RestHighLevelClient.internalPerformRequest(RestHighLevelClient.java:1654)
	... 10 more
```

**Comment by msavy** [comment]
Good evening @shekarnode 

Please refer to the migration guide - https://www.apiman.io/apiman-docs/core/2.1.0.Final/migration/migrations.html#_elasticsearch

**Comment by shekarnode** [comment]
Thanks Marc for support .
I was able to resolve the issue by following the steps mentioned in doc.
