### ISSUE TITLE
Gson dependency issue in Custom policy with Apiman vertx gateway 2.1.0 

### ISSUE THREAD

**Issue by shekarnode** [apiman/apiman#1501]
Hi Marc,

I tried to use  custom policy in Apiman vertx 2.1.0 and when i added the policy and attached it a A.
Which is related to Gson dependency i was using using policy for some purpose.
This same policy was already working properly with vertx gateway version 1.5.7.

```
** ERROR: com.google.gson.JsonParseException **
java.lang.NoClassDefFoundError: com.google.gson.JsonParseException
        at io.apiman.plugins.random_policy.randomPolicy.requestDataHandler(randomPolicy.java:126)
        at io.apiman.plugins.random_policy.randomPolicy.requestDataHandler(randomPolicy.java:84)
        at io.apiman.gateway.engine.policies.AbstractMappedDataPolicy.getRequestDataHandler(AbstractMappedDataPolicy.java:45)
        at io.apiman.gateway.engine.policy.RequestChain.getApiHandler(RequestChain.java:55)
        at io.apiman.gateway.engine.policy.Chain.chainPolicyHandlers(Chain.java:84)
        at io.apiman.gateway.engine.policy.Chain.doApply(Chain.java:145)
        at io.apiman.gateway.engine.impl.ApiRequestExecutorImpl.lambda$execute$5(ApiRequestExecutorImpl.java:300)
        at io.apiman.gateway.engine.impl.ApiRequestExecutorImpl$$Lambda$510/0x00000000e821b6e0.handle(Unknown Source)
        at io.apiman.gateway.engine.impl.ApiRequestExecutorImpl.lambda$loadPolicies$7(ApiRequestExecutorImpl.java:681)
        at io.apiman.gateway.engine.impl.ApiRequestExecutorImpl$$Lambda$511/0x00000000e822cd60.handle(Unknown Source)
        at io.apiman.gateway.engine.policy.PolicyFactoryImpl$1.handle(PolicyFactoryImpl.java:184)
        at io.apiman.gateway.engine.policy.PolicyFactoryImpl$1.handle(PolicyFactoryImpl.java:164)
        at io.apiman.gateway.engine.impl.DefaultPluginRegistry.lambda$loadPlugin$0(DefaultPluginRegistry.java:187)
        at io.apiman.gateway.engine.impl.DefaultPluginRegistry$$Lambda$512/0x00000000e822d5a0.handle(Unknown Source)
        at io.apiman.gateway.engine.impl.DefaultPluginRegistry.lambda$loadPlugin$1(DefaultPluginRegistry.java:288)
        at io.apiman.gateway.engine.impl.DefaultPluginRegistry$$Lambda$513/0x00000000f41a5160.handle(Unknown Source)
        at io.apiman.gateway.engine.impl.DefaultPluginRegistry$2.handle(DefaultPluginRegistry.java:361)
        at io.apiman.gateway.engine.impl.DefaultPluginRegistry$2.handle(DefaultPluginRegistry.java:353)
        at io.apiman.gateway.platforms.vertx3.engine.VertxPluginRegistry.lambda$downloadArtifactTo$2(VertxPluginRegistry.java:140)
        at io.apiman.gateway.platforms.vertx3.engine.VertxPluginRegistry$$Lambda$544/0x00000000f42131e0.handle(Unknown Source)
        at io.vertx.core.Future.lambda$onSuccess$0(Future.java:150)
        at io.vertx.core.Future$$Lambda$546/0x00000000f42137f0.handle(Unknown Source)
        at io.vertx.core.impl.FutureImpl.dispatch(FutureImpl.java:102)
        at io.vertx.core.impl.FutureImpl.tryComplete(FutureImpl.java:150)
        at io.vertx.core.impl.FutureImpl.complete(FutureImpl.java:111)
        at io.vertx.circuitbreaker.impl.CircuitBreakerImpl.lambda$null$4(CircuitBreakerImpl.java:232)
        at io.vertx.circuitbreaker.impl.CircuitBreakerImpl$$Lambda$575/0x00000000e83423a0.handle(Unknown Source)
        at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:366)
        at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38)
        at io.vertx.core.impl.EventLoopContext$$Lambda$68/0x00000000108c5800.run(Unknown Source)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:497)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:826)
Caused by: java.lang.ClassNotFoundException
        at java.lang.ClassLoader.findClass(ClassLoader.java:516)
        at io.apiman.common.plugin.PluginClassLoader.findClass(PluginClassLoader.java:182)
        at java.lang.ClassLoader.loadClassHelper(ClassLoader.java:954)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:899)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:882)
        ... 37 more
```

**Comment by msavy** [comment]
You may need to explicitly include GSON in your plugin's POM dependencies section.

Example (not tested)
```
<dependency>
    <groupId>com.google.code.gson</groupId>
    <artifactId>gson</artifactId>
    <version>2.8.8</version>
</dependency>
```

**Comment by shekarnode** [comment]
Hi marc,
Thanks for prompt reply.
I have already added the dependency in pom.xml .
As i mentioned the custom policy is already working properly with apiman vertx 1.5.7 
but its not working for 2.1.0.

**Comment by msavy** [comment]
There's no easy way for me to know based upon just what you are telling me.

It appears that your GSON dep is not available for some reason.

**Comment by shekarnode** [comment]
Thank you marc for reply
I was already using gson dependency in plugins pom file.
so i moved the dependency to parent pom file and by that the issue got fixed.
