### ISSUE TITLE
Not able to get status of the API : Error: storage transaction is still open for request

### ISSUE THREAD

**Issue by iamakashk** [apiman/apiman#1516]
Hi all,

I am using latest release of the apiman.

I am trying to use following REST API with basic authentication,

http://IP:8080/apiman/organizations/Aphabet_Inc/apis/DemoSample3/versions/1.0/status

For this I am getting internal server error and when I tried to look into the logs I got following trace ,

```
08:54:30,599 ERROR [stderr] (default task-26) java.lang.Exception: Error: storage transaction is still open for request: /organizations/Aphabet_Inc/apis/DemoSample3/versions/1.0/status
08:54:30,600 ERROR [stderr] (default task-26)   at deployment.apiman.war//io.apiman.manager.api.war.TransactionWatchdogFilter.doFilter(TransactionWatchdogFilter.java:60)
08:54:30,600 ERROR [stderr] (default task-26)   at io.undertow.servlet@2.1.3.Final//io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
08:54:30,600 ERROR [stderr] (default task-26)   at io.undertow.servlet@2.1.3.Final//io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
08:54:30,600 ERROR [stderr] (default task-26)   at deployment.apiman.war//io.apiman.manager.api.security.impl.DefaultSecurityContextFilter.doFilter(DefaultSecurityContextFilter.java:55)
08:54:30,600 ERROR [stderr] (default task-26)   at io.undertow.servlet@2.1.3.Final//io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
08:54:30,600 ERROR [stderr] (default task-26)   at io.undertow.servlet@2.1.3.Final//io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
08:54:30,600 ERROR [stderr] (default task-26)   at deployment.apiman.war//io.apiman.common.servlet.DisableCachingFilter.doFilter(DisableCachingFilter.java:52)
08:54:30,600 ERROR [stderr] (default task-26)   at io.undertow.servlet@2.1.3.Final//io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
08:54:30,600 ERROR [stderr] (default task-26)   at io.undertow.servlet@2.1.3.Final//io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
08:54:30,601 ERROR [stderr] (default task-26)   at deployment.apiman.war//io.apiman.common.servlet.ApimanCorsFilter.doFilter(ApimanCorsFilter.java:71)
08:54:30,601 ERROR [stderr] (default task-26)   at io.undertow.servlet@2.1.3.Final//io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
08:54:30,601 ERROR [stderr] (default task-26)   at io.undertow.servlet@2.1.3.Final//io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
08:54:30,601 ERROR [stderr] (default task-26)   at deployment.apiman.war//io.apiman.common.servlet.LocaleFilter.doFilter(LocaleFilter.java:61)
08:54:30,601 ERROR [stderr] (default task-26)   at io.undertow.servlet@2.1.3.Final//io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
08:54:30,601 ERROR [stderr] (default task-26)   at io.undertow.servlet@2.1.3.Final//io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
08:54:30,601 ERROR [stderr] (default task-26)   at io.undertow.servlet@2.1.3.Final//io.undertow.servlet.handlers.FilterHandler.handleRequest(FilterHandler.java:84)
08:54:30,601 ERROR [stderr] (default task-26)   at io.undertow.servlet@2.1.3.Final//io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62)
08:54:30,601 ERROR [stderr] (default task-26)   at io.undertow.servlet@2.1.3.Final//io.undertow.servlet.handlers.ServletChain$1.handleRequest(ServletChain.java:68)
08:54:30,601 ERROR [stderr] (default task-26)   at io.undertow.servlet@2.1.3.Final//io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)
08:54:30,601 ERROR [stderr] (default task-26)   at org.wildfly.extension.undertow@20.0.0.Final//org.wildfly.extension.undertow.security.SecurityContextAssociationHandler.handleRequest(SecurityContextAssociationHandler.java:78)
08:54:30,602 ERROR [stderr] (default task-26)   at io.undertow.core@2.1.3.Final//io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
08:54:30,602 ERROR [stderr] (default task-26)   at org.keycloak.keycloak-undertow-adapter@10.0.2//org.keycloak.adapters.undertow.UndertowAuthenticatedActionsHandler.handleRequest(UndertowAuthenticatedActionsHandler.java:66)
08:54:30,602 ERROR [stderr] (default task-26)   at io.undertow.servlet@2.1.3.Final//io.undertow.servlet.handlers.RedirectDirHandler.handleRequest(RedirectDirHandler.java:68)
08:54:30,602 ERROR [stderr] (default task-26)   at io.undertow.servlet@2.1.3.Final//io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:132)
08:54:30,602 ERROR [stderr] (default task-26)   at io.undertow.servlet@2.1.3.Final//io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57)
08:54:30,602 ERROR [stderr] (default task-26)   at io.undertow.core@2.1.3.Final//io.undertow.server.handlers.DisableCacheHandler.handleRequest(DisableCacheHandler.java:33)
08:54:30,602 ERROR [stderr] (default task-26)   at io.undertow.core@2.1.3.Final//io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
08:54:30,602 ERROR [stderr] (default task-26)   at io.undertow.core@2.1.3.Final//io.undertow.security.handlers.AuthenticationConstraintHandler.handleRequest(AuthenticationConstraintHandler.java:53)
08:54:30,602 ERROR [stderr] (default task-26)   at io.undertow.core@2.1.3.Final//io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46)
08:54:30,602 ERROR [stderr] (default task-26)   at io.undertow.servlet@2.1.3.Final//io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64)
08:54:30,602 ERROR [stderr] (default task-26)   at io.undertow.servlet@2.1.3.Final//io.undertow.servlet.handlers.security.ServletSecurityConstraintHandler.handleRequest(ServletSecurityConstraintHandler.java:59)
08:54:30,603 ERROR [stderr] (default task-26)   at io.undertow.core@2.1.3.Final//io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60)
08:54:30,603 ERROR [stderr] (default task-26)   at io.undertow.servlet@2.1.3.Final//io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77)
08:54:30,603 ERROR [stderr] (default task-26)   at io.undertow.core@2.1.3.Final//io.undertow.security.handlers.NotificationReceiverHandler.handleRequest(NotificationReceiverHandler.java:50)
08:54:30,603 ERROR [stderr] (default task-26)   at io.undertow.core@2.1.3.Final//io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43)
08:54:30,603 ERROR [stderr] (default task-26)   at io.undertow.core@2.1.3.Final//io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
08:54:30,603 ERROR [stderr] (default task-26)   at org.wildfly.extension.undertow@20.0.0.Final//org.wildfly.extension.undertow.security.jacc.JACCContextIdHandler.handleRequest(JACCContextIdHandler.java:61)
08:54:30,603 ERROR [stderr] (default task-26)   at io.undertow.core@2.1.3.Final//io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
08:54:30,603 ERROR [stderr] (default task-26)   at org.wildfly.extension.undertow@20.0.0.Final//org.wildfly.extension.undertow.deployment.GlobalRequestControllerHandler.handleRequest(GlobalRequestControllerHandler.java:68)
08:54:30,603 ERROR [stderr] (default task-26)   at org.keycloak.keycloak-undertow-adapter@10.0.2//org.keycloak.adapters.undertow.ServletPreAuthActionsHandler.handleRequest(ServletPreAuthActionsHandler.java:69)
08:54:30,603 ERROR [stderr] (default task-26)   at io.undertow.core@2.1.3.Final//io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
08:54:30,603 ERROR [stderr] (default task-26)   at io.undertow.servlet@2.1.3.Final//io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:269)
08:54:30,603 ERROR [stderr] (default task-26)   at io.undertow.servlet@2.1.3.Final//io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:78)
08:54:30,603 ERROR [stderr] (default task-26)   at io.undertow.servlet@2.1.3.Final//io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:133)
08:54:30,604 ERROR [stderr] (default task-26)   at io.undertow.servlet@2.1.3.Final//io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:130)
08:54:30,604 ERROR [stderr] (default task-26)   at io.undertow.servlet@2.1.3.Final//io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48)
08:54:30,604 ERROR [stderr] (default task-26)   at io.undertow.servlet@2.1.3.Final//io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
08:54:30,604 ERROR [stderr] (default task-26)   at org.wildfly.extension.undertow@20.0.0.Final//org.wildfly.extension.undertow.security.SecurityContextThreadSetupAction.lambda$create$0(SecurityContextThreadSetupAction.java:105)
08:54:30,604 ERROR [stderr] (default task-26)   at org.wildfly.extension.undertow@20.0.0.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1530)
08:54:30,604 ERROR [stderr] (default task-26)   at org.wildfly.extension.undertow@20.0.0.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1530)
08:54:30,604 ERROR [stderr] (default task-26)   at org.wildfly.extension.undertow@20.0.0.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1530)
08:54:30,604 ERROR [stderr] (default task-26)   at org.wildfly.extension.undertow@20.0.0.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1530)
08:54:30,604 ERROR [stderr] (default task-26)   at org.wildfly.extension.undertow@20.0.0.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1530)
08:54:30,604 ERROR [stderr] (default task-26)   at io.undertow.servlet@2.1.3.Final//io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:249)
08:54:30,604 ERROR [stderr] (default task-26)   at io.undertow.servlet@2.1.3.Final//io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:78)
08:54:30,604 ERROR [stderr] (default task-26)   at io.undertow.servlet@2.1.3.Final//io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:99)
08:54:30,604 ERROR [stderr] (default task-26)   at io.undertow.core@2.1.3.Final//io.undertow.server.Connectors.executeRootHandler(Connectors.java:370)
08:54:30,605 ERROR [stderr] (default task-26)   at io.undertow.core@2.1.3.Final//io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:830)
08:54:30,605 ERROR [stderr] (default task-26)   at org.jboss.threads@2.3.3.Final//org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
08:54:30,605 ERROR [stderr] (default task-26)   at org.jboss.threads@2.3.3.Final//org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1982)
08:54:30,605 ERROR [stderr] (default task-26)   at org.jboss.threads@2.3.3.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1486)
08:54:30,605 ERROR [stderr] (default task-26)   at org.jboss.threads@2.3.3.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1377)
08:54:30,605 ERROR [stderr] (default task-26)   at java.base/java.lang.Thread.run(Thread.java:834)
08:54:30,605 ERROR [io.undertow.request] (default task-26) UT005023: Exception handling request to /apiman/organizations/Aphabet_Inc/apis/DemoSample3/versions/1.0/status: javax.servlet.ServletException: java.lang.Exception: Error: storage transaction is still open for request: /organizations/Aphabet_Inc/apis/DemoSample3/versions/1.0/status
        at deployment.apiman.war//io.apiman.manager.api.war.TransactionWatchdogFilter.doFilter(TransactionWatchdogFilter.java:64)
        at io.undertow.servlet@2.1.3.Final//io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
        at io.undertow.servlet@2.1.3.Final//io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
        at deployment.apiman.war//io.apiman.manager.api.security.impl.DefaultSecurityContextFilter.doFilter(DefaultSecurityContextFilter.java:55)
        at io.undertow.servlet@2.1.3.Final//io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
        at io.undertow.servlet@2.1.3.Final//io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
        at deployment.apiman.war//io.apiman.common.servlet.DisableCachingFilter.doFilter(DisableCachingFilter.java:52)
        at io.undertow.servlet@2.1.3.Final//io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
        at io.undertow.servlet@2.1.3.Final//io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
        at deployment.apiman.war//io.apiman.common.servlet.ApimanCorsFilter.doFilter(ApimanCorsFilter.java:71)
        at io.undertow.servlet@2.1.3.Final//io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
        at io.undertow.servlet@2.1.3.Final//io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
        at deployment.apiman.war//io.apiman.common.servlet.LocaleFilter.doFilter(LocaleFilter.java:61)
        at io.undertow.servlet@2.1.3.Final//io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
        at io.undertow.servlet@2.1.3.Final//io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
        at io.undertow.servlet@2.1.3.Final//io.undertow.servlet.handlers.FilterHandler.handleRequest(FilterHandler.java:84)
        at io.undertow.servlet@2.1.3.Final//io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62)
                at io.undertow.servlet@2.1.3.Final//io.undertow.servlet.handlers.ServletChain$1.handleRequest(ServletChain.java:68)
        at io.undertow.servlet@2.1.3.Final//io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)
        at org.wildfly.extension.undertow@20.0.0.Final//org.wildfly.extension.undertow.security.SecurityContextAssociationHandler.handleRequest(SecurityContextAssociationHandler.java:78)
        at io.undertow.core@2.1.3.Final//io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
        at org.keycloak.keycloak-undertow-adapter@10.0.2//org.keycloak.adapters.undertow.UndertowAuthenticatedActionsHandler.handleRequest(UndertowAuthenticatedActionsHandler.java:66)
        at io.undertow.servlet@2.1.3.Final//io.undertow.servlet.handlers.RedirectDirHandler.handleRequest(RedirectDirHandler.java:68)
        at io.undertow.servlet@2.1.3.Final//io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:132)
        at io.undertow.servlet@2.1.3.Final//io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57)
        at io.undertow.core@2.1.3.Final//io.undertow.server.handlers.DisableCacheHandler.handleRequest(DisableCacheHandler.java:33)
        at io.undertow.core@2.1.3.Final//io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
        at io.undertow.core@2.1.3.Final//io.undertow.security.handlers.AuthenticationConstraintHandler.handleRequest(AuthenticationConstraintHandler.java:53)
        at io.undertow.core@2.1.3.Final//io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46)
        at io.undertow.servlet@2.1.3.Final//io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64)
        at io.undertow.servlet@2.1.3.Final//io.undertow.servlet.handlers.security.ServletSecurityConstraintHandler.handleRequest(ServletSecurityConstraintHandler.java:59)
        at io.undertow.core@2.1.3.Final//io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60)
        at io.undertow.servlet@2.1.3.Final//io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77)
        at io.undertow.core@2.1.3.Final//io.undertow.security.handlers.NotificationReceiverHandler.handleRequest(NotificationReceiverHandler.java:50)
        at io.undertow.core@2.1.3.Final//io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43)
```

After this I went to apiman UI and clicked on sidebar menu and got following error.

![image](https://user-images.githubusercontent.com/19202603/135422072-c070aaec-0f75-4475-afba-d19d7a4032df.png)

I waited for few minutes and tries with status REST API and it works fine same for UI as well. 

Is there anything which I am missing ?

**Comment by volkflo** [comment]
Hi @iamakashk,

can you tell us what version of Apiman you are using?
If possible please try to update to the latest version (2.1.0) of Apiman.
https://github.com/apiman/apiman/releases/tag/2.1.0.Final

**Comment by iamakashk** [comment]
> Hi @iamakashk,
> 
> can you tell us what version of Apiman you are using? If possible please try to update to the latest version (2.1.0) of Apiman. https://github.com/apiman/apiman/releases/tag/2.1.0.Final

I am using this version only.

**Comment by msavy** [comment]
**Describe your setup**
- Environment
  - Operating system (e.g. Linux, Docker, Windows)
  - Java version (e.g. 8, 11, 17)
  - Any custom JVM settings?
- Manager platform e.g. Wildfly, Tomcat)
  -  Component configuration (provide redacted `apiman.properties` or describe).
- Gateway platform (e.g. Vert.x, Wildfly, Tomcat, etc)
  -  Component configuration (provide your redacted `conf.json`, `apiman.properties`, or describe your setup).
- Any alterations to the standard setup (e.g. JVM configuration)
