### ISSUE TITLE
io.apiman.gateway.engine.policies.config.BasicAuthenticationConfig["requestUnmatched"])

### ISSUE THREAD

**Issue by cmoulliard** [apiman/apiman#154]
With the endpoint of the service created and reported [here](https://github.com/apiman/apiman/issues/153) I get this error : 

```
http -a demo:demo --verify=no GET https://localhost:8443/apiman-gateway/demo/CustomerService/2.0/123
HTTP/1.1 500 Internal Server Error
Connection: keep-alive
Date: Thu, 09 Jul 2015 15:52:50 GMT
Server: WildFly/8
Transfer-Encoding: chunked
X-Exception: org.codehaus.jackson.map.exc.UnrecognizedPropertyException: Unrecognized field "requestUnmatched" (Class io.apiman.gateway.engine.policies.config.BasicAuthenticationConfig), not marked as ignorable
X-Powered-By: Undertow/1
at [Source: java.io.StringReader@635a79b4; line: 1, column: 22] (through reference chain: io.apiman.gateway.engine.policies.config.BasicAuthenticationConfig["requestUnmatched"])

io.apiman.gateway.engine.beans.exceptions.ConfigurationParseException: org.codehaus.jackson.map.exc.UnrecognizedPropertyException: Unrecognized field "requestUnmatched" (Class io.apiman.gateway.engine.policies.config.BasicAuthenticationConfig), not marked as ignorable
 at [Source: java.io.StringReader@635a79b4; line: 1, column: 22] (through reference chain: io.apiman.gateway.engine.policies.config.BasicAuthenticationConfig["requestUnmatched"])
	at io.apiman.gateway.engine.policies.AbstractMappedPolicy.parseConfiguration(AbstractMappedPolicy.java:51)
	at io.apiman.gateway.engine.policy.PolicyFactoryImpl.loadConfig(PolicyFactoryImpl.java:63)
	at io.apiman.gateway.engine.impl.ServiceRequestExecutorImpl$5.handle(ServiceRequestExecutorImpl.java:362)
	at io.apiman.gateway.engine.impl.ServiceRequestExecutorImpl$5.handle(ServiceRequestExecutorImpl.java:356)
	at io.apiman.gateway.engine.policy.PolicyFactoryImpl.loadPolicy(PolicyFactoryImpl.java:81)
	at io.apiman.gateway.engine.impl.ServiceRequestExecutorImpl.loadPolicies(ServiceRequestExecutorImpl.java:356)
	at io.apiman.gateway.engine.impl.ServiceRequestExecutorImpl.access$1400(ServiceRequestExecutorImpl.java:76)
	at io.apiman.gateway.engine.impl.ServiceRequestExecutorImpl$3.handle(ServiceRequestExecutorImpl.java:265)
	at io.apiman.gateway.engine.impl.ServiceRequestExecutorImpl$3.handle(ServiceRequestExecutorImpl.java:251)
	at io.apiman.gateway.engine.impl.SecureRegistryWrapper$1.handle(SecureRegistryWrapper.java:105)
	at io.apiman.gateway.engine.impl.SecureRegistryWrapper$1.handle(SecureRegistryWrapper.java:97)
	at io.apiman.gateway.engine.impl.InMemoryRegistry.getService(InMemoryRegistry.java:196)
	at io.apiman.gateway.engine.impl.SecureRegistryWrapper.getService(SecureRegistryWrapper.java:97)
	at io.apiman.gateway.engine.impl.ServiceRequestExecutorImpl.execute(ServiceRequestExecutorImpl.java:250)
	at io.apiman.gateway.platforms.servlet.GatewayServlet.doAction(GatewayServlet.java:234)
	at io.apiman.gateway.platforms.servlet.GatewayServlet.doGet(GatewayServlet.java:80)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:85)
	at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:61)
	at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)
	at org.wildfly.extension.undertow.security.SecurityContextAssociationHandler.handleRequest(SecurityContextAssociationHandler.java:78)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:131)
	at io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:56)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:45)
	at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:63)
	at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:58)
	at io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:70)
	at io.undertow.security.handlers.SecurityInitialHandler.handleRequest(SecurityInitialHandler.java:76)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at org.wildfly.extension.undertow.security.jacc.JACCContextIdHandler.handleRequest(JACCContextIdHandler.java:61)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:261)
	at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:247)
	at io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:76)
	at io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:166)
	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:197)
	at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:759)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.codehaus.jackson.map.exc.UnrecognizedPropertyException: Unrecognized field "requestUnmatched" (Class io.apiman.gateway.engine.policies.config.BasicAuthenticationConfig), not marked as ignorable
 at [Source: java.io.StringReader@635a79b4; line: 1, column: 22] (through reference chain: io.apiman.gateway.engine.policies.config.BasicAuthenticationConfig["requestUnmatched"])
	at org.codehaus.jackson.map.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:53)
	at org.codehaus.jackson.map.deser.StdDeserializationContext.unknownFieldException(StdDeserializationContext.java:267)
	at org.codehaus.jackson.map.deser.std.StdDeserializer.reportUnknownProperty(StdDeserializer.java:673)
	at org.codehaus.jackson.map.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:659)
	at org.codehaus.jackson.map.deser.BeanDeserializer.handleUnknownProperty(BeanDeserializer.java:1365)
	at org.codehaus.jackson.map.deser.BeanDeserializer._handleUnknown(BeanDeserializer.java:725)
	at org.codehaus.jackson.map.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:703)
	at org.codehaus.jackson.map.deser.BeanDeserializer.deserialize(BeanDeserializer.java:580)
	at org.codehaus.jackson.map.ObjectReader._bindAndClose(ObjectReader.java:768)
	at org.codehaus.jackson.map.ObjectReader.readValue(ObjectReader.java:460)
	at io.apiman.gateway.engine.policies.AbstractMappedPolicy.parseConfiguration(AbstractMappedPolicy.java:49)
	... 43 more
```

**Comment by msavy** [comment]
What happens if you do:

```
curl -k -v https://localhost:8443/apiman-gateway/demo/CustomerService/2.0/123 -u demo:demo
```

I wonder if somehow you've provided a BASIC config that shouldn't be allowed. We've not managed to reproduce it yet.

**Comment by msavy** [comment]
@EricWittmann This error looks to me like one the classic Jackson errors where the wrong object arrives to the deserializer (hence field name mismatches).

**Comment by cmoulliard** [comment]
Same response using curl tool instead of httpie (https://github.com/jkbrzt/httpie)

**Comment by cmoulliard** [comment]
I have done this test one hour ago and that was working .... After redeploying apiman, that doesn't work anymore.

**Comment by msavy** [comment]
Do you have the authorization policy added as well, or just that one policy?

**Comment by cmoulliard** [comment]
Just the basic authentication policy

**Comment by cmoulliard** [comment]
I have switched to version 1.1.4.final and don't have this error anymore

**Comment by cmoulliard** [comment]
I suspect that this issue is related the the JVM used (works with JDK 7 but not with JDK 8)

**Comment by EricWittmann** [comment]
Sorry was out of town last week - I'll have a look at this tomorrow.  However, the error implies that the wrong configuration was given to the BasicAuth policy.  The error indicates that some JSON configuration was passed that included a "requestUnmatched" field.  The Authorization policy config has such a field, but the basic auth policy config does not.  I think this is why @msavy asked if you were also using an authorization policy in addition to the basicauth policy.

Will try to reproduce with various VMs tomorrow and see what's what.

**Comment by EricWittmann** [comment]
I've had no luck reproducing this.  :(

**Comment by EricWittmann** [comment]
Any chance of reproducing on a new service on your end?

**Comment by cmoulliard** [comment]
done some tests now but I can't reproduce it anymore
