### ISSUE TITLE
Schema-validation: wrong column type encountered in column [data] in table [api_defs]; found [bytea (Types#BINARY)], but expecting [oid (Types#BLOB)

### ISSUE THREAD

**Issue by mendon26** [apiman/apiman#2043]
I am using Postgres 14 and using the DDL provided to setup the db. But when 

apiman.hibernate.hbm2ddl.auto=validate

```
I get the error: 

18:27:33,053 INFO  [org.hibernate.orm.beans] (Thread-112) HHH10005002: No explicit CDI BeanManager reference was passed to Hibernate, but CDI is available on the Hibernate ClassLoader.
18:27:33,503 ERROR [stderr] (Thread-112) Exception in thread "Thread-112" java.lang.RuntimeException: org.jboss.weld.exceptions.WeldException: WELD-000049: Unable to invoke public void io.apiman.manager.api.jpa.EntityManagerFactoryAccessor.postConstruct() on io.apiman.manager.api.jpa.EntityManagerFactoryAccessor@73688f88
18:27:33,504 ERROR [stderr] (Thread-112) 	at deployment.apiman.war//io.apiman.manager.api.war.WarApiManagerBootstrapperServlet.doImport(WarApiManagerBootstrapperServlet.java:105)
18:27:33,504 ERROR [stderr] (Thread-112) 	at deployment.apiman.war//io.apiman.manager.api.war.WarApiManagerBootstrapperServlet.lambda$init$0(WarApiManagerBootstrapperServlet.java:72)
18:27:33,505 ERROR [stderr] (Thread-112) 	at java.base/java.lang.Thread.run(Thread.java:844)
18:27:33,506 ERROR [stderr] (Thread-112) Caused by: org.jboss.weld.exceptions.WeldException: WELD-000049: Unable to invoke public void io.apiman.manager.api.jpa.EntityManagerFactoryAccessor.postConstruct() on io.apiman.manager.api.jpa.EntityManagerFactoryAccessor@73688f88
18:27:33,506 ERROR [stderr] (Thread-112) 	at org.jboss.weld.core@3.1.6.Final//org.jboss.weld.injection.producer.DefaultLifecycleCallbackInvoker.invokeMethods(DefaultLifecycleCallbackInvoker.java:85)
18:27:33,506 ERROR [stderr] (Thread-112) 	at org.jboss.weld.core@3.1.6.Final//org.jboss.weld.injection.producer.DefaultLifecycleCallbackInvoker.postConstruct(DefaultLifecycleCallbackInvoker.java:66)
18:27:33,507 ERROR [stderr] (Thread-112) 	at org.jboss.weld.core@3.1.6.Final//org.jboss.weld.injection.producer.BasicInjectionTarget.postConstruct(BasicInjectionTarget.java:122)
18:27:33,507 ERROR [stderr] (Thread-112) 	at org.jboss.weld.core@3.1.6.Final//org.jboss.weld.bean.ManagedBean.create(ManagedBean.java:174)
18:27:33,507 ERROR [stderr] (Thread-112) 	at org.jboss.weld.core@3.1.6.Final//org.jboss.weld.contexts.AbstractContext.get(AbstractContext.java:96)
18:27:33,508 ERROR [stderr] (Thread-112) 	at org.jboss.weld.core@3.1.6.Final//org.jboss.weld.bean.ContextualInstanceStrategy$DefaultContextualInstanceStrategy.get(ContextualInstanceStrategy.java:100)
18:27:33,508 ERROR [stderr] (Thread-112) 	at org.jboss.weld.core@3.1.6.Final//org.jboss.weld.bean.ContextualInstanceStrategy$ApplicationScopedContextualInstanceStrategy.get(ContextualInstanceStrategy.java:140)
18:27:33,508 ERROR [stderr] (Thread-112) 	at org.jboss.weld.core@3.1.6.Final//org.jboss.weld.bean.ContextualInstance.get(ContextualInstance.java:50)
18:27:33,508 ERROR [stderr] (Thread-112) 	at org.jboss.weld.core@3.1.6.Final//org.jboss.weld.bean.proxy.ContextBeanInstance.getInstance(ContextBeanInstance.java:102)
18:27:33,509 ERROR [stderr] (Thread-112) 	at org.jboss.weld.core@3.1.6.Final//org.jboss.weld.bean.proxy.ProxyMethodHandler.getInstance(ProxyMethodHandler.java:131)
18:27:33,509 ERROR [stderr] (Thread-112) 	at deployment.apiman.war//io.apiman.manager.api.jpa.EntityManagerFactoryAccessor$Proxy$_$$_WeldClientProxy.getEntityManagerFactory(Unknown Source)
18:27:33,509 ERROR [stderr] (Thread-112) 	at deployment.apiman.war//io.apiman.manager.api.jpa.AbstractJpaStorage.beginTx(AbstractJpaStorage.java:81)
18:27:33,509 ERROR [stderr] (Thread-112) 	at deployment.apiman.war//io.apiman.manager.api.jpa.JpaStorage.beginTx(JpaStorage.java:102)
18:27:33,509 ERROR [stderr] (Thread-112) 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
18:27:33,510 ERROR [stderr] (Thread-112) 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
18:27:33,510 ERROR [stderr] (Thread-112) 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
18:27:33,510 ERROR [stderr] (Thread-112) 	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
18:27:33,510 ERROR [stderr] (Thread-112) 	at org.jboss.weld.core@3.1.6.Final//org.jboss.weld.bean.proxy.AbstractBeanInstance.invoke(AbstractBeanInstance.java:38)
18:27:33,511 ERROR [stderr] (Thread-112) 	at org.jboss.weld.core@3.1.6.Final//org.jboss.weld.bean.proxy.ProxyMethodHandler.invoke(ProxyMethodHandler.java:106)
18:27:33,511 ERROR [stderr] (Thread-112) 	at deployment.apiman.war//io.apiman.manager.api.core.IStorage1436035431$Proxy$_$$_WeldClientProxy.beginTx(Unknown Source)
18:27:33,511 ERROR [stderr] (Thread-112) 	at deployment.apiman.war//io.apiman.manager.api.exportimport.manager.StorageImportDispatcher.start(StorageImportDispatcher.java:158)
18:27:33,511 ERROR [stderr] (Thread-112) 	at deployment.apiman.war//io.apiman.manager.api.war.WarApiManagerBootstrapperServlet.doImport(WarApiManagerBootstrapperServlet.java:101)
18:27:33,511 ERROR [stderr] (Thread-112) 	... 2 more
18:27:33,512 ERROR [stderr] (Thread-112) Caused by: java.lang.reflect.InvocationTargetException
18:27:33,512 ERROR [stderr] (Thread-112) 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
18:27:33,512 ERROR [stderr] (Thread-112) 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
18:27:33,512 ERROR [stderr] (Thread-112) 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
18:27:33,513 ERROR [stderr] (Thread-112) 	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
18:27:33,513 ERROR [stderr] (Thread-112) 	at org.jboss.weld.core@3.1.6.Final//org.jboss.weld.injection.producer.DefaultLifecycleCallbackInvoker.invokeMethods(DefaultLifecycleCallbackInvoker.java:83)
18:27:33,513 ERROR [stderr] (Thread-112) 	... 23 more
18:27:33,514 ERROR [stderr] (Thread-112) Caused by: javax.persistence.PersistenceException: [PersistenceUnit: apiman-manager-api-jpa] Unable to build Hibernate SessionFactory
18:27:33,514 ERROR [stderr] (Thread-112) 	at org.hibernate@5.3.20.Final//org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.persistenceException(EntityManagerFactoryBuilderImpl.java:1327)
18:27:33,515 ERROR [stderr] (Thread-112) 	at org.hibernate@5.3.20.Final//org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.build(EntityManagerFactoryBuilderImpl.java:1253)
18:27:33,517 ERROR [stderr] (Thread-112) 	at org.hibernate@5.3.20.Final//org.hibernate.jpa.HibernatePersistenceProvider.createEntityManagerFactory(HibernatePersistenceProvider.java:56)
18:27:33,518 ERROR [stderr] (Thread-112) 	at javax.persistence.api@2.2.3//javax.persistence.Persistence.createEntityManagerFactory(Persistence.java:80)
18:27:33,519 ERROR [stderr] (Thread-112) 	at deployment.apiman.war//io.apiman.manager.api.jpa.EntityManagerFactoryAccessor.postConstruct(EntityManagerFactoryAccessor.java:76)
18:27:33,519 ERROR [stderr] (Thread-112) 	... 28 more
18:27:33,520 ERROR [stderr] (Thread-112) Caused by: org.hibernate.tool.schema.spi.SchemaManagementException: Schema-validation: wrong column type encountered in column [data] in table [api_defs]; found [bytea (Types#BINARY)], but expecting [oid (Types#BLOB)]
18:27:33,521 ERROR [stderr] (Thread-112) 	at org.hibernate@5.3.20.Final//org.hibernate.tool.schema.internal.AbstractSchemaValidator.validateColumnType(AbstractSchemaValidator.java:159)
18:27:33,521 ERROR [stderr] (Thread-112) 	at org.hibernate@5.3.20.Final//org.hibernate.tool.schema.internal.AbstractSchemaValidator.validateTable(AbstractSchemaValidator.java:143)
18:27:33,522 ERROR [stderr] (Thread-112) 	at org.hibernate@5.3.20.Final//org.hibernate.tool.schema.internal.GroupedSchemaValidatorImpl.validateTables(GroupedSchemaValidatorImpl.java:42)
18:27:33,523 ERROR [stderr] (Thread-112) 	at org.hibernate@5.3.20.Final//org.hibernate.tool.schema.internal.AbstractSchemaValidator.performValidation(AbstractSchemaValidator.java:89)
18:27:33,524 ERROR [stderr] (Thread-112) 	at org.hibernate@5.3.20.Final//org.hibernate.tool.schema.internal.AbstractSchemaValidator.doValidation(AbstractSchemaValidator.java:68)
18:27:33,531 ERROR [stderr] (Thread-112) 	at org.hibernate@5.3.20.Final//org.hibernate.tool.schema.spi.SchemaManagementToolCoordinator.performDatabaseAction(SchemaManagementToolCoordinator.java:191)
18:27:33,534 ERROR [stderr] (Thread-112) 	at org.hibernate@5.3.20.Final//org.hibernate.tool.schema.spi.SchemaManagementToolCoordinator.process(SchemaManagementToolCoordinator.java:72)
18:27:33,535 ERROR [stderr] (Thread-112) 	at org.hibernate@5.3.20.Final//org.hibernate.internal.SessionFactoryImpl.<init>(SessionFactoryImpl.java:310)
18:27:33,535 ERROR [stderr] (Thread-112) 	at org.hibernate@5.3.20.Final//org.hibernate.boot.internal.SessionFactoryBuilderImpl.build(SessionFactoryBuilderImpl.java:467)
18:27:33,536 ERROR [stderr] (Thread-112) 	at org.hibernate@5.3.20.Final//org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.build(EntityManagerFactoryBuilderImpl.java:1250)
18:27:33,536 ERROR [stderr] (Thread-112) 	... 31 more
^C18:31:04,297 INFO  [org.jboss.as.server] (Thread-1) WFLYSRV0272: Suspending server
18:31:04,301 INFO  [org.jboss.as.ejb3] (Thread-1) WFLYEJB0493: Jakarta Enterprise Beans subsystem suspension complete
```

**Comment by mendon26** [comment]
The issue was fixed by rebuild api_defs table and changing the datatype of data column to 'oid'

**Comment by msavy** [comment]
Hi. Which version of Apiman were you using when this happened?

**Comment by mendon26** [comment]
2.2.3.Final

**Comment by msavy** [comment]
I wonder if that coincided with the bump of WildFly and hence Hibernate 🤔
