### ISSUE TITLE
getting  A connection to http://localhost:5052/ was leaked

### ISSUE THREAD

**Issue by shachindrasingh** [apiman/apiman#2222]
### Apiman Version

2.2.3

### Apiman Manager Distro

WildFly

### Apiman Gateway Distro

Tomcat

### Java Version

openjdk version "1.8.0_322"

### Operating System

Lunix

### Are you running Apiman in a container, or on an orchestration platform?

Other (please specify below)

### Describe the bug

we had done the load testing of 10 Active user.  but after some time we got the memory leak issue.   we find the no of connection open at tomcat level were not closed.  find the stack for your reference ..

Caused by: java.io.IOException: Connection reset by peer
       at sun.nio.ch.FileDispatcherImpl.write0(Native Method)
       at sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:47)
       at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:93)
       at sun.nio.ch.IOUtil.write(IOUtil.java:65)
       at sun.nio.ch.UnixAsynchronousSocketChannelImpl.implWrite(UnixAsynchronousSocketChannelImpl.java:694)
       at sun.nio.ch.AsynchronousSocketChannelImpl.write(AsynchronousSocketChannelImpl.java:383)
       at sun.nio.ch.AsynchronousSocketChannelImpl.write(AsynchronousSocketChannelImpl.java:388)
       at org.apache.tomcat.util.net.Nio2Channel.write(Nio2Channel.java:167)
       at org.apache.tomcat.util.net.Nio2Endpoint$Nio2SocketWrapper.doWrite(Nio2Endpoint.java:1221)
       at org.apache.tomcat.util.net.SocketWrapperBase.doWrite(SocketWrapperBase.java:766)
       at org.apache.tomcat.util.net.SocketWrapperBase.flushBlocking(SocketWrapperBase.java:719)
       at org.apache.tomcat.util.net.Nio2Endpoint$Nio2SocketWrapper.flushBlocking(Nio2Endpoint.java:1264)
       at org.apache.tomcat.util.net.SocketWrapperBase.flush(SocketWrapperBase.java:709)
       at org.apache.coyote.http11.Http11OutputBuffer$SocketOutputBuffer.flush(Http11OutputBuffer.java:573)
       at org.apache.coyote.http11.filters.ChunkedOutputFilter.flush(ChunkedOutputFilter.java:157)
       at org.apache.coyote.http11.Http11OutputBuffer.flush(Http11OutputBuffer.java:221)
       at org.apache.coyote.http11.Http11Processor.flush(Http11Processor.java:1205)
       at org.apache.coyote.AbstractProcessor.action(AbstractProcessor.java:402)
       at org.apache.coyote.Response.action(Response.java:209)
       at org.apache.catalina.connector.OutputBuffer.doFlush(OutputBuffer.java:306)
       ... 75 more
01-Aug-2022 19:00:52.104 WARNING [OkHttp ConnectionPool] com.squareup.okhttp.ConnectionPool.pruneAndGetAllocationCount A connection to http://localhost:5052/ was leaked. Did you forget to close a response body?

find the server.xml configuration 

<Connector port="8080" protocol="org.apache.coyote.http11.Http11Nio2Protocol" connectionTimeout="500000" maxThreads="500" enableLookups="false" maxKeepAliveRequests="10" />

export JAVA_OPTS="$JAVA_OPTS\
 -server\
 -Xms4g\
 -Xmx4g\
 -Djio.tomcatlog.base=/usrdata/logs/tomcatlogs\
 -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/tmp\

**Comment by msavy** [comment]
Which policies are in your pipeline?

**Comment by shachindrasingh** [comment]
we had customized Plugin . compile using the 2.2.3 version . we had review all code of that plugin but didn't find any thing. same code based we are using in 1.5.7 version in that we didn't face this issue.

**Comment by msavy** [comment]
You need to mention these kinds of details in bug reports otherwise we have no way of figuring out what is going on.

What happens if you run your load tests without your custom plugin. No policies at all. Does that message ever show?

**Comment by shachindrasingh** [comment]
thanks for prompt respond. if we remove all plugin we find the same issue.  let me tell you where it stuck . every thing goes right till validation but when request reaches to endpoint of that api then this issue occur.  we are also trying to upgrade the tomcat version after that we will check again . because in 9.0.65 version apache had done some fix for memory leakage. but if you can also halp us that would be great.

**Comment by shachindrasingh** [comment]
we had test with the Tomcat 9.0.65 version find the same issue .. in fact this time we had dig down the issue trace. find the exact issue. when APIMAN gatway tried to insert the in data in ES metric index and ES performance is slow.  due to that " client.bulkAsync(request, RequestOptions.DEFAULT, listener)" method is creating the issue.  find the thread and heap dump screen shot for your reference. also we had done the TCP dump we find the the communication between ES and gateway is very slow. instead of bulk insert , we find single record was processed by the gateway .  
we had done some changes in code and doing the load test. we will share detail after that .

<img width="1060" alt="Screenshot 2022-08-02 at 9 07 06 PM" src="https://user-images.githubusercontent.com/8200140/182601061-1d7f9261-283b-410b-9ac6-888be15aafda.png">
<img width="975" alt="MicrosoftTeams-image (2)" src="https://user-images.githubusercontent.com/8200140/182601099-82bf5493-90c4-447f-851d-2d496d6dea1f.png">
<img width="1085" alt="MicrosoftTeams-image (3)" src="https://user-images.githubusercontent.com/8200140/182601108-6b412dcb-1694-4651-ae42-0fea5babd5f6.png">

**Comment by msavy** [comment]
The metrics is on a separate thread, so it should not interfere with the normal proxying functionality

**Comment by shachindrasingh** [comment]
Please check the thread and heap dump. because of ES slowness this create problem. lot's of thread acculated in memory waiting state. finally apiman start throwing out of memory Error.   when we had disable the metric after that we didn't get any issue.

**Comment by msavy** [comment]
There are some improvements to metrics which may be helpful, but they won't be released until 3.0.0.Final. I currently have no plans to backport that work to 2.x.
