### ISSUE TITLE
ES Rate Limiter and Metrics not working with Elastic 8

### ISSUE THREAD

**Issue by esbakker** [apiman/apiman#2665]
### Apiman Version

3.1.2

### Apiman Manager Distro

WildFly

### Apiman Gateway Distro

Vert.x

### Java Version

11 (from vertx-gateway docker image)

### Operating System

eclipse-temurin:11-jre-alpine

### Are you running Apiman in a container, or on an orchestration platform?

OpenShift

### Describe the bug

After upgrading from elastic 7.17.0 to 8.16.1 request fail because of errors with the RateLimit request.

### Expected behaviour

No errors when doing requests.

### Actual behaviour

Requests fail with a 500 error:

```
java.io.IOException: Unable to parse response body for Response{requestLine=PUT /apiman_gateway_ratebucket/_doc/NjMwOWNiZjAtOWNiOC00YTk5LTljM2ItOWM3NGE1NDU1ZDg1NjMwOWNiZjAtOWNiOC00YTk5LTljM2ItOWM3NGE1NDU1ZDg1fHxBUFB8fE9wZW5IZWFsdGhodWJ8fGFzcC1wcm9kdWN0aW9u?timeout=1m HTTP/1.1, host=:9243, response=HTTP/1.1 200 OK}
	at org.elasticsearch.client.RestHighLevelClient.internalPerformRequest(RestHighLevelClient.java:2190) ~[apiman-gateway.jar:?]
	at org.elasticsearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:2137) ~[apiman-gateway.jar:?]
	at org.elasticsearch.client.RestHighLevelClient.performRequestAndParseEntity(RestHighLevelClient.java:2105) ~[apiman-gateway.jar:?]
	at org.elasticsearch.client.RestHighLevelClient.index(RestHighLevelClient.java:1241) ~[apiman-gateway.jar:?]
	at io.apiman.gateway.engine.es.EsRateLimiterComponent.updateBucketAndReturn(EsRateLimiterComponent.java:122) ~[apiman-gateway.jar:?]
	at io.apiman.gateway.engine.es.EsRateLimiterComponent.accept(EsRateLimiterComponent.java:94) ~[apiman-gateway.jar:?]
	at io.apiman.gateway.engine.policies.RateLimitingPolicy.doApply(RateLimitingPolicy.java:94) ~[apiman-gateway.jar:?]
	at io.apiman.gateway.engine.policies.RateLimitingPolicy.doApply(RateLimitingPolicy.java:51) ~[apiman-gateway.jar:?]
	at io.apiman.gateway.engine.policies.AbstractMappedPolicy.apply(AbstractMappedPolicy.java:87) ~[apiman-gateway.jar:?]
	at io.apiman.gateway.engine.policy.RequestChain.lambda$applyPolicy$0(RequestChain.java:67) ~[apiman-gateway.jar:?]
	at io.apiman.gateway.engine.policy.Chain.executeInPolicyContextLoader(Chain.java:299) ~[apiman-gateway.jar:?]
	at io.apiman.gateway.engine.policy.RequestChain.applyPolicy(RequestChain.java:66) ~[apiman-gateway.jar:?]
	at io.apiman.gateway.engine.policy.Chain.doApply(Chain.java:150) ~[apiman-gateway.jar:?]
	at io.apiman.gateway.engine.impl.ApiRequestExecutorImpl.lambda$execute_$5(ApiRequestExecutorImpl.java:298) ~[apiman-gateway.jar:?]
	at io.apiman.gateway.engine.impl.ApiRequestExecutorImpl.lambda$loadPolicies$7(ApiRequestExecutorImpl.java:679) ~[apiman-gateway.jar:?]
	at io.apiman.gateway.engine.policy.PolicyFactoryImpl.loadPolicy(PolicyFactoryImpl.java:95) ~[apiman-gateway.jar:?]
	at io.apiman.gateway.engine.impl.ApiRequestExecutorImpl.loadPolicies(ApiRequestExecutorImpl.java:647) ~[apiman-gateway.jar:?]
	at io.apiman.gateway.engine.impl.ApiRequestExecutorImpl.lambda$execute_$6(ApiRequestExecutorImpl.java:410) ~[apiman-gateway.jar:?]
	at io.apiman.gateway.engine.impl.SecureRegistryWrapper$2.handle(SecureRegistryWrapper.java:189) ~[apiman-gateway.jar:?]
	at io.apiman.gateway.engine.impl.SecureRegistryWrapper$2.handle(SecureRegistryWrapper.java:171) ~[apiman-gateway.jar:?]
	at io.apiman.gateway.engine.es.CachingEsRegistry.getContract(CachingEsRegistry.java:103) ~[apiman-gateway.jar:?]
	at io.apiman.gateway.engine.impl.SecureRegistryWrapper.getContract(SecureRegistryWrapper.java:171) ~[apiman-gateway.jar:?]
	at io.apiman.gateway.engine.impl.ApiRequestExecutorImpl.execute_(ApiRequestExecutorImpl.java:376) ~[apiman-gateway.jar:?]
	at io.apiman.gateway.engine.impl.ApiRequestExecutorImpl.lambda$execute$1(ApiRequestExecutorImpl.java:229) ~[apiman-gateway.jar:?]
	at io.apiman.gateway.engine.impl.SecureRegistryWrapper$1.handle(SecureRegistryWrapper.java:123) ~[apiman-gateway.jar:?]
	at io.apiman.gateway.engine.impl.SecureRegistryWrapper$1.handle(SecureRegistryWrapper.java:112) ~[apiman-gateway.jar:?]
	at io.apiman.gateway.engine.es.CachingEsRegistry.getApi(CachingEsRegistry.java:117) ~[apiman-gateway.jar:?]
	at io.apiman.gateway.engine.impl.SecureRegistryWrapper.getApi(SecureRegistryWrapper.java:112) ~[apiman-gateway.jar:?]
	at io.apiman.gateway.engine.impl.ApiRequestExecutorImpl.execute(ApiRequestExecutorImpl.java:225) ~[apiman-gateway.jar:?]
	at io.apiman.gateway.platforms.vertx3.http.HttpPolicyAdapter._execute(HttpPolicyAdapter.java:112) ~[apiman-gateway.jar:?]
	at io.apiman.gateway.platforms.vertx3.http.HttpPolicyAdapter.execute(HttpPolicyAdapter.java:61) ~[apiman-gateway.jar:?]
	at io.apiman.gateway.platforms.vertx3.verticles.HttpGatewayVerticle.requestHandler(HttpGatewayVerticle.java:55) ~[apiman-gateway.jar:?]
	at io.vertx.core.http.impl.WebSocketRequestHandler.handle(WebSocketRequestHandler.java:50) ~[apiman-gateway.jar:?]
	at io.vertx.core.http.impl.WebSocketRequestHandler.handle(WebSocketRequestHandler.java:32) ~[apiman-gateway.jar:?]
	at io.vertx.core.http.impl.Http1xServerConnection.handleMessage(Http1xServerConnection.java:136) ~[apiman-gateway.jar:?]
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:366) ~[apiman-gateway.jar:?]
	at io.vertx.core.impl.EventLoopContext.execute(EventLoopContext.java:43) ~[apiman-gateway.jar:?]
	at io.vertx.core.impl.ContextImpl.executeFromIO(ContextImpl.java:229) ~[apiman-gateway.jar:?]
	at io.vertx.core.net.impl.VertxHandler.channelRead(VertxHandler.java:164) ~[apiman-gateway.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[apiman-gateway.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[apiman-gateway.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[apiman-gateway.jar:?]
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:93) ~[apiman-gateway.jar:?]
	at io.netty.handler.codec.http.websocketx.extensions.WebSocketServerExtensionHandler.channelRead(WebSocketServerExtensionHandler.java:109) ~[apiman-gateway.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[apiman-gateway.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[apiman-gateway.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[apiman-gateway.jar:?]
	at io.vertx.core.http.impl.Http1xUpgradeToH2CHandler.channelRead(Http1xUpgradeToH2CHandler.java:114) ~[apiman-gateway.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[apiman-gateway.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[apiman-gateway.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[apiman-gateway.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346) ~[apiman-gateway.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318) ~[apiman-gateway.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[apiman-gateway.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[apiman-gateway.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[apiman-gateway.jar:?]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[apiman-gateway.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) ~[apiman-gateway.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[apiman-gateway.jar:?]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[apiman-gateway.jar:?]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) ~[apiman-gateway.jar:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788) ~[apiman-gateway.jar:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724) ~[apiman-gateway.jar:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650) ~[apiman-gateway.jar:?]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562) ~[apiman-gateway.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[apiman-gateway.jar:?]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[apiman-gateway.jar:?]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[apiman-gateway.jar:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.NullPointerException
	at java.util.Objects.requireNonNull(Objects.java:221) ~[?:?]
	at org.elasticsearch.action.DocWriteResponse.<init>(DocWriteResponse.java:116) ~[apiman-gateway.jar:?]
	at org.elasticsearch.action.index.IndexResponse.<init>(IndexResponse.java:43) ~[apiman-gateway.jar:?]
	at org.elasticsearch.action.index.IndexResponse.<init>(IndexResponse.java:28) ~[apiman-gateway.jar:?]
	at org.elasticsearch.action.index.IndexResponse$Builder.build(IndexResponse.java:96) ~[apiman-gateway.jar:?]
	at org.elasticsearch.action.index.IndexResponse.fromXContent(IndexResponse.java:78) ~[apiman-gateway.jar:?]
	at org.elasticsearch.client.RestHighLevelClient.parseEntity(RestHighLevelClient.java:2484) ~[apiman-gateway.jar:?]
	at org.elasticsearch.client.RestHighLevelClient.lambda$performRequestAndParseEntity$8(RestHighLevelClient.java:2105) ~[apiman-gateway.jar:?]
	at org.elasticsearch.client.RestHighLevelClient.internalPerformRequest(RestHighLevelClient.java:2188) ~[apiman-gateway.jar:?]
	... 68 more
```

Also storing metrics fails:
```
java.io.IOException: Unable to parse response body for Response{requestLine=POST /_bulk?timeout=1m HTTP/1.1, host=, response=HTTP/1.1 200 OK}
	at org.elasticsearch.client.RestHighLevelClient$1.onSuccess(RestHighLevelClient.java:2351) ~[apiman-gateway.jar:?]
	at org.elasticsearch.client.RestClient$FailureTrackingResponseListener.onSuccess(RestClient.java:678) ~[apiman-gateway.jar:?]
	at org.elasticsearch.client.RestClient$1.completed(RestClient.java:399) ~[apiman-gateway.jar:?]
	at org.elasticsearch.client.RestClient$1.completed(RestClient.java:393) ~[apiman-gateway.jar:?]
	at org.apache.http.concurrent.BasicFuture.completed(BasicFuture.java:122) ~[apiman-gateway.jar:?]
	at org.apache.http.impl.nio.client.DefaultClientExchangeHandlerImpl.responseCompleted(DefaultClientExchangeHandlerImpl.java:182) ~[apiman-gateway.jar:?]
	at org.apache.http.nio.protocol.HttpAsyncRequestExecutor.processResponse(HttpAsyncRequestExecutor.java:448) ~[apiman-gateway.jar:?]
	at org.apache.http.nio.protocol.HttpAsyncRequestExecutor.inputReady(HttpAsyncRequestExecutor.java:338) ~[apiman-gateway.jar:?]
	at org.apache.http.impl.nio.DefaultNHttpClientConnection.consumeInput(DefaultNHttpClientConnection.java:265) ~[apiman-gateway.jar:?]
	at org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:87) ~[apiman-gateway.jar:?]
	at org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:40) ~[apiman-gateway.jar:?]
	at org.apache.http.impl.nio.reactor.AbstractIODispatch.inputReady(AbstractIODispatch.java:121) ~[apiman-gateway.jar:?]
	at org.apache.http.impl.nio.reactor.BaseIOReactor.readable(BaseIOReactor.java:162) ~[apiman-gateway.jar:?]
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvent(AbstractIOReactor.java:337) ~[apiman-gateway.jar:?]
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvents(AbstractIOReactor.java:315) ~[apiman-gateway.jar:?]
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:276) ~[apiman-gateway.jar:?]
	at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104) ~[apiman-gateway.jar:?]
	at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:591) ~[apiman-gateway.jar:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.NullPointerException
	at java.util.Objects.requireNonNull(Objects.java:221) ~[?:?]
	at org.elasticsearch.action.DocWriteResponse.<init>(DocWriteResponse.java:116) ~[apiman-gateway.jar:?]
	at org.elasticsearch.action.index.IndexResponse.<init>(IndexResponse.java:43) ~[apiman-gateway.jar:?]
	at org.elasticsearch.action.index.IndexResponse.<init>(IndexResponse.java:28) ~[apiman-gateway.jar:?]
	at org.elasticsearch.action.index.IndexResponse$Builder.build(IndexResponse.java:96) ~[apiman-gateway.jar:?]
	at org.elasticsearch.action.index.IndexResponse$Builder.build(IndexResponse.java:93) ~[apiman-gateway.jar:?]
	at org.elasticsearch.action.bulk.BulkItemResponse.fromXContent(BulkItemResponse.java:148) ~[apiman-gateway.jar:?]
	at org.elasticsearch.action.bulk.BulkResponse.fromXContent(BulkResponse.java:184) ~[apiman-gateway.jar:?]
	at org.elasticsearch.client.RestHighLevelClient.parseEntity(RestHighLevelClient.java:2484) ~[apiman-gateway.jar:?]
	at org.elasticsearch.client.RestHighLevelClient.lambda$performRequestAsyncAndParseEntity$10(RestHighLevelClient.java:2245) ~[apiman-gateway.jar:?]
	at org.elasticsearch.client.RestHighLevelClient$1.onSuccess(RestHighLevelClient.java:2349) ~[apiman-gateway.jar:?]
	... 18 more
```

### Anything else?

Maybe this is a feature request to support elastic 8. 

As a workaround I'm now using the InMemoryRateLimiter.

**Comment by msavy** [comment]
Good morning, Eddy. I hope you are well.

Can I suggest that you redact your stack trace, as it contains potentially sensitive information.

Regards,
Marc

**Comment by wbeck-fr** [comment]
Hello.
The client currently used in Apiman is only compatible with Elasticsearch servers running version 7.x. However, it can be made to work with an 8.x server by enabling compatibility mode. This requires the client to send the compatible-with=7 header with each request.

There are two ways to achieve this:

- Use a proxy server: A proxy server can be placed between the client and the Elasticsearch server. The proxy can be configured to add the compatible-with=7 header to all requests forwarded to the Elasticsearch server.
- Develop a new client plugin: An Apiman plugin can be developed to create a new client that natively supports Elasticsearch 8.x. This would be a more long-term solution and eliminate the need for a proxy or compatibility mode.

Regards,
William

**Comment by msavy** [comment]
> * Develop a new client plugin: An Apiman plugin can be developed to create a new client that natively supports Elasticsearch 8.x. This would be a more long-term solution and eliminate the need for a proxy or compatibility mode.

I can look at achieving this for the next version of Apiman.

It's a lot of maintenance effort for BPL, because some people want older versions, others newer, etc. 

Perhaps that's a good downstream enterprise feature for customers who work with BPL, as it will require a lot of ongoing maintenance to sustain numerous older versions of Elasticsearch. Needs money to fund it.

And, of course, there's now OpenSearch to consider.

As a broader question for @wbeck-fr  and @esbakker — what are your thoughts on OpenSearch? Or are you strongly tied to Elasticsearch in your organisations?

**Comment by wbeck-fr** [comment]
Hello Mark,
We use Elasticsearch as a key component of our IT infrastructure (for Kibana visualizations, data caching, etc.) and have recently upgraded to Elasticsearch 8.x. To ensure compatibility with this version, we developed an Apiman plugin to adapt the Elasticsearch client.

We haven't yet evaluated OpenSearch. We chose Elasticsearch for use with Apiman because it's the reference implementation. If this changes, we will re-evaluate our position.

For the maintenance effort, can I suggest you something.
We propose creating a marketplace for exchanging plugins and custom components. Integrating every plugin into the main Apiman project could hinder contributions due to versioning and lifecycle management constraints. A marketplace would allow for more flexibility and community involvement.

Regards,
William

**Comment by msavy** [comment]
> We use Elasticsearch as a key component of our IT infrastructure (for Kibana visualizations, data caching, etc.) and have recently upgraded to Elasticsearch 8.x. To ensure compatibility with this version, we developed an Apiman plugin to adapt the Elasticsearch client.

Fantastic, thanks for the feedback. 

I'd actually like to figure out some way of integrating better visualisations directly into Apiman at some point, but it is more challenging that you might expect, given Apiman's modularity.

> For the maintenance effort, can I suggest you something. We propose creating a marketplace for exchanging plugins and custom components. Integrating every plugin into the main Apiman project could hinder contributions due to versioning and lifecycle management constraints. A marketplace would allow for more flexibility and community involvement.
> 
> Regards, William

Thank you for your thoughts 🙏.

We evaluated this approach in the past, but unfortunately, the amount of money that users were willing to pay in aggregate for plugins did not come even close to paying the cost for a single engineer  — hence, our 'enterprise support' approach that bundles 'everything in', including any addons such as these.

Being an open source engineer by background for many years — the reality of starting Black Parrot Labs to support the project and getting into commercials has been a real eye-opener. I must admit, many of the beliefs I had and assumptions I made as an engineer have proven to be completely wrong over the years!

You can be assured that we will try our best, and I'll continue working very hard.

Thanks @esbakker  and @wbeck-fr  as always for your feedback and support, it's much appreciated 💪.

**Comment by esbakker** [comment]
I looked into creating a plugin and while diving into the elastic code I came across an environment variable that can be set to enable api compatibility in the elastic client:
![image](https://github.com/user-attachments/assets/f36b935b-6c6a-4f46-902e-523627fa49ac)
```
/**
 * Environment variable determining whether to send the 7.x compatibility header
 */
public static final String API_VERSIONING_ENV_VARIABLE = "ELASTIC_CLIENT_APIVERSIONING";
```

Setting the environment variable to `true` seems to have fixed the issue.

**Comment by msavy** [comment]
Nice, that's a really handy solution. I'll make a change to the docs to note this.
