### ISSUE TITLE
Is FullTestSuite class still up to date

### ISSUE THREAD

**Issue by cmoulliard** [apiman/apiman#333]
Is the FullTestSuite testing class still up to date as we have to change using a sys env variable the endpoint gateway to check an external Apiman Server (1.1.9, 1.2, ...) ?

```
mvn test -Dapiman.full-test-suite.gateway-endpoint=https://localhost:8443/apiman-gateway

```

**Comment by EricWittmann** [comment]
I think the FullTestSuite class is still up to date, yes.  Are you running into a problem with it?

**Comment by cmoulliard** [comment]
- I have added a sys env variable on the command line `-Dapiman.full-test-suite.gateway-endpoint=https://localhost:8443/apiman-gateway`  as the address of the gateway is now "https://localhost:8443/apiman-gateway" and not "http://localhost:8080/apiman-gateway"

- Some tests fail due to a PKI error 

````
19:58:21,432  INFO     >> Sending HTTP request to: https://localhost:8443/apiman-gateway/Test/echo/1.0
19:58:21,451  INFO     >> [EXCEPTION] sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
Caused by: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
	at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1937)
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:302)
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:296)
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1478)
	at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:212)
	at sun.security.ssl.Handshaker.processLoop(Handshaker.java:979)
	at sun.security.ssl.Handshaker.process_record(Handshaker.java:914)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1050)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1363)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1391)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1375)
	at com.squareup.okhttp.internal.http.SocketConnector.connectTls(SocketConnector.java:103)
	at com.squareup.okhttp.Connection.connect(Connection.java:143)
	at com.squareup.okhttp.Connection.connectAndSetOwner(Connection.java:185)
	at com.squareup.okhttp.OkHttpClient$1.connectAndSetOwner(OkHttpClient.java:128)
	at com.squareup.okhttp.internal.http.HttpEngine.nextConnection(HttpEngine.java:341)
	at com.squareup.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:330)
	at com.squareup.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:248)
	at com.squareup.okhttp.Call.getResponse(Call.java:273)
	at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:230)
	at com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call.java:201)
	at com.squareup.okhttp.Call.execute(Call.java:81)
	at io.apiman.test.common.util.TestPlanRunner.runTest(TestPlanRunner.java:175)
	at io.apiman.manager.test.junit.ManagerRestTester$4.evaluate(ManagerRestTester.java:317)
```

**Comment by msavy** [comment]
I don't think these tests are expecting an SSL endpoint

**Comment by cmoulliard** [comment]
But this is this endpoint which is used by default with the distribution of apiman (Manager/Gateway) ...

**Comment by EricWittmann** [comment]
The distribution supports both SSL on port 8443 and non-SSL on port 8080.  That said, I suppose the testing framework should support self-signed SSL certs.  No harm in it.

**Comment by cmoulliard** [comment]
Nevertheless the test fails as it can't get a valid certification path "unable to find valid certification path to requested target". I will debug to have a look.

**Comment by EricWittmann** [comment]
I think what we're saying is that if you use port 8080 with http instead of https on port 8443 then it should work (and that's the default for the test).

That said, I believe the error you are getting comes from the fact that the REST client used by the test framework doesn't support self-signed SSL certificates.  The solution would be to modify the test client so that it doesn't care who signed the SSL cert.
