### ISSUE TITLE
Standalone manager can't be started using mvn -Prun

### ISSUE THREAD

**Issue by cmoulliard** [apiman/apiman#342]
location : /home/dabou/Repos/apiman/apiman-core-forked/tools/dev-server

```
[dabou@localhost manager-api] $ mvn install -Prun
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building apiman-tools-dev-server-manager-api 1.2.2-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[WARNING] The POM for org.glassfish:javax.el:jar:3.0.1-b06-SNAPSHOT is missing, no dependency information available
[WARNING] The POM for org.glassfish:javax.el:jar:3.0.1-b07-SNAPSHOT is missing, no dependency information available
[WARNING] The POM for org.glassfish:javax.el:jar:3.0.1-b08-SNAPSHOT is missing, no dependency information available
[INFO] 
[INFO] --- maven-resources-plugin:2.7:resources (default-resources) @ apiman-tools-dev-server-manager-api ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 2 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.2:compile (default-compile) @ apiman-tools-dev-server-manager-api ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- maven-resources-plugin:2.7:testResources (default-testResources) @ apiman-tools-dev-server-manager-api ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 3 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.2:testCompile (default-testCompile) @ apiman-tools-dev-server-manager-api ---
[INFO] No sources to compile
[INFO] 
[INFO] --- maven-surefire-plugin:2.17:test (default-test) @ apiman-tools-dev-server-manager-api ---
[INFO] 
[INFO] >>> exec-maven-plugin:1.2.1:java (run) > validate @ apiman-tools-dev-server-manager-api >>>
[INFO] 
[INFO] <<< exec-maven-plugin:1.2.1:java (run) < validate @ apiman-tools-dev-server-manager-api <<<
[INFO] 
[INFO] --- exec-maven-plugin:1.2.1:java (run) @ apiman-tools-dev-server-manager-api ---
**** Starting Server (ManagerApiTestServer)
08:56:32,713  INFO Logging initialized @3592ms
DataSource created and bound to JNDI.
08:56:33,345  INFO jetty-9.2.10.v20150310
08:56:33,430  INFO WELD-ENV-001007: Initialize Weld using ServletContextListener
08:56:33,452  INFO WELD-000900: 2.3.0 (Final)
08:56:33,767  INFO WELD-000101: Transactional services not available. Injection of @Inject UserTransaction not available. Transactional observers will be invoked synchronously.
08:56:33,819  WARN WELD-001700: Interceptor annotation class javax.ejb.PostActivate not found, interception based on it is not enabled
08:56:33,820  WARN WELD-001700: Interceptor annotation class javax.ejb.PrePassivate not found, interception based on it is not enabled
08:56:33,942  INFO WELD-000411: Observer method [BackedAnnotatedMethod] public org.jboss.resteasy.cdi.ResteasyCdiExtension.observeResources(@Observes ProcessAnnotatedType<T>, BeanManager) receives events for all annotated types. Consider restricting events using @WithAnnotations or a generic type with bounds.
08:56:34,129  INFO WELD-000119: Not generating any bean definitions from io.apiman.manager.test.junit.ManagerRestTester because of underlying class loading error: Type org.junit.runners.ParentRunner not found.  If this is unexpected, enable DEBUG logging to see the full error.
08:56:34,129  INFO WELD-000119: Not generating any bean definitions from io.apiman.manager.test.junit.ManagerRestTester$3 because of underlying class loading error: Type org.junit.runners.model.Statement not found.  If this is unexpected, enable DEBUG logging to see the full error.
08:56:34,132  INFO WELD-000119: Not generating any bean definitions from io.apiman.manager.test.junit.ManagerRestTester$1 because of underlying class loading error: Type org.junit.runners.ParentRunner not found.  If this is unexpected, enable DEBUG logging to see the full error.
08:56:34,137  INFO WELD-000119: Not generating any bean definitions from io.apiman.manager.test.junit.ManagerRestTester$4 because of underlying class loading error: Type org.junit.runners.model.Statement not found.  If this is unexpected, enable DEBUG logging to see the full error.
08:56:34,138  INFO WELD-000119: Not generating any bean definitions from io.apiman.manager.test.junit.ManagerRestTester$2 because of underlying class loading error: Type org.junit.runners.model.Statement not found.  If this is unexpected, enable DEBUG logging to see the full error.
08:56:34,143  INFO WELD-000119: Not generating any bean definitions from io.apiman.manager.test.junit.ManagerRestTester$GatewayAssertionTestInfo because of underlying class loading error: Type org.junit.runners.ParentRunner not found.  If this is unexpected, enable DEBUG logging to see the full error.
08:56:34,145  INFO WELD-000119: Not generating any bean definitions from io.apiman.manager.test.junit.ManagerRestTester$PublishPayloadTestInfo because of underlying class loading error: Type org.junit.runners.ParentRunner not found.  If this is unexpected, enable DEBUG logging to see the full error.
08:56:34,146  INFO WELD-000119: Not generating any bean definitions from io.apiman.manager.test.junit.ManagerRestTester$TestInfo because of underlying class loading error: Type org.junit.runners.ParentRunner not found.  If this is unexpected, enable DEBUG logging to see the full error.
08:56:34,148  INFO WELD-000119: Not generating any bean definitions from io.apiman.manager.test.junit.ManagerRestTester$TestPlanInfo because of underlying class loading error: Type org.junit.runners.ParentRunner not found.  If this is unexpected, enable DEBUG logging to see the full error.
08:56:34,356  INFO WELD-ENV-001201: Jetty 7.2+ detected, CDI injection will be available in Servlets and Filters. Injection into Listeners is not supported.
08:56:34,924  WARN FAILED o.e.j.s.ServletContextHandler@4b342442{/apiman,null,STARTING}: org.jboss.weld.exceptions.DeploymentException: WELD-001409: Ambiguous dependencies for type ApiManagerConfig with qualifiers @Default
  at injection point [BackedAnnotatedField] @Inject io.apiman.manager.api.rest.impl.PluginResourceImpl.config
  at io.apiman.manager.api.rest.impl.PluginResourceImpl.config(PluginResourceImpl.java:0)
  Possible dependencies: 
  - Managed Bean [class io.apiman.manager.test.server.ManagerApiTestServerConfig] with qualifiers [@Any @Default],
  - Managed Bean [class io.apiman.tools.devsvr.manager.api.ManagerApiDevServerConfig] with qualifiers [@Any @Default]

org.jboss.weld.exceptions.DeploymentException: WELD-001409: Ambiguous dependencies for type ApiManagerConfig with qualifiers @Default
  at injection point [BackedAnnotatedField] @Inject io.apiman.manager.api.rest.impl.PluginResourceImpl.config
  at io.apiman.manager.api.rest.impl.PluginResourceImpl.config(PluginResourceImpl.java:0)
  Possible dependencies: 
  - Managed Bean [class io.apiman.manager.test.server.ManagerApiTestServerConfig] with qualifiers [@Any @Default],
  - Managed Bean [class io.apiman.tools.devsvr.manager.api.ManagerApiDevServerConfig] with qualifiers [@Any @Default]

	at org.jboss.weld.bootstrap.Validator.validateInjectionPointForDeploymentProblems(Validator.java:367)
	at org.jboss.weld.bootstrap.Validator.validateInjectionPoint(Validator.java:281)
	at org.jboss.weld.bootstrap.Validator.validateGeneralBean(Validator.java:134)
	at org.jboss.weld.bootstrap.Validator.validateRIBean(Validator.java:155)
	at org.jboss.weld.bootstrap.Validator.validateBean(Validator.java:518)
	at org.jboss.weld.bootstrap.ConcurrentValidator$1.doWork(ConcurrentValidator.java:68)
	at org.jboss.weld.bootstrap.ConcurrentValidator$1.doWork(ConcurrentValidator.java:66)
	at org.jboss.weld.executor.IterativeWorkerTaskFactory$1.call(IterativeWorkerTaskFactory.java:63)
	at org.jboss.weld.executor.IterativeWorkerTaskFactory$1.call(IterativeWorkerTaskFactory.java:56)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
08:56:34,961  WARN FAILED org.eclipse.jetty.server.handler.ContextHandlerCollection@652a9d04[o.e.j.s.ServletContextHandler@4b342442{/apiman,null,STARTING}, o.e.j.s.ServletContextHandler@450909a7{/mock-gateway,null,null}]: org.jboss.weld.exceptions.DeploymentException: WELD-001409: Ambiguous dependencies for type ApiManagerConfig with qualifiers @Default
  at injection point [BackedAnnotatedField] @Inject io.apiman.manager.api.rest.impl.PluginResourceImpl.config
  at io.apiman.manager.api.rest.impl.PluginResourceImpl.config(PluginResourceImpl.java:0)
  Possible dependencies: 
  - Managed Bean [class io.apiman.manager.test.server.ManagerApiTestServerConfig] with qualifiers [@Any @Default],
  - Managed Bean [class io.apiman.tools.devsvr.manager.api.ManagerApiDevServerConfig] with qualifiers [@Any @Default]

org.jboss.weld.exceptions.DeploymentException: WELD-001409: Ambiguous dependencies for type ApiManagerConfig with qualifiers @Default
  at injection point [BackedAnnotatedField] @Inject io.apiman.manager.api.rest.impl.PluginResourceImpl.config
  at io.apiman.manager.api.rest.impl.PluginResourceImpl.config(PluginResourceImpl.java:0)
  Possible dependencies: 
  - Managed Bean [class io.apiman.manager.test.server.ManagerApiTestServerConfig] with qualifiers [@Any @Default],
  - Managed Bean [class io.apiman.tools.devsvr.manager.api.ManagerApiDevServerConfig] with qualifiers [@Any @Default]

	at org.jboss.weld.bootstrap.Validator.validateInjectionPointForDeploymentProblems(Validator.java:367)
	at org.jboss.weld.bootstrap.Validator.validateInjectionPoint(Validator.java:281)
	at org.jboss.weld.bootstrap.Validator.validateGeneralBean(Validator.java:134)
	at org.jboss.weld.bootstrap.Validator.validateRIBean(Validator.java:155)
	at org.jboss.weld.bootstrap.Validator.validateBean(Validator.java:518)
	at org.jboss.weld.bootstrap.ConcurrentValidator$1.doWork(ConcurrentValidator.java:68)
	at org.jboss.weld.bootstrap.ConcurrentValidator$1.doWork(ConcurrentValidator.java:66)
	at org.jboss.weld.executor.IterativeWorkerTaskFactory$1.call(IterativeWorkerTaskFactory.java:63)
	at org.jboss.weld.executor.IterativeWorkerTaskFactory$1.call(IterativeWorkerTaskFactory.java:56)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
08:56:34,974  INFO Started ServerConnector@41c22894{HTTP/1.1}{0.0.0.0:7070}
08:56:34,975  WARN FAILED org.eclipse.jetty.server.Server@a7e8e2a: org.jboss.weld.exceptions.DeploymentException: WELD-001409: Ambiguous dependencies for type ApiManagerConfig with qualifiers @Default
  at injection point [BackedAnnotatedField] @Inject io.apiman.manager.api.rest.impl.PluginResourceImpl.config
  at io.apiman.manager.api.rest.impl.PluginResourceImpl.config(PluginResourceImpl.java:0)
  Possible dependencies: 
  - Managed Bean [class io.apiman.manager.test.server.ManagerApiTestServerConfig] with qualifiers [@Any @Default],
  - Managed Bean [class io.apiman.tools.devsvr.manager.api.ManagerApiDevServerConfig] with qualifiers [@Any @Default]

org.jboss.weld.exceptions.DeploymentException: WELD-001409: Ambiguous dependencies for type ApiManagerConfig with qualifiers @Default
  at injection point [BackedAnnotatedField] @Inject io.apiman.manager.api.rest.impl.PluginResourceImpl.config
  at io.apiman.manager.api.rest.impl.PluginResourceImpl.config(PluginResourceImpl.java:0)
  Possible dependencies: 
  - Managed Bean [class io.apiman.manager.test.server.ManagerApiTestServerConfig] with qualifiers [@Any @Default],
  - Managed Bean [class io.apiman.tools.devsvr.manager.api.ManagerApiDevServerConfig] with qualifiers [@Any @Default]

	at org.jboss.weld.bootstrap.Validator.validateInjectionPointForDeploymentProblems(Validator.java:367)
	at org.jboss.weld.bootstrap.Validator.validateInjectionPoint(Validator.java:281)
	at org.jboss.weld.bootstrap.Validator.validateGeneralBean(Validator.java:134)
	at org.jboss.weld.bootstrap.Validator.validateRIBean(Validator.java:155)
	at org.jboss.weld.bootstrap.Validator.validateBean(Validator.java:518)
	at org.jboss.weld.bootstrap.ConcurrentValidator$1.doWork(ConcurrentValidator.java:68)
	at org.jboss.weld.bootstrap.ConcurrentValidator$1.doWork(ConcurrentValidator.java:66)
	at org.jboss.weld.executor.IterativeWorkerTaskFactory$1.call(IterativeWorkerTaskFactory.java:63)
	at org.jboss.weld.executor.IterativeWorkerTaskFactory$1.call(IterativeWorkerTaskFactory.java:56)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[WARNING] 
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:297)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.jboss.weld.exceptions.DeploymentException: WELD-001409: Ambiguous dependencies for type ApiManagerConfig with qualifiers @Default
  at injection point [BackedAnnotatedField] @Inject io.apiman.manager.api.rest.impl.PluginResourceImpl.config
  at io.apiman.manager.api.rest.impl.PluginResourceImpl.config(PluginResourceImpl.java:0)
  Possible dependencies: 
  - Managed Bean [class io.apiman.manager.test.server.ManagerApiTestServerConfig] with qualifiers [@Any @Default],
  - Managed Bean [class io.apiman.tools.devsvr.manager.api.ManagerApiDevServerConfig] with qualifiers [@Any @Default]

	at org.jboss.weld.bootstrap.Validator.validateInjectionPointForDeploymentProblems(Validator.java:367)
	at org.jboss.weld.bootstrap.Validator.validateInjectionPoint(Validator.java:281)
	at org.jboss.weld.bootstrap.Validator.validateGeneralBean(Validator.java:134)
	at org.jboss.weld.bootstrap.Validator.validateRIBean(Validator.java:155)
	at org.jboss.weld.bootstrap.Validator.validateBean(Validator.java:518)
	at org.jboss.weld.bootstrap.ConcurrentValidator$1.doWork(ConcurrentValidator.java:68)
	at org.jboss.weld.bootstrap.ConcurrentValidator$1.doWork(ConcurrentValidator.java:66)
	at org.jboss.weld.executor.IterativeWorkerTaskFactory$1.call(IterativeWorkerTaskFactory.java:63)
	at org.jboss.weld.executor.IterativeWorkerTaskFactory$1.call(IterativeWorkerTaskFactory.java:56)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	... 1 more

```

**Comment by EricWittmann** [comment]
Moved issue to here:
https://issues.jboss.org/browse/APIMAN-920
