### ISSUE TITLE
schema validation error in 1.2.5final mysql

### ISSUE THREAD

**Issue by lscalpati** [apiman/apiman#489]
I get a schema validation error when I try to log into apiman for the auditlog table data column.  Wants type to be longtext but validator sees varchar.  The database schema reflects longtext

mysql describe auditlog:

```
   -> ;
+-----------------+--------------+------+-----+---------+-------+
| Field           | Type         | Null | Key | Default | Extra |
+-----------------+--------------+------+-----+---------+-------+
| id              | bigint(20)   | NO   | PRI | NULL    |       |
| created_on      | datetime     | NO   |     | NULL    |       |
| data            | longtext     | YES  |     | NULL    |       |
| entity_id       | varchar(255) | YES  |     | NULL    |       |
| entity_type     | varchar(255) | NO   |     | NULL    |       |
| entity_version  | varchar(255) | YES  |     | NULL    |       |
| organization_id | varchar(255) | NO   | MUL | NULL    |       |
| what            | varchar(255) | NO   |     | NULL    |       |
| who             | varchar(255) | NO   | MUL | NULL    |       |
+-----------------+--------------+------+-----+---------+-------+
9 rows in set (0.00 sec)
```

I get the following error when I try to log into apiman in the logs:

```
manager_1  | 20:22:39,914 INFO  [org.hibernate.tool.hbm2ddl.SchemaValidator] (default task-4) HHH000229: Running schema validator
manager_1  | 20:22:40,012 ERROR [io.undertow.request] (default task-4) UT005023: Exception handling request to /apiman/currentuser/in
fo: org.jboss.resteasy.spi.UnhandledException: org.jboss.weld.exceptions.WeldException: WELD-000049: Unable to invoke public void io.
apiman.manager.api.jpa.EntityManagerFactoryAccessor.postConstruct() on io.apiman.manager.api.jpa.EntityManagerFactoryAccessor@39e1a9c
e
manager_1  |    at org.jboss.resteasy.core.ExceptionHandler.handleApplicationException(ExceptionHandler.java:76)
manager_1  |    at org.jboss.resteasy.core.ExceptionHandler.handleException(ExceptionHandler.java:212)
manager_1  |    at org.jboss.resteasy.core.SynchronousDispatcher.writeException(SynchronousDispatcher.java:168)
manager_1  |    at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:411)
manager_1  |    at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:202)
manager_1  |    at org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.service(ServletContainerDispatcher.java:221)
manager_1  |    at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:56)
manager_1  |    at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:51)
manager_1  |    at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
manager_1  |    at io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:85)
manager_1  |    at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:129)
manager_1  |    at io.apiman.common.servlet.RootResourceFilter.doFilter(RootResourceFilter.java:59)
manager_1  |    at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:60)
manager_1  |    at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
manager_1  |    at io.apiman.manager.api.war.TransactionWatchdogFilter.doFilter(TransactionWatchdogFilter.java:57)
manager_1  |    at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:60)
manager_1  |    at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
manager_1  |    at io.apiman.manager.api.security.impl.DefaultSecurityContextFilter.doFilter(DefaultSecurityContextFilter.java:56)
manager_1  |    at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:60)
manager_1  |    at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
manager_1  |    at io.apiman.common.servlet.DisableCachingFilter.doFilter(DisableCachingFilter.java:59)
manager_1  |    at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:60)
manager_1  |    at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
manager_1  |    at io.apiman.common.servlet.ApimanCorsFilter.doFilter(ApimanCorsFilter.java:71)
manager_1  |    at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:60)
manager_1  |    at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
manager_1  |    at io.apiman.common.servlet.LocaleFilter.doFilter(LocaleFilter.java:61)
manager_1  |    at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:60)
manager_1  |    at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
manager_1  |    at io.undertow.servlet.handlers.FilterHandler.handleRequest(FilterHandler.java:84)
manager_1  |    at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62)
manager_1  |    at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)
manager_1  |    at org.wildfly.extension.undertow.security.SecurityContextAssociationHandler.handleRequest(SecurityContextAssociationHandler.java:78)
manager_1  |    at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
manager_1  |    at org.keycloak.adapters.undertow.UndertowAuthenticatedActionsHandler.handleRequest(UndertowAuthenticatedActionsHandler.java:66)
manager_1  |    at io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:131)
manager_1  |    at io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57)
manager_1  |    at io.undertow.server.handlers.DisableCacheHandler.handleRequest(DisableCacheHandler.java:33)
manager_1  |    at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
manager_1  |    at io.undertow.security.handlers.AuthenticationConstraintHandler.handleRequest(AuthenticationConstraintHandler.java:51)
manager_1  |    at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46)
manager_1  |    at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64)
manager_1  |    at io.undertow.servlet.handlers.security.ServletSecurityConstraintHandler.handleRequest(ServletSecurityConstraintHandler.java:56)
manager_1  |    at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60)
manager_1  |    at io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77)
manager_1  |    at io.undertow.security.handlers.NotificationReceiverHandler.handleRequest(NotificationReceiverHandler.java:50)
manager_1  |    at io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43)
manager_1  |    at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
manager_1  |    at org.wildfly.extension.undertow.security.jacc.JACCContextIdHandler.handleRequest(JACCContextIdHandler.java:61)
manager_1  |    at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
manager_1  |    at org.keycloak.adapters.undertow.ServletPreAuthActionsHandler.handleRequest(ServletPreAuthActionsHandler.java:69)
manager_1  |    at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
manager_1  |    at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:284)
manager_1  |    at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:263)
manager_1  |    at io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:81)
manager_1  |    at io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:174)
manager_1  |    at io.undertow.server.Connectors.executeRootHandler(Connectors.java:202)
manager_1  |    at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:793)
manager_1  |    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
manager_1  |    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
manager_1  |    at java.lang.Thread.run(Thread.java:745)
manager_1  | Caused by: org.jboss.weld.exceptions.WeldException: WELD-000049: Unable to invoke public void io.apiman.manager.api.jpa.EntityManagerFactoryAccessor.postConstruct() on io.apiman.manager.api.jpa.EntityManagerFactoryAccessor@39e1a9ce
manager_1  |    at org.jboss.weld.injection.producer.DefaultLifecycleCallbackInvoker.invokeMethods(DefaultLifecycleCallbackInvoker.java:100)
manager_1  |    at org.jboss.weld.injection.producer.DefaultLifecycleCallbackInvoker.postConstruct(DefaultLifecycleCallbackInvoker.java:81)
manager_1  |    at org.jboss.weld.injection.producer.BasicInjectionTarget.postConstruct(BasicInjectionTarget.java:126)
manager_1  |    at org.jboss.weld.bean.ManagedBean.create(ManagedBean.java:162)
manager_1  |    at org.jboss.weld.context.AbstractContext.get(AbstractContext.java:96)
manager_1  |    at org.jboss.weld.bean.ContextualInstanceStrategy$DefaultContextualInstanceStrategy.get(ContextualInstanceStrategy.java:101)
manager_1  |    at org.jboss.weld.bean.ContextualInstanceStrategy$ApplicationScopedContextualInstanceStrategy.get(ContextualInstanceStrategy.java:141)
manager_1  |    at org.jboss.weld.bean.ContextualInstance.get(ContextualInstance.java:50)
manager_1  |    at org.jboss.weld.bean.proxy.ContextBeanInstance.getInstance(ContextBeanInstance.java:99)
manager_1  |    at org.jboss.weld.bean.proxy.ProxyMethodHandler.getInstance(ProxyMethodHandler.java:125)
manager_1  |    at io.apiman.manager.api.jpa.EntityManagerFactoryAccessor$Proxy$_$$_WeldClientProxy.getEntityManagerFactory(Unknown Source)
manager_1  |    at io.apiman.manager.api.jpa.AbstractJpaStorage.beginTx(AbstractJpaStorage.java:81)
manager_1  |    at io.apiman.manager.api.jpa.JpaStorage.beginTx(JpaStorage.java:130)
manager_1  |    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
manager_1  |    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
manager_1  |    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
manager_1  |    at java.lang.reflect.Method.invoke(Method.java:498)
manager_1  |    at org.jboss.weld.bean.proxy.AbstractBeanInstance.invoke(AbstractBeanInstance.java:38)
manager_1  |    at org.jboss.weld.bean.proxy.ProxyMethodHandler.invoke(ProxyMethodHandler.java:100)
manager_1  |    at org.jboss.weld.proxies.IStorage$816713466$Proxy$_$$_WeldClientProxy.beginTx(Unknown Source)
manager_1  |    at io.apiman.manager.api.rest.impl.CurrentUserResourceImpl.getInfo(CurrentUserResourceImpl.java:81)
manager_1  |    at io.apiman.manager.api.rest.impl.CurrentUserResourceImpl$Proxy$_$$_WeldClientProxy.getInfo(Unknown Source)
manager_1  |    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
manager_1  |    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
manager_1  |    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
manager_1  |    at java.lang.reflect.Method.invoke(Method.java:498)
manager_1  |    at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:139)
manager_1  |    at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:295)
manager_1  |    at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:249)
manager_1  |    at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:236)
manager_1  |    at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:395)
manager_1  |    ... 57 more
manager_1  | Caused by: java.lang.reflect.InvocationTargetException
manager_1  |    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
manager_1  |    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
manager_1  |    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
manager_1  |    at java.lang.reflect.Method.invoke(Method.java:498)
manager_1  |    at org.jboss.weld.injection.producer.DefaultLifecycleCallbackInvoker.invokeMethods(DefaultLifecycleCallbackInvoker.java:98)
manager_1  |    ... 87 more
manager_1  | Caused by: javax.persistence.PersistenceException: [PersistenceUnit: apiman-manager-api-jpa] Unable to build Hibernate SessionFactory
manager_1  |    at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.persistenceException(EntityManagerFactoryBuilderImpl.java:954)
manager_1  |    at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.build(EntityManagerFactoryBuilderImpl.java:882)
manager_1  |    at org.hibernate.jpa.HibernatePersistenceProvider.createEntityManagerFactory(HibernatePersistenceProvider.java:58)
manager_1  |    at javax.persistence.Persistence.createEntityManagerFactory(Persistence.java:55)
manager_1  |    at io.apiman.manager.api.jpa.EntityManagerFactoryAccessor.postConstruct(EntityManagerFactoryAccessor.java:76)
manager_1  |    ... 92 more
manager_1  | Caused by: org.hibernate.tool.schema.spi.SchemaManagementException: Schema-validation: wrong column type encountered in column [data] in table [auditlog]; found [varchar (Types#VARCHAR)], but expecting [longtext (Types#LONGVARCHAR)]
manager_1  |    at org.hibernate.tool.schema.internal.SchemaValidatorImpl.validateColumnType(SchemaValidatorImpl.java:105)
manager_1  |    at org.hibernate.tool.schema.internal.SchemaValidatorImpl.validateTable(SchemaValidatorImpl.java:92)
manager_1  |    at org.hibernate.tool.schema.internal.SchemaValidatorImpl.doValidation(SchemaValidatorImpl.java:50)
manager_1  |    at org.hibernate.tool.hbm2ddl.SchemaValidator.validate(SchemaValidator.java:91)
manager_1  |    at org.hibernate.internal.SessionFactoryImpl.<init>(SessionFactoryImpl.java:473)
manager_1  |    at org.hibernate.boot.internal.SessionFactoryBuilderImpl.build(SessionFactoryBuilderImpl.java:444)
manager_1  |    at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.build(EntityManagerFactoryBuilderImpl.java:879)
manager_1  |    ... 95 more
```

**Comment by lscalpati** [comment]
update:  when I switched:
```apiman.hibernate.hbm2ddl.auto=validate```
to
```apiman.hibernate.hbm2ddl.auto=update```
and dropped the database and re-created an empty database it worked.  I dropped and re-added the database and schema previous with no avail - something with the =vaidate????

**Comment by EricWittmann** [comment]
What version of mysql are you using? 

What hibernate dialect do you have configured in apiman.properties?
