### ISSUE TITLE
Unable to run Apiman on Docker with non embedded DB, ES and Keycloak

### ISSUE THREAD

**Issue by ndziePatrickJoel** [apiman/apiman#733]
I want to run apiman with the configuration below

- A separated database
- A separated es instance (1.7.3)
- A separated keycloak instance 
-  The Manager and the gateway in the same container 

This is the Dockerfile i have written

`FROM apiman/on-wildfly11

#on met à jour le fichier standalone de apiman

WORKDIR /opt/jboss/wildfly

COPY ./mysql-connector-java-5.1.33-bin.jar standalone/deployments/mysql-connector-java-5.1.33-bin.jar
ENV DATABASE_TYPE="x1"
ENV DATABASE_HOST=172.21.95.88
ENV DATABASE_PORT=3306
ENV DATABASE_USER=beetoo
ENV DATABASE_PASSWORD=beetoo
ENV GATEWAY_PUBLIC_ENDPOINT=http://172.26.36.26:3000/apiman-gateway
ENV HIBERNATE_DIALECT=org.hibernate.dialect.MySQL5Dialect

RUN rm -f standalone/deployments/apiman-es.war
RUN rm -f standalone/deployments/keycloak-server.war

COPY ./standalone-apiman.xml standalone/configuration/standalone-apiman.xml

RUN sed -i "s/apiman.es.protocol=.*$/apiman.es.protocol=http/g" standalone/configuration/apiman.properties
RUN sed -i "s/apiman.es.host=.*$/apiman.es.host=172.26.33.6/g" standalone/configuration/apiman.properties
RUN sed -i "s/apiman.es.port=.*$/apiman.es.port=9200/g" standalone/configuration/apiman.properties
RUN sed -i "s/^apiman-manager/#apiman-manager/g" standalone/configuration/apiman.properties
RUN echo "" >> standalone/configuration/apiman.properties
RUN echo "# The public endpoint for accessing the API Gateway" standalone/configuration/apiman.properties
RUN echo "apiman-gateway.public-endpoint=$GATEWAY_PUBLIC_ENDPOINT" >> wildfly-11.0.0.Final/standalone/configuration/apiman.properties

RUN cp apiman/sample-configs/apiman-ds_mysql.xml standalone/deployments/apiman-ds.xml
RUN sed -i "s/MYSQLSERVER/$DATABASE_HOST/g" standalone/deployments/apiman-ds.xml
RUN sed -i "s/3306/$DATABASE_PORT/g" standalone/deployments/apiman-ds.xml

RUN sed -i "s/^apiman.hibernate.dialect=.*$/apiman.hibernate.dialect=$HIBERNATE_DIALECT/g" standalone/configuration/apiman.properties
RUN sed -i "s/DBUSER/$DATABASE_USER/g" standalone/deployments/apiman-ds.xml
RUN sed -i "s/DBPASS/$DATABASE_PASSWORD/g" standalone/deployments/apiman-ds.xml

ENTRYPOINT ["/opt/jboss/wildfly/bin/standalone.sh", "-b", "0.0.0.0",  "-bmanagement",  "0.0.0.0", "-c", "standalone-apiman.xml"]
`

As you can see i extend the apiman/on-wildfly11 image which when launch in standlone mode is working properly.

This is the content of my standalone-apiman.xml file

This is the only section i change in the standalone-apim.xml file

`<subsystem xmlns="urn:jboss:domain:keycloak:1.1">
          <realm name="apiman">
            <realm-public-key>MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCrVrCuTtArbgaZzL1hvh0xtL5mc7o0NqPVnYXkLvgcwiC3BjLGw1tGEGoJaXDuSaRllobm53JBhjx33UNv+5z/UMG4kytBWxheNVKnL6GgqlNabMaFfPLPCF8kAgKnsi79NMo+n6KnSY8YeUmec/p2vjO2NjsSAVcWEQMVhJ31LwIDAQAB</realm-public-key>
            <auth-server-url>http://keycloak.orange.cm/auth</auth-server-url>
            <ssl-required>none</ssl-required>
            <enable-cors>false</enable-cors>
            <principal-attribute>preferred_username</principal-attribute>
          </realm>
          <secure-deployment name="apiman.war">
            <realm>apiman</realm>
            <resource>apiman</resource>
            <credential name="secret">5af5458f-0a96-4251-8f92-08ebcc3a8aa2</credential>
            <disable-trust-manager>true</disable-trust-manager>
            <bearer-only>true</bearer-only>
            <enable-basic-auth>true</enable-basic-auth>
          </secure-deployment>
          <secure-deployment name="apimanui.war">
            <realm>apiman</realm>
            <resource>apimanui</resource>
            <credential name="secret">8d4d27c7-e70a-41db-acd7-e8f2df31fa90</credential>
            <disable-trust-manager>true</disable-trust-manager>
            
          </secure-deployment>
          <secure-deployment name="apiman-gateway-api.war">
            <realm>apiman</realm>
            <resource>apiman-gateway-api</resource>
            <credential name="secret">217b725d-7790-47a7-a3fc-5cf31f92a8db</credential>
            <disable-trust-manager>true</disable-trust-manager>
            <bearer-only>true</bearer-only>
            <enable-basic-auth>true</enable-basic-auth>
          </secure-deployment>
</subsystem>`

On i startup de container and i browse to http://172.26.36.26:3000/apimanui/ the login page successfully show up but then i this error message from the wilfdly

15:42:32,794 ERROR [io.undertow.request] (default task-10) UT005023: Exception handling request to /apimanui/apiman/config.js: javax.servlet.ServletException: java.lang.RuntimeException: Invalid API authentication type: null
        at io.apiman.manager.ui.server.servlets.ConfigurationServlet.doGet(ConfigurationServlet.java:155)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        at io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:85)
        at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62)
        at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)
        at org.wildfly.extension.undertow.security.SecurityContextAssociationHandler.handleRequest(SecurityContextAssociationHandler.java:78)
        at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
        at org.keycloak.adapters.undertow.UndertowAuthenticatedActionsHandler.handleRequest(UndertowAuthenticatedActionsHandler.java:66)
        at io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:131)
        at io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57)
        at io.undertow.server.handlers.DisableCacheHandler.handleRequest(DisableCacheHandler.java:33)
        at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
        at io.undertow.security.handlers.AuthenticationConstraintHandler.handleRequest(AuthenticationConstraintHandler.java:53)
        at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46)
        at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64)
        at io.undertow.servlet.handlers.security.ServletSecurityConstraintHandler.handleRequest(ServletSecurityConstraintHandler.java:59)
        at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60)
        at io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77)
        at io.undertow.security.handlers.NotificationReceiverHandler.handleRequest(NotificationReceiverHandler.java:50)
        at io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43)
        at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
        at org.wildfly.extension.undertow.security.jacc.JACCContextIdHandler.handleRequest(JACCContextIdHandler.java:61)
        at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
        at org.wildfly.extension.undertow.deployment.GlobalRequestControllerHandler.handleRequest(GlobalRequestControllerHandler.java:68)
        at org.keycloak.adapters.undertow.ServletPreAuthActionsHandler.handleRequest(ServletPreAuthActionsHandler.java:69)
        at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
        at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:292)
        at io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:81)
        at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:138)
        at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:135)
        at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48)
        at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
        at org.wildfly.extension.undertow.security.SecurityContextThreadSetupAction.lambda$create$0(SecurityContextThreadSetupAction.java:105)
        at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1508)
        at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1508)
        at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1508)
        at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1508)
        at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:272)
        at io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:81)
        at io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:104)
        at io.undertow.server.Connectors.executeRootHandler(Connectors.java:326)
        at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:812)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

And in the browser console i get the following error

![apiman-error](https://user-images.githubusercontent.com/11424992/57972114-3e5b5280-798e-11e9-9a3d-c3ef8ca75d6e.PNG)

**Comment by ndziePatrickJoel** [comment]
The problem was due to this line in the docker file 
RUN sed -i "s/^apiman-manager/#apiman-manager/g" standalone/configuration/apiman.properties

After removing it everything started to work. Thank for this amazing product, i'm hurry to start contributing to it.
