### ISSUE TITLE
Can't save huge swagger api definition using ES storage

### ISSUE THREAD

**Issue by owsega** [apiman/apiman#736]
I'm using elasticsearch for my storage instead of the default RDBMS and everything worked fine. 

When I tried to save a new API definition for an API I created I noticed it doesn't save the definition. It does not show any error on the UI. I only notice the new definition did not reflect after refreshing the page. My new API definition is a bit large (160kb) which is greater than the 32kb size limit on elasticsearch keyword fields.

How can I change the API definition field to accept large JSON or YAML strings?

**Comment by volkflo** [comment]
We encountered the same problem a few days ago.
The short solution is to create a new data mapping, like explained here (https://stackoverflow.com/questions/48290970/changing-field-type-of-an-index-to-new-index-in-elasticsearch)

But for the long term we have to find a better solution because elasitcseach 6+ is dropping support for mappings (https://www.elastic.co/guide/en/elasticsearch/reference/current/removal-of-types.html#removal-of-types).

**Comment by owsega** [comment]
After reindexing, I keep getting StorageException errors all over the app. I can't do anything on the `System Administration` page and on several other pages as well.

`io.apiman.manager.api.core.exceptions.StorageException: java.lang.NullPointerException`

```io.apiman.manager.api.rest.contract.exceptions.SystemErrorException: io.apiman.manager.api.core.exceptions.StorageException: java.lang.NullPointerException
	at io.apiman.manager.api.rest.impl.GatewayResourceImpl.list(GatewayResourceImpl.java:117)
	at io.apiman.manager.api.rest.impl.GatewayResourceImpl$Proxy$_$$_WeldClientProxy.list(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:140)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:295)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:249)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:236)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:406)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:213)
	at org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.service(ServletContainerDispatcher.java:228)
	at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:56)
	at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:51)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:85)
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:129)
	at io.apiman.common.servlet.RootResourceFilter.doFilter(RootResourceFilter.java:59)
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
	at io.apiman.manager.api.war.TransactionWatchdogFilter.doFilter(TransactionWatchdogFilter.java:57)
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
	at io.apiman.manager.api.security.impl.DefaultSecurityContextFilter.doFilter(DefaultSecurityContextFilter.java:56)
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
	at io.apiman.common.servlet.DisableCachingFilter.doFilter(DisableCachingFilter.java:52)
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
	at io.apiman.common.servlet.ApimanCorsFilter.doFilter(ApimanCorsFilter.java:71)
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
	at io.apiman.common.servlet.LocaleFilter.doFilter(LocaleFilter.java:61)
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
	at io.undertow.servlet.handlers.FilterHandler.handleRequest(FilterHandler.java:84)
	at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62)
	at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)
	at org.wildfly.extension.undertow.security.SecurityContextAssociationHandler.handleRequest(SecurityContextAssociationHandler.java:78)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at org.keycloak.adapters.undertow.UndertowAuthenticatedActionsHandler.handleRequest(UndertowAuthenticatedActionsHandler.java:66)
	at io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:131)
	at io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57)
	at io.undertow.server.handlers.DisableCacheHandler.handleRequest(DisableCacheHandler.java:33)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.security.handlers.AuthenticationConstraintHandler.handleRequest(AuthenticationConstraintHandler.java:53)
	at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46)
	at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64)
	at io.undertow.servlet.handlers.security.ServletSecurityConstraintHandler.handleRequest(ServletSecurityConstraintHandler.java:59)
	at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60)
	at io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77)
	at io.undertow.security.handlers.NotificationReceiverHandler.handleRequest(NotificationReceiverHandler.java:50)
	at io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at org.wildfly.extension.undertow.security.jacc.JACCContextIdHandler.handleRequest(JACCContextIdHandler.java:61)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at org.wildfly.extension.undertow.deployment.GlobalRequestControllerHandler.handleRequest(GlobalRequestControllerHandler.java:68)
	at org.keycloak.adapters.undertow.ServletPreAuthActionsHandler.handleRequest(ServletPreAuthActionsHandler.java:69)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:292)
	at io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:81)
	at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:138)
	at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:135)
	at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48)
	at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
	at org.wildfly.extension.undertow.security.SecurityContextThreadSetupAction.lambda$create$0(SecurityContextThreadSetupAction.java:105)
	at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1508)
	at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1508)
	at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1508)
	at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1508)
	at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1508)
	at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:272)
	at io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:81)
	at io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:104)
	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:326)
	at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:812)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: io.apiman.manager.api.core.exceptions.StorageException: java.lang.NullPointerException
	at io.apiman.manager.api.es.EsStorage.listEntities(EsStorage.java:2050)
	at io.apiman.manager.api.es.EsStorage.listGateways(EsStorage.java:1213)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.weld.bean.proxy.AbstractBeanInstance.invoke(AbstractBeanInstance.java:38)
	at org.jboss.weld.bean.proxy.ProxyMethodHandler.invoke(ProxyMethodHandler.java:100)
	at io.apiman.manager.api.core.IStorageQuery$816713463$Proxy$_$$_WeldClientProxy.listGateways(Unknown Source)
	at io.apiman.manager.api.rest.impl.GatewayResourceImpl.list(GatewayResourceImpl.java:115)
	... 79 more
Caused by: java.lang.NullPointerException
	at io.searchbox.core.SearchResult.getHits(SearchResult.java:85)
	at io.searchbox.core.SearchResult.getHits(SearchResult.java:73)
	at io.searchbox.core.SearchResult.getHits(SearchResult.java:65)
	at io.searchbox.core.SearchResult.getHits(SearchResult.java:61)
	at io.apiman.manager.api.es.EsStorage.listEntities(EsStorage.java:2047)
	... 88 more```

**Comment by owsega** [comment]
Never mind, the problem stopped when I redeployed the wars (apiman-gateway.war apiman.war apimanui.war)

**Comment by volkflo** [comment]
Great to hear, did you encountered further problems with this? 
I tested this only with a clean elasticsearch installation without existing data.

**Comment by owsega** [comment]
Mine was "almost" fresh too. Only the admin user's login data was in the elasticsearch when I did the reindexing. 

The current problem is that I can't see the API definition anywhere. It gets saved correctly. I can see it in the page where the API is being edited, but not in the page where the API is to be viewed. 

![view-api-ordinary_user](https://user-images.githubusercontent.com/2920281/58808662-5b408880-8612-11e9-8509-ae8afb1022dd.png)
![edit-api-admin](https://user-images.githubusercontent.com/2920281/58808663-5bd91f00-8612-11e9-96ae-8335ca888531.png)
![view-api-admin](https://user-images.githubusercontent.com/2920281/58808664-5bd91f00-8612-11e9-9b84-13820bac37d8.png)

**Comment by volkflo** [comment]
For me the button appears and I can also view the definition. That is a bit strange.
![image](https://user-images.githubusercontent.com/13332383/58882309-3b759700-86dc-11e9-9a0a-60f44d13ed28.png)

**Comment by EricWittmann** [comment]
And I guess there are no errors in the javascript/browser console?

**Comment by owsega** [comment]
Nope. There are no errors in my browser console

**Comment by owsega** [comment]
I just discovered the fact that I can't see the "View API Definition" link is a different issue entirely. I have created a new issue for that [https://github.com/apiman/apiman/issues/738](here)

I had to start a fresh installation to notice, even when I use a small yaml file (e.g. https://github.com/OAI/OpenAPI-Specification/blob/master/examples/v2.0/yaml/petstore.yaml) , the link doesn't show . However, it shows once I switch to a json definition (e.g. https://github.com/OAI/OpenAPI-Specification/blob/master/examples/v2.0/json/petstore.json)

**Comment by owsega** [comment]
@volkflo It works with a large JSON definition. Thanks!
I guess I should still leave the issue open till a fix is built.

**Comment by EricWittmann** [comment]
Ah yes - it's very likely that only JSON is supported.

**Comment by volkflo** [comment]
@EricWittmann  The main problem here is that the field mapping is created with the field type "keyword" but keyword allows only documents up to 32 KB and so we get a problem with bigger swagger files.

I think I found a "simple" solution which will migrate existing indicies and reindex them to a new index with a new mapping. If everything works as I hope, I will provide a PR.
