### ISSUE TITLE
Errors while running the complete tests (system properties)

### ISSUE THREAD

**Issue by volkflo** [apiman/apiman#744]
I was trying to run the complete test suite locally (like the tests are executed on travis) but I encountered some questions and problems. 

1. If I run `mvn clean test -Dapiman.gateway-test.config=vertx3-es` I always getting errors that the gateway could not connect to elasticsearch.
```java
Caused by: io.searchbox.client.config.exception.CouldNotConnectException: Could not connect to http://localhost:19250
        at io.searchbox.client.http.JestHttpClient.execute(JestHttpClient.java:70)
        at io.searchbox.client.http.JestHttpClient.execute(JestHttpClient.java:60)
        at io.apiman.gateway.engine.es.ESRegistry.validateContract(ESRegistry.java:167)
        ... 81 more
Caused by: org.apache.http.conn.HttpHostConnectException: Connect to localhost:19250 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Connection refused: connect
```
After a quick look I am not sure how elasticsearch is started in this test, I didn't find the place where a startup is performed.

2. The action `mvn clean test -Dapiman-test.type=es -Dapiman.gateway-test.config=servlet-es` is always executed two times. Is there a reason for it?
![image](https://user-images.githubusercontent.com/13332383/61288321-26098780-a7c7-11e9-83d8-e827eb763826.png)

3. On travis the build stage is executed before the test runs. Are some build artifacts needed for the whole test suite?

Maybe someone can help or point me into the right direction :)

P.S. @bekihm and I fixed the test that failed sometimes with a correlation failure. We will suggest a PR after we get our local test environment working correctly

**Comment by msavy** [comment]
Travis starts es in the background for that test as I recall it.

In other cases we use embedded elastic.

I think changes in ES behaviour cause non-determinism in ordering of
returned payloads that the test framework can't deal with very well
(especially in nested complex cases).

I'll kick it again when I get back to the office and it'll probably pass

**Comment by volkflo** [comment]
> I think changes in ES behaviour cause non-determinism in ordering of
returned payloads that the test framework can't deal with very well
(especially in nested complex cases).

Yes, we did a lot of debugging to find this. The most problem part is the Migration Test (Export/Import). We decided to always sort the expected json and the actual json alphabetically which fixes the problem for us. Maybe not in all cases.

> Travis starts es in the background for that test as I recall it.

Is this done via `travis.yml` or is this done somewhere else?

**Comment by volkflo** [comment]
The mentioned pull request is https://github.com/apiman/apiman/pull/745

**Comment by msavy** [comment]
Yes, before I left RHT I was thinking of a fool-proof solution for this. It's actually non-trivial for the framework design that we have -- as testing semantic equivalence of those nested payloads is trickier than it first appears intuitively. 

The solution you mention is likely a fine interim solution, and I'll try to give it some more thought later.

**Comment by msavy** [comment]
> Is this done via `travis.yml` or is this done somewhere else?

In most cases, travis.yml yes (services section)

In some cases we use EmbeddedElastic (https://github.com/apiman/apiman/blob/master/common/es/src/main/java/io/apiman/common/es/util/ApimanEmbeddedElastic.java)

This history of this is that older versions of Apiman Servlet editions used an embedded version of Elasticsearch for trials -- we included that in the tests for convenience also. Vert.x couldn't do this without causing problems, so we just expected a standalone ES instance for the Vert.x Gateway.

Fast forwards a few years, and ES dropped support for embedding ES within the same JVM as another application. To avoid major disruption, I used the EmebeddedElastic project, which spins up ES in a separate VM and controls it remotely. 

I wrote a wrapper (linked above) to prevent some issues if the server is hard/-9 killed (e.g. by hitting 'stop' in Eclipse; finally{} blocks don't even get called sometimes, this would leave ES running in the background and subsequent test runs would fail because of the ports being bound already, or unexpected data, etc.).

Hope that gives a bit of context as to why there are two ways of doing things!

**Comment by EricWittmann** [comment]
I also wonder why **servlet-es** is being tested twice.  Looking at the travis config file I don't see why that should be happening.  A bug in travis or something I don't understand about our config?  Any idea @msavy ?

You can see the problem here:

https://travis-ci.org/apiman/apiman/builds/560109988

There are 6 entries in "test" but only 5 values for `ACTION` defined in the travis config:

https://github.com/apiman/apiman/blob/master/.travis.yml#L21-L25

**Comment by EricWittmann** [comment]
To answer @volkflo question (3) - I don't believe there is a requirement to build before testing.  I think the travis build does this so that it only builds once but then tests 5 different config combinations.  So it doesn't need to do the build step for each of those.

**Comment by volkflo** [comment]
@msavy and @EricWittmann Thanks a lot for the detailed answers. 

If have still two questions, maybe you can also help us with this.
1. We are running the tests on jenkins with:
`mvn clean test -pl !gateway/engine/redis -Dapiman-test.type=es -Dapiman.gateway-test.config=servlet-es` 

But they sometimes failing with this error (not the correlation error). Do you have any idea what is causing this?
```java
INFO  [main]: #fetch(GET localhost:6060 /api/organizations/GatewayApiTest/apis/echo/versions): [200 OK] in 11ms
INFO  [main]:     >> -----------------------------------------------------------
INFO  [main]:     >> Starting Test [api-testPlan.xml / List Clients]
INFO  [main]:     >> -----------------------------------------------------------
INFO  [main]:     >> Sending HTTP request to: http://localhost:6060/api/organizations/GatewayApiTest/clients
INFO  [main]: #fetch(GET localhost:6060 /api/organizations/GatewayApiTest/clients): [200 OK] in 11ms
--- START FAILED JSON PAYLOAD ---
[]
--- END FAILED JSON PAYLOAD ---
INFO  [main]:     >> [ERROR] []: Expected 1 values but got 0
INFO  [main]:     >> -----------------------------------------------------------
INFO  [main]:     >> Starting Test [api-testPlan.xml / List Client Versions]
INFO  [main]:     >> -----------------------------------------------------------
INFO  [main]:     >> Sending HTTP request to: http://localhost:6060/api/organizations/GatewayApiTest/clients/test-client/versions
INFO  [main]: #fetch(GET localhost:6060 /api/organizations/GatewayApiTest/clients/test-client/versions): [200 OK] in 10ms
--- START FAILED JSON PAYLOAD ---
[]
--- END FAILED JSON PAYLOAD ---
INFO  [main]:     >> [ERROR] []: Expected 1 values but got 0
INFO  [main]: Stopped ServerConnector@54361a9{HTTP/1.1,[http/1.1]}{0.0.0.0:6060}
INFO  [main]: node0 Stopped scavenging
INFO  [main]: Stopped o.e.j.s.ServletContextHandler@7fe7c640{/,null,UNAVAILABLE}
INFO  [main]: Stopped ServerConnector@68ad99fe{HTTP/1.1,[http/1.1]}{0.0.0.0:7654}
INFO  [main]: node0 Stopped scavenging
INFO  [main]: Stopped o.e.j.s.ServletContextHandler@7e5d9a50{/,null,UNAVAILABLE}
INFO  [EmbeddedElsHandler]: [2019-07-18T12:22:41,588][INFO ][o.e.c.m.MetaDataDeleteIndexService] [XjkMQ7j] [apiman_gateway/0cjjuXqvTTOroBdsK0aR6A] deleting index
======== STOPPING ES ========
INFO  [main]: Stopping elasticsearch server...
INFO  [main]: Elasticsearch exited with RC 143
INFO  [main]: Removing installation directory...
INFO  [main]: Finishing...
INFO  [main]:     >> 
INFO  [main]:     >> -------------------------------------------------------------------------------
INFO  [main]:     >> REST Test complete
INFO  [main]:     >> -------------------------------------------------------------------------------
INFO  [main]:     >> 
Tests run: 18, Failures: 2, Errors: 0, Skipped: 0, Time elapsed: 14.993 sec <<< FAILURE! - in io.apiman.gateway.test.GatewayApiTest
List Clients(io.apiman.gateway.test.GatewayApiTest)  Time elapsed: 0.022 sec  <<< FAILURE!
java.lang.AssertionError: []: Expected 1 values but got 0
	at org.skyscreamer.jsonassert.JSONAssert.assertEquals(JSONAssert.java:482)
	at org.skyscreamer.jsonassert.JSONAssert.assertEquals(JSONAssert.java:464)
	at io.apiman.test.common.json.JsonCompare.assertJson(JsonCompare.java:186)
	at io.apiman.test.common.util.TestPlanRunner.assertJsonPayload(TestPlanRunner.java:303)
	at io.apiman.test.common.util.TestPlanRunner.assertResponse(TestPlanRunner.java:255)
	at io.apiman.test.common.util.TestPlanRunner.runTest(TestPlanRunner.java:178)
	at io.apiman.gateway.test.junit.GatewayRestTester$1.evaluate(GatewayRestTester.java:258)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at io.apiman.gateway.test.junit.GatewayRestTester.runChild(GatewayRestTester.java:230)
	at io.apiman.gateway.test.junit.GatewayRestTester.runChild(GatewayRestTester.java:54)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at io.apiman.gateway.test.junit.GatewayRestTester.run(GatewayRestTester.java:208)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:264)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:124)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)

List Client Versions(io.apiman.gateway.test.GatewayApiTest)  Time elapsed: 0.011 sec  <<< FAILURE!
java.lang.AssertionError: []: Expected 1 values but got 0
	at org.skyscreamer.jsonassert.JSONAssert.assertEquals(JSONAssert.java:482)
	at org.skyscreamer.jsonassert.JSONAssert.assertEquals(JSONAssert.java:464)
	at io.apiman.test.common.json.JsonCompare.assertJson(JsonCompare.java:186)
	at io.apiman.test.common.util.TestPlanRunner.assertJsonPayload(TestPlanRunner.java:303)
	at io.apiman.test.common.util.TestPlanRunner.assertResponse(TestPlanRunner.java:255)
	at io.apiman.test.common.util.TestPlanRunner.runTest(TestPlanRunner.java:178)
	at io.apiman.gateway.test.junit.GatewayRestTester$1.evaluate(GatewayRestTester.java:258)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at io.apiman.gateway.test.junit.GatewayRestTester.runChild(GatewayRestTester.java:230)
	at io.apiman.gateway.test.junit.GatewayRestTester.runChild(GatewayRestTester.java:54)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at io.apiman.gateway.test.junit.GatewayRestTester.run(GatewayRestTester.java:208)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:264)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:124)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)

Running io.apiman.gateway.test.SimpleEchoPublicTest
````

2. The vert.x es tests `mvn clean test -Dapiman.gateway-test.config=vertx3-es`
> Vert.x couldn't do this without causing problems, so we just expected a standalone ES instance for the Vert.x Gateway.

So travis is starting an additional instance? I can't see something in the logs about that. It always connects to localhost:19250 (embedded es)

And If I run this locally then the `io.apiman.gateway.test` crahes with a `CouldNotConnectException` (same as mentioned as I opened the issue).

In addition I provided a standalone elasticsearch instance with docker running on 19250 the previous tests that using embeeded es will fail because embeeded es can not start through a already existing port binding of 19250.

Maybe someone has an idea what I am doing wrong?

**Comment by EricWittmann** [comment]
I don't know the answer to (2) regarding how ES is starting up.  I'm also having trouble figuring out how that's working in travis.

As for (1) - I can provide a bit of insight.  The failing test is backed by the following test plan:

https://github.com/apiman/apiman/blob/master/gateway/test/src/test/resources/test-plans/api/api-testPlan.xml

Every test plan of this nature is a number of REST API calls made by the test to a running Apiman server.  Each step in the test plan is represented by a *.resttest file.  Each of these files contains the **HTTP Request** that should be sent to the server followed by the **expected HTTP response** that should be used for assert purposes.  In this case the **List Clients** and **List Client Versions** tests are failing (the last 2 in this test plan).  They are failing because no clients are found!  

My best guess is that the nature of elasticsearch's eventual consistency for searching may be the culprit here.  At least I recall ES working that way.  This test tries to remove and then re-add the client here:

https://github.com/apiman/apiman/blob/master/gateway/test/src/test/resources/test-plans/api/api-testPlan.xml#L21-L22

It then expects the client (and client version) to exist here:

https://github.com/apiman/apiman/blob/master/gateway/test/src/test/resources/test-plans/api/api-testPlan.xml#L32-L33

Perhaps a delay is needed to ensure that ES indexing has been completed.

**Comment by volkflo** [comment]
@EricWittmann Seems that was the problem. I added a delay of 5 seconds between the lines. And know our jenkins doesn't complain anymore. Thanks a lot!

Should I create a PR for this? We encountered that some of the logging (all of the log I posted above with port 6060 )on travis is missing, because of missing log4j.xmls. Was this on purpose to reduce logging on travis? 

If not I would also include them in a PR.

**Comment by msavy** [comment]
Some kind of bounded polling loop might be an appropriate solution too

**Comment by EricWittmann** [comment]
I'm sure a missing `log4j.xml` is an oversight and not intentional.  If you could create a PR that would be great - with both things.  I **think** you can set the delay to 2s instead of 5 - the last time I used ES I believe 1s was the amount of time between ES indexing, although that was a long time ago.  Still, I think 2s is appropriate and we can increase the time later if needed.

**Comment by EricWittmann** [comment]
And @msavy - yes a better approach would probably be a bounded polling loop.  That's harder to implement generically, obviously. :)
