### ISSUE TITLE
Log4J update has broken vert.x gateway

### ISSUE THREAD

**Issue by volkflo** [apiman/apiman#778]
It seems that the log4j update to 2.12.0 has broken the vert.x gateway

```java
Exception in thread "main" java.lang.NoSuchMethodError: com.lmax.disruptor.dsl.Disruptor.<init>(Lcom/lmax/disruptor/EventFactory;ILjava/util/concurrent/ThreadFactory;Lcom/lmax/disruptor/dsl/ProducerType;Lcom/lmax/disruptor/WaitStrategy;)V
gateway          |      at org.apache.logging.log4j.core.async.AsyncLoggerDisruptor.start(AsyncLoggerDisruptor.java:102)
gateway          |      at org.apache.logging.log4j.core.async.AsyncLoggerContext.start(AsyncLoggerContext.java:75)
gateway          |      at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:243)
gateway          |      at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:45)
gateway          |      at org.apache.logging.log4j.LogManager.getContext(LogManager.java:174)
gateway          |      at org.apache.logging.log4j.LogManager.getLogger(LogManager.java:661)
gateway          |      at io.apiman.gateway.platforms.vertx3.logging.ApimanLog4j2LogDelegate.<init>(ApimanLog4j2LogDelegate.java:21)
gateway          |      at io.apiman.gateway.platforms.vertx3.logging.ApimanLog4j2LogDelegateFactory.createDelegate(ApimanLog4j2LogDelegateFactory.java:9)
gateway          |      at io.vertx.core.logging.LoggerFactory.getLogger(LoggerFactory.java:74)
gateway          |      at io.vertx.core.logging.LoggerFactory.getLogger(LoggerFactory.java:67)
gateway          |      at io.vertx.core.impl.launcher.commands.ClasspathHandler.<init>(ClasspathHandler.java:45)
gateway          |      at io.vertx.core.impl.launcher.commands.BareCommand.<init>(BareCommand.java:49)
gateway          |      at io.vertx.core.impl.launcher.commands.RunCommand.<init>(RunCommand.java:39)
gateway          |      at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
gateway          |      at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
gateway          |      at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
gateway          |      at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
gateway          |      at java.lang.Class.newInstance(Class.java:442)
gateway          |      at io.vertx.core.cli.impl.ReflectionUtils.newInstance(ReflectionUtils.java:32)
gateway          |      at io.vertx.core.spi.launcher.DefaultCommandFactory.create(DefaultCommandFactory.java:44)
gateway          |      at io.vertx.core.impl.launcher.VertxCommandLauncher.getNewCommandInstance(VertxCommandLauncher.java:158)
gateway          |      at io.vertx.core.impl.launcher.VertxCommandLauncher.execute(VertxCommandLauncher.java:213)
gateway          |      at io.vertx.core.impl.launcher.VertxCommandLauncher.dispatch(VertxCommandLauncher.java:380)
gateway          |      at io.vertx.core.impl.launcher.VertxCommandLauncher.dispatch(VertxCommandLauncher.java:324)
gateway          |      at io.apiman.gateway.platforms.vertx3.ApimanLauncher.main(ApimanLauncher.java:48)
```

**Comment by msavy** [comment]
Looks like the lmax disruptor version is not aligned properly

**Comment by msavy** [comment]
I'll push a branch/PR for you to test
