### ISSUE TITLE
Issue when service becomes slow

### ISSUE THREAD

**Issue by MinniArora** [apiman/apiman#852]
We have defined a read timeout of 1sec in apiman.

Now, whenever a service becomes slow due to issues on the backend, we get timeout errors which is expected: The error message is: The timeout period of 1000ms has been exceeded while executing GET .... for host ...

But even after the service recovers, we keep getting timeout errors continuously and now the requests do not even reach the service. Seems the requests are timing out from some internal queue. It's only after a restart that the issue gets resolved.

Stacktrace:
        at io.apiman.gateway.platforms.vertx3.connector.HttpConnector$ExceptionHandler.handle(HttpConnector.java:327)
        at io.apiman.gateway.platforms.vertx3.connector.HttpConnector$ExceptionHandler.handle(HttpConnector.java:324)
        at io.vertx.core.http.impl.HttpClientRequestBase.handleException(HttpClientRequestBase.java:136)
        at io.vertx.core.http.impl.HttpClientRequestImpl.handleException(HttpClientRequestImpl.java:51)
        at io.vertx.core.http.impl.HttpClientRequestBase.timeout(HttpClientRequestBase.java:183)
        at io.vertx.core.http.impl.HttpClientRequestBase.handleTimeout(HttpClientRequestBase.java:168)
        at io.vertx.core.http.impl.HttpClientRequestBase.lambda$setTimeout$0(HttpClientRequestBase.java:126)
        at io.vertx.core.impl.VertxImpl$InternalTimerHandler.handle(VertxImpl.java:784)
        at io.vertx.core.impl.VertxImpl$InternalTimerHandler.handle(VertxImpl.java:755)
        at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:324)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:445)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
        at java.lang.Thread.run(Thread.java:748)

**Comment by msavy** [comment]
Can you have a look at netstat/lsof or similar to see what's going on? 

I wonder whether the threads are blocked in some way because of the corresponding TCP connection(s) still open/half open or something, and the rebooted remote service is not terminating those connections - that would be one scenario where it may leave them 'stuck'.

**Comment by volkflo** [comment]
Yes, debugging is possible with `./apiman-gateway.sh --debug` on port 8787.
Also, you could try to set the log level to debug if you add the gateway option `-Dapiman.gateway-logLevel=debug`

**Comment by MinniArora** [comment]
Missed to mention that the issue is seen only when a continuous stream of requests is sent to a slow service which is normal on production. Works fine for a single request.

**Comment by MinniArora** [comment]
Hi. Any clue here? You can try benchmark apiman using a sample service with synthetic delay and you will see the issue.

**Comment by bekihm** [comment]
@MinniArora Do you have a setup for this (jmeter or something)?

**Comment by MinniArora** [comment]
Had used [wrk](https://github.com/wg/wrk). Although jmeter can be used too.

**Comment by msavy** [comment]
@MinniArora, are you able to do the debug steps mentioned earlier in the thread?

It may be that there are tonnes of half-open/open connections just sitting there waiting for I/O or in various states of the connection process (handshakes, etc). That may result in thread exhaustion until timeouts eventually kick in. By restarting the server you are forcibly terminating all of those connections.

Or it may be something else.

If you can verify that, then it will be helpful to give us a starting point; have a look at the state of the threads in the system, and what they/IO appears to be blocked on.

**Comment by msavy** [comment]
BTW you should consider using wrk2 or gatling to avoid [coordinated omission](https://www.youtube.com/watch?v=lJ8ydIuPFeU) problems when benchmarking

**Comment by cen1** [comment]
When backends are slow it could indeed fill up to the point new connections can no longer be accepted. What settings can be changed to increase this?

**Comment by msavy** [comment]
> When backends are slow it could indeed fill up to the point new connections can no longer be accepted. What settings can be changed to increase this?
> 
> On one of our systems we noticed hundreds of tcp connections open to LDAP and we see a lot of these in the ssl debug log, could this have anything to do with connections being exhausted? It comes from the LDAP policy apparently.
> 
> ```
>  [6731]: javax.net.ssl|WARNING|01 54|qtp1216590855-340 - CET|Logger.java:765|SSLSocket duplex close failed (
>  [6731]: "throwable" : {
>  [6731]: java.net.SocketException: Socket is closed
>  [6731]: at java.net.Socket.shutdownInput(Socket.java:1539)
>  [6731]: at sun.security.ssl.BaseSSLSocketImpl.shutdownInput(BaseSSLSocketImpl.java:218)
>  [6731]: at sun.security.ssl.SSLSocketImpl.shutdownInput(SSLSocketImpl.java:643)
>  [6731]: at sun.security.ssl.SSLSocketImpl.bruteForceCloseInput(SSLSocketImpl.java:598)
>  [6731]: at sun.security.ssl.SSLSocketImpl.duplexCloseOutput(SSLSocketImpl.java:558)
>  [6731]: at sun.security.ssl.SSLSocketImpl.close(SSLSocketImpl.java:471)
>  [6731]: at com.squareup.okhttp.internal.http.HttpConnection$AbstractSource.endOfInput(ApiRequestExecutorImpl.java:245)
> ...
>  [6731]: at io.apiman.gateway.engine.policy.Chain.handleHead(Chain.java:211)
>  [6731]: at io.apiman.gateway.engine.policy.Chain.doApply(Chain.java:150)
>  [6731]: at io.apiman.gateway.engine.policies.BasicAuthenticationPolicy$1.handle(BasicAuthenticationPolicy.java:142)
>  [6731]: at io.apiman.gateway.engine.policies.BasicAuthenticationPolicy$1.handle(BasicAuthenticationPolicy.java:124)
>  [6731]: at io.apiman.gateway.engine.policies.auth.LDAPIdentityValidator$6.handle(LDAPIdentityValidator.java:249)
>  [6731]: at io.apiman.gateway.engine.policies.auth.LDAPIdentityValidator$6.handle(LDAPIdentityValidator.java:229)
>  [6731]: at io.apiman.gateway.engine.impl.DefaultLdapClientConnection.evalBindReturn(DefaultLdapClientConnection.java:66)
>  [6731]: at io.apiman.gateway.engine.impl.DefaultLdapClientConnection.bind(DefaultLdapClientConnection.java:76)
>  [6731]: at io.apiman.gateway.engine.impl.DefaultLdapComponent.bind(DefaultLdapComponent.java:89)
>  [6731]: at io.apiman.gateway.engine.policies.auth.LDAPIdentityValidator.bind(LDAPIdentityValidator.java:155)
>  [6731]: at io.apiman.gateway.engine.policies.auth.LDAPIdentityValidator.handleLdapSearch(LDAPIdentityValidator.java:229)
> ```

Can you open a separate bug report for this, please?
