### ISSUE TITLE
Connection error while starting apiman-es.war

### ISSUE THREAD

**Issue by nishasumesh** [apiman/apiman#857]
I took the code from http://www.apiman.io/latest/download.html, unzipped files and edited apiman.properties 

edited below properties
```
apiman.hibernate.hbm2ddl.auto=update
```

and uncommented below properties
```
#apiman-manager.storage.es.protocol=${apiman.es.protocol}
#apiman-manager.storage.es.host=${apiman.es.host}
#apiman-manager.storage.es.port=${apiman.es.port}
#apiman-manager.storage.es.username=${apiman.es.username}
#apiman-manager.storage.es.password=${apiman.es.password}
#apiman-manager.storage.es.timeout=${apiman.es.timeout}
#apiman-manager.storage.es.initialize=true
```

Edited apiman-ds.xml to add the proper db configurations

http://localhost:19200/?pretty is not working

getting the below error in logs:

```
18:56:39,951 INFO  [org.wildfly.extension.undertow] (ServerService Thread Pool -- 69) WFLYUT0021: Registered web context: /auth
18:56:39,959 ERROR [org.jboss.as.controller.management-operation] (Controller Boot Thread) WFLYCTL0013: Operation ("deploy") failed - address: ([("deployment" => "apiman-es.war")]) - failure description: {
    "WFLYCTL0080: Failed services" => {"jboss.undertow.deployment.default-server.default-host./apiman-es" => "org.jboss.msc.service.StartException in service jboss.undertow.deployment.default-server.default-host./apiman-es: java.lang.ExceptionInInitializerError
    Caused by: java.lang.ExceptionInInitializerError
    Caused by: java.lang.UnsupportedOperationException: Boot class path mechanism is not supported"},
    "WFLYCTL0412: Required services that are not installed:" => ["jboss.undertow.deployment.default-server.default-host./apiman-es"],
    "WFLYCTL0180: Services with missing/unavailable dependencies" => undefined
}
18:56:39,990 INFO  [org.jboss.as.server] (ServerService Thread Pool -- 36) WFLYSRV0010: Deployed "apiman-es.war" (runtime-name : "apiman-es.war")
18:56:39,990 INFO  [org.jboss.as.server] (ServerService Thread Pool -- 36) WFLYSRV0010: Deployed "apiman-ds.xml" (runtime-name : "apiman-ds.xml")
18:56:39,991 INFO  [org.jboss.as.server] (ServerService Thread Pool -- 36) WFLYSRV0010: Deployed "apiman.war" (runtime-name : "apiman.war")
18:56:39,991 INFO  [org.jboss.as.server] (ServerService Thread Pool -- 36) WFLYSRV0010: Deployed "apiman-gateway-api.war" (runtime-name : "apiman-gateway-api.war")
18:56:39,991 INFO  [org.jboss.as.server] (ServerService Thread Pool -- 60) WFLYSRV0010: Deployed "keycloak-server.war" (runtime-name : "keycloak-server.war")
18:56:39,991 INFO  [org.jboss.as.server] (ServerService Thread Pool -- 36) WFLYSRV0010: Deployed "apimanui.war" (runtime-name : "apimanui.war")
18:56:39,991 INFO  [org.jboss.as.server] (ServerService Thread Pool -- 36) WFLYSRV0010: Deployed "apiman-gateway.war" (runtime-name : "apiman-gateway.war")
18:56:39,995 INFO  [org.jboss.as.controller] (Controller Boot Thread) WFLYCTL0183: Service status report
WFLYCTL0186:   Services which failed to start:      service jboss.undertow.deployment.default-server.default-host./apiman-es: org.jboss.msc.service.StartException in service jboss.undertow.deployment.default-server.default-host./apiman-es: java.lang.ExceptionInInitializerError

18:56:40,129 INFO  [org.jboss.as] (Controller Boot Thread) WFLYSRV0060: Http management interface listening on http://127.0.0.1:9990/management
18:56:40,129 INFO  [org.jboss.as] (Controller Boot Thread) WFLYSRV0051: Admin console listening on http://127.0.0.1:9990
18:56:40,130 ERROR [org.jboss.as] (Controller Boot Thread) WFLYSRV0026: WildFly Full 10.1.0.Final (WildFly Core 2.2.0.Final) started (with errors) in 30068ms - Started 990 of 1337 services (2 services failed or missing dependencies, 598 services are lazy, passive or on-demand)
18:56:40,255 INFO  [org.jboss.as.server.deployment] (MSC service thread 1-8) WFLYSRV0028: Stopped deployment apiman-es.war (runtime-name: apiman-es.war) in 48ms
18:56:40,342 WARN  [org.jboss.as.controller] (DeploymentScanner-threads - 1) WFLYCTL0357: Notification of type deployment-undeployed is not described for the resource at the address []
18:56:40,355 INFO  [org.jboss.as.repository] (DeploymentScanner-threads - 1) WFLYDR0002: Content removed from location /Users/nishaks/Softwares/apiman/old_wildfly-10.1.0.Final/standalone/data/content/ef/46f755c41b138836c7b08ede82d64c0a9202cb/content
18:56:40,356 INFO  [org.jboss.as.server] (DeploymentScanner-threads - 1) WFLYSRV0009: Undeployed "apiman-es.war" (runtime-name: "apiman-es.war")
18:56:40,356 INFO  [org.jboss.as.controller] (DeploymentScanner-threads - 1) WFLYCTL0183: Service status report
WFLYCTL0184:    New missing/unsatisfied dependencies:
      service jboss.deployment.unit."apiman-es.war".component."javax.faces.webapp.FacetTag".START (missing) dependents: [service jboss.deployment.unit."apiman-es.war".deploymentCompleteService] 
WFLYCTL0186:   Services which failed to start:      service jboss.undertow.deployment.default-server.default-host./apiman-es

18:57:14,157 INFO  [io.searchbox.client.JestClientFactory] (ESRegistryCacheInvalidator) Using multi thread/connection supporting pooling connection manager
18:57:14,225 INFO  [io.searchbox.client.JestClientFactory] (ESRegistryCacheInvalidator) Using default GSON instance
18:57:14,225 INFO  [io.searchbox.client.JestClientFactory] (ESRegistryCacheInvalidator) Node Discovery disabled...
18:57:14,225 INFO  [io.searchbox.client.JestClientFactory] (ESRegistryCacheInvalidator) Idle connection reaping disabled...
18:57:14,254 ERROR [stderr] (ESRegistryCacheInvalidator) Exception in thread "ESRegistryCacheInvalidator" java.lang.RuntimeException: org.apache.http.conn.HttpHostConnectException: Connect to localhost:19200 [localhost/127.0.0.1] failed: Connection refused
18:57:14,254 ERROR [stderr] (ESRegistryCacheInvalidator) 	at io.apiman.gateway.engine.es.AbstractClientFactory.initializeClient(AbstractClientFactory.java:68)
18:57:14,254 ERROR [stderr] (ESRegistryCacheInvalidator) 	at io.apiman.gateway.engine.es.DefaultESClientFactory.createJestClient(DefaultESClientFactory.java:121)
18:57:14,254 ERROR [stderr] (ESRegistryCacheInvalidator) 	at io.apiman.gateway.engine.es.DefaultESClientFactory.createClient(DefaultESClientFactory.java:68)
18:57:14,255 ERROR [stderr] (ESRegistryCacheInvalidator) 	at io.apiman.gateway.engine.es.AbstractESComponent.createClient(AbstractESComponent.java:61)
18:57:14,255 ERROR [stderr] (ESRegistryCacheInvalidator) 	at io.apiman.gateway.engine.es.AbstractESComponent.getClient(AbstractESComponent.java:51)
18:57:14,255 ERROR [stderr] (ESRegistryCacheInvalidator) 	at io.apiman.gateway.engine.es.PollCachingESRegistry.checkCacheVersion(PollCachingESRegistry.java:204)
18:57:14,255 ERROR [stderr] (ESRegistryCacheInvalidator) 	at io.apiman.gateway.engine.es.PollCachingESRegistry$6.run(PollCachingESRegistry.java:180)
18:57:14,255 ERROR [stderr] (ESRegistryCacheInvalidator) 	at java.base/java.lang.Thread.run(Thread.java:830)
18:57:14,256 ERROR [stderr] (ESRegistryCacheInvalidator) Caused by: org.apache.http.conn.HttpHostConnectException: Connect to localhost:19200 [localhost/127.0.0.1] failed: Connection refused
18:57:14,256 ERROR [stderr] (ESRegistryCacheInvalidator) 	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:151)
18:57:14,256 ERROR [stderr] (ESRegistryCacheInvalidator) 	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:353)
18:57:14,257 ERROR [stderr] (ESRegistryCacheInvalidator) 	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380)
18:57:14,257 ERROR [stderr] (ESRegistryCacheInvalidator) 	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
18:57:14,257 ERROR [stderr] (ESRegistryCacheInvalidator) 	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
18:57:14,258 ERROR [stderr] (ESRegistryCacheInvalidator) 	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
18:57:14,258 ERROR [stderr] (ESRegistryCacheInvalidator) 	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
18:57:14,259 ERROR [stderr] (ESRegistryCacheInvalidator) 	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
18:57:14,259 ERROR [stderr] (ESRegistryCacheInvalidator) 	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
18:57:14,259 ERROR [stderr] (ESRegistryCacheInvalidator) 	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:107)
18:57:14,259 ERROR [stderr] (ESRegistryCacheInvalidator) 	at io.searchbox.client.http.JestHttpClient.execute(JestHttpClient.java:50)
18:57:14,260 ERROR [stderr] (ESRegistryCacheInvalidator) 	at io.apiman.gateway.engine.es.AbstractClientFactory.initializeClient(AbstractClientFactory.java:61)
18:57:14,261 ERROR [stderr] (ESRegistryCacheInvalidator) 	... 7 more
18:57:14,262 ERROR [stderr] (ESRegistryCacheInvalidator) Caused by: java.net.ConnectException: Connection refused
18:57:14,262 ERROR [stderr] (ESRegistryCacheInvalidator) 	at java.base/sun.nio.ch.Net.pollConnect(Native Method)
18:57:14,262 ERROR [stderr] (ESRegistryCacheInvalidator) 	at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:579)
18:57:14,262 ERROR [stderr] (ESRegistryCacheInvalidator) 	at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:549)
18:57:14,263 ERROR [stderr] (ESRegistryCacheInvalidator) 	at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:597)
18:57:14,263 ERROR [stderr] (ESRegistryCacheInvalidator) 	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:339)
18:57:14,263 ERROR [stderr] (ESRegistryCacheInvalidator) 	at java.base/java.net.Socket.connect(Socket.java:585)
18:57:14,263 ERROR [stderr] (ESRegistryCacheInvalidator) 	at org.apache.http.conn.socket.PlainConnectionSocketFactory.connectSocket(PlainConnectionSocketFactory.java:74)
18:57:14,263 ERROR [stderr] (ESRegistryCacheInvalidator) 	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:134)
18:57:14,267 ERROR [stderr] (ESRegistryCacheInvalidator) 	... 18 more
18:57:14,652 INFO  [io.searchbox.client.JestClientFactory] (ESRegistryCacheInvalidator) Using multi thread/connection supporting pooling connection manager
18:57:14,720 INFO  [io.searchbox.client.JestClientFactory] (ESRegistryCacheInvalidator) Using default GSON instance
18:57:14,720 INFO  [io.searchbox.client.JestClientFactory] (ESRegistryCacheInvalidator) Node Discovery disabled...
18:57:14,721 INFO  [io.searchbox.client.JestClientFactory] (ESRegistryCacheInvalidator) Idle connection reaping disabled...
18:57:14,746 ERROR [stderr] (ESRegistryCacheInvalidator) Exception in thread "ESRegistryCacheInvalidator" java.lang.RuntimeException: org.apache.http.conn.HttpHostConnectException: Connect to localhost:19200 [localhost/127.0.0.1] failed: Connection refused
18:57:14,746 ERROR [stderr] (ESRegistryCacheInvalidator) 	at io.apiman.gateway.engine.es.AbstractClientFactory.initializeClient(AbstractClientFactory.java:68)
18:57:14,746 ERROR [stderr] (ESRegistryCacheInvalidator) 	at io.apiman.gateway.engine.es.DefaultESClientFactory.createJestClient(DefaultESClientFactory.java:121)
18:57:14,747 ERROR [stderr] (ESRegistryCacheInvalidator) 	at io.apiman.gateway.engine.es.DefaultESClientFactory.createClient(DefaultESClientFactory.java:68)
18:57:14,747 ERROR [stderr] (ESRegistryCacheInvalidator) 	at io.apiman.gateway.engine.es.AbstractESComponent.createClient(AbstractESComponent.java:61)
18:57:14,747 ERROR [stderr] (ESRegistryCacheInvalidator) 	at io.apiman.gateway.engine.es.AbstractESComponent.getClient(AbstractESComponent.java:51)
18:57:14,747 ERROR [stderr] (ESRegistryCacheInvalidator) 	at io.apiman.gateway.engine.es.PollCachingESRegistry.checkCacheVersion(PollCachingESRegistry.java:204)
18:57:14,747 ERROR [stderr] (ESRegistryCacheInvalidator) 	at io.apiman.gateway.engine.es.PollCachingESRegistry$6.run(PollCachingESRegistry.java:180)
18:57:14,747 ERROR [stderr] (ESRegistryCacheInvalidator) 	at java.base/java.lang.Thread.run(Thread.java:830)
18:57:14,748 ERROR [stderr] (ESRegistryCacheInvalidator) Caused by: org.apache.http.conn.HttpHostConnectException: Connect to localhost:19200 [localhost/127.0.0.1] failed: Connection refused
18:57:14,748 ERROR [stderr] (ESRegistryCacheInvalidator) 	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:151)
18:57:14,748 ERROR [stderr] (ESRegistryCacheInvalidator) 	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:353)
18:57:14,748 ERROR [stderr] (ESRegistryCacheInvalidator) 	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380)
18:57:14,749 ERROR [stderr] (ESRegistryCacheInvalidator) 	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
18:57:14,749 ERROR [stderr] (ESRegistryCacheInvalidator) 	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
18:57:14,749 ERROR [stderr] (ESRegistryCacheInvalidator) 	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
18:57:14,749 ERROR [stderr] (ESRegistryCacheInvalidator) 	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
18:57:14,749 ERROR [stderr] (ESRegistryCacheInvalidator) 	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
18:57:14,750 ERROR [stderr] (ESRegistryCacheInvalidator) 	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
18:57:14,750 ERROR [stderr] (ESRegistryCacheInvalidator) 	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:107)
18:57:14,750 ERROR [stderr] (ESRegistryCacheInvalidator) 	at io.searchbox.client.http.JestHttpClient.execute(JestHttpClient.java:50)
18:57:14,750 ERROR [stderr] (ESRegistryCacheInvalidator) 	at io.apiman.gateway.engine.es.AbstractClientFactory.initializeClient(AbstractClientFactory.java:61)
18:57:14,750 ERROR [stderr] (ESRegistryCacheInvalidator) 	... 7 more
18:57:14,751 ERROR [stderr] (ESRegistryCacheInvalidator) Caused by: java.net.ConnectException: Connection refused
18:57:14,751 ERROR [stderr] (ESRegistryCacheInvalidator) 	at java.base/sun.nio.ch.Net.pollConnect(Native Method)
18:57:14,751 ERROR [stderr] (ESRegistryCacheInvalidator) 	at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:579)
18:57:14,751 ERROR [stderr] (ESRegistryCacheInvalidator) 	at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:549)
18:57:14,751 ERROR [stderr] (ESRegistryCacheInvalidator) 	at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:597)
18:57:14,751 ERROR [stderr] (ESRegistryCacheInvalidator) 	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:339)
18:57:14,751 ERROR [stderr] (ESRegistryCacheInvalidator) 	at java.base/java.net.Socket.connect(Socket.java:585)
18:57:14,752 ERROR [stderr] (ESRegistryCacheInvalidator) 	at org.apache.http.conn.socket.PlainConnectionSocketFactory.connectSocket(PlainConnectionSocketFactory.java:74)
18:57:14,752 ERROR [stderr] (ESRegistryCacheInvalidator) 	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:134)
18:57:14,752 ERROR [stderr] (ESRegistryCacheInvalidator) 	... 18 more
```

Please help me , I am new to this and is stuck since last one week.

**Comment by EricWittmann** [comment]
Can you post the following info:

* Either your full `apiman.properties` file or a diff between yours and the default
* Your apiman-ds.xml file (with any secrets redacted)
* The full Wildfly startup log

The exception you're seeing indicates that Elasticsearch isn't starting up.  But the `org.jboss.as.controller.management-operation` error at the top of what you've pasted here is something I've not seen before.

Question: why did you uncomment the section about connecting to an Elasticsearch storage for the manager?  That would only be relevant if you switched the `apiman-manager.storage.type` from `jps` to `es` (indicating you wanted to use Elasticsearch as your storage mechanism **instead of** a database).  Note that Elasticsearch is also used for metrics and gateway storage, which is why it's required even though we're using a database to store manager related stuff.

**Comment by EricWittmann** [comment]
Also I recommend this guide if you want to know more about how everything works together:

https://apiman.gitbooks.io/apiman-production-guide/

**Comment by nishasumesh** [comment]
I tried with and with out editing apiman.properties file. result is the same. PFA apiman.properties and ds.xml files
[files.zip](https://github.com/apiman/apiman/files/4856608/files.zip)

Also tried installation from the link you have provided, I am not able to unzip the file using my mac archiveutility / unarchiver .
tried unzip wildfly-10.0.0.final and got wildfly-10.0.0.final.zip.cpgz

**Comment by EricWittmann** [comment]
I don't think Mac should be an issue.  But I don't have one so I can't confirm that.  I'm downloading the files now and will see what I get.

Your apiman.properties and apiman-ds.xml files look fine to me.  But you didn't include your full wildfly startup log in the zip file you attached.  I'll need that to see if I can figure out what's going on.

When you start up the server, make sure you do it like this:

`./bin/standalone.sh -c standalone-apiman.xml`

**Comment by EricWittmann** [comment]
OK I just tried running the Apiman quickstart (with no modifications to apiman.properties) and everything worked.  Here is my startup log for reference:

[server.log](https://github.com/apiman/apiman/files/4859617/server.log)

**Comment by nishasumesh** [comment]
Please find the attached log file [
[apiman_log.txt](https://github.com/apiman/apiman/files/4864091/apiman_log.txt)
]

**Comment by EricWittmann** [comment]
So when you're running locally (not in docker) the first and most important error is this one:

```
Caused by: java.lang.UnsupportedOperationException: Boot class path mechanism is not supported
```

I suspect this is a java version problem.  The apiman project is a bit older and has not been tested with Java 13.  Can you give Java 11 or Java 8 (I know) a try and see what you get?

The error running docker appears to be a timeout - in that situation is **appears** that the embedded elasticsearch server that we include in the quickstart (to make things easier, ironically) did not start up in a reasonable amount of time.

**Comment by nishasumesh** [comment]
:) it worked with java8. Thanks Eric.

**Comment by nishasumesh** [comment]
Again I am geeting error while startup . It was working since yesterday. Today morning I am getting some DB error. Not sure why.
PFA
[db_error.txt](https://github.com/apiman/apiman/files/4882626/db_error.txt)

**Comment by msavy** [comment]
You are using JDK 11 according to that log, please use JDK 8 .

**Comment by nishasumesh** [comment]
ok i will check, thanks
