### ISSUE TITLE
Logging pattern on every line of stack trace

### ISSUE THREAD

**Issue by gromero-pivops** [apiman/apiman#867]
Hi !

I've installed Apiman 1.5.1.Final + Wildfly 17.
Wildfly logs all pattern on each stack trace line. This only happens when Apiman executes something like e.printStackTrace(), i.e. when it outputs in _stderr_.

Example when I was testing losing connection to database : 
2020-07-12 05:58:43,201 | ERROR | stderr | JdbcRegistryCacheInvalidator | java.sql.SQLException: Communications link failure
2020-07-12 05:58:43,202 | ERROR | stderr | JdbcRegistryCacheInvalidator |
2020-07-12 05:58:43,202 | ERROR | stderr | JdbcRegistryCacheInvalidator | The last packet successfully received from the server was 10,013 milliseconds ago.  The last packet sent successfully to the server was 13 milliseconds ago. Query: SELECT version FROM gw_dataversion Parameters: []
2020-07-12 05:58:43,202 | ERROR | stderr | JdbcRegistryCacheInvalidator |       at org.apache.commons.dbutils.AbstractQueryRunner.rethrow(AbstractQueryRunner.java:392)
2020-07-12 05:58:43,202 | ERROR | stderr | JdbcRegistryCacheInvalidator |       at org.apache.commons.dbutils.QueryRunner.query(QueryRunner.java:351)
2020-07-12 05:58:43,202 | ERROR | stderr | JdbcRegistryCacheInvalidator |       at org.apache.commons.dbutils.QueryRunner.query(QueryRunner.java:307)
2020-07-12 05:58:43,202 | ERROR | stderr | JdbcRegistryCacheInvalidator |       at io.apiman.gateway.engine.jdbc.PollCachingJdbcRegistry.checkCacheVersion(PollCachingJdbcRegistry.java:206)
2020-07-12 05:58:43,202 | ERROR | stderr | JdbcRegistryCacheInvalidator |       at io.apiman.gateway.engine.jdbc.PollCachingJdbcRegistry$5.run(PollCachingJdbcRegistry.java:182)
2020-07-12 05:58:43,202 | ERROR | stderr | JdbcRegistryCacheInvalidator |       at java.lang.Thread.run(Thread.java:748)
2020-07-12 05:58:43,203 | ERROR | stderr | JdbcRegistryCacheInvalidator | java.sql.SQLException: Communications link failure

This doesn't happen on other threads. Pattern is applied on first line, and the rest of the stack trace displays normally.
Regards,
Guillaume

**Comment by volkflo** [comment]
Seems that this is a bug, but I am not a wildfly expert, so this could maybe solved with a different configuration.

**Comment by gromero-pivops** [comment]
I tried to adapt logging configuration but couldn't change the way stdout/stderr are displayed. According to (quite few) Wildfly/Jboss related sites about that specific problem, the hosted application shouldn't write in stdout/stderr, which are  reserved for Wildfly itself (sort of).

**Comment by EricWittmann** [comment]
Yeah I think the bug is actually right here:

https://github.com/apiman/apiman/blob/master/gateway/engine/jdbc/src/main/java/io/apiman/gateway/engine/jdbc/PollCachingJdbcRegistry.java#L213-L214

We should be using a logger here instead of writing to standard error.
