### ISSUE TITLE
Maven 3.6.3 (mvn clean install) build failure

### ISSUE THREAD

**Issue by chooikj275** [apiman/apiman#879]
```
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for apiman 1.5.8-SNAPSHOT:
[INFO]
[INFO] apiman ............................................. SUCCESS [  1.785 s]
[INFO] apiman-common ...................................... SUCCESS [  0.118 s]
[INFO] apiman-common-auth ................................. SUCCESS [  4.782 s]
[INFO] apiman-common-util ................................. SUCCESS [ 10.866 s]
[INFO] apiman-common-config ............................... SUCCESS [  6.442 s]
[INFO] apiman-common-logging .............................. SUCCESS [  0.045 s]
[INFO] apiman-common-logging-core ......................... SUCCESS [  7.412 s]
[INFO] apiman-common-plugin ............................... SUCCESS [  3.160 s]
[INFO] apiman-gateway ..................................... SUCCESS [  0.366 s]
[INFO] apiman-gateway-engine .............................. SUCCESS [  0.190 s]
[INFO] apiman-gateway-engine-beans ........................ SUCCESS [  7.379 s]
[INFO] apiman-gateway-engine-core ......................... SUCCESS [ 13.810 s]
[INFO] apiman-common-logging-log4j2 ....................... SUCCESS [  4.718 s]
[INFO] apiman-common-es ................................... SUCCESS [ 12.126 s]
[INFO] apiman-common-net .................................. SUCCESS [  4.895 s]
[INFO] apiman-common-servlet .............................. SUCCESS [  3.144 s]
[INFO] apiman-common-logging-slf4j ........................ SUCCESS [  1.626 s]
[INFO] apiman-distro ...................................... SUCCESS [  0.082 s]
[INFO] apiman-distro-data ................................. SUCCESS [  0.785 s]
[INFO] apiman-manager ..................................... SUCCESS [  0.351 s]
[INFO] apiman-manager-api ................................. SUCCESS [  0.219 s]
[INFO] apiman-manager-api-beans ........................... SUCCESS [ 17.306 s]
[INFO] apiman-distro-ddl .................................. SUCCESS [ 27.916 s]
[INFO] apiman-manager-api-config .......................... SUCCESS [  4.108 s]
[INFO] apiman-manager-api-core ............................ SUCCESS [  5.848 s]
[INFO] apiman-gateway-api ................................. SUCCESS [  0.051 s]
[INFO] apiman-gateway-api-rest ............................ SUCCESS [  4.053 s]
[INFO] apiman-manager-api-gateway ......................... SUCCESS [  2.887 s]
[INFO] apiman-manager-api-export-import-api ............... SUCCESS [  2.947 s]
[INFO] apiman-manager-api-rest-exceptions ................. SUCCESS [  3.185 s]
[INFO] apiman-manager-api-security ........................ SUCCESS [  5.627 s]
[INFO] apiman-manager-api-rest ............................ SUCCESS [  2.443 s]
[INFO] apiman-test ........................................ SUCCESS [  0.060 s]
[INFO] apiman-test-common ................................. SUCCESS [ 29.998 s]
[INFO] apiman-manager-api-migrator ........................ SUCCESS [  3.729 s]
[INFO] apiman-manager-api-rest-impl ....................... SUCCESS [ 21.398 s]
[INFO] apiman-manager-api-jpa ............................. SUCCESS [  4.092 s]
[INFO] apiman-manager-api-es .............................. SUCCESS [  8.626 s]
[INFO] apiman-manager-api-jdbc ............................ SUCCESS [  3.115 s]
[INFO] apiman-manager-api-hawkular ........................ SUCCESS [  2.456 s]
[INFO] apiman-manager-api-war ............................. SUCCESS [  8.481 s]
[INFO] apiman-manager-api-ispn ............................ SUCCESS [  9.922 s]
[INFO] apiman-manager-api-war-wildfly8 .................... SUCCESS [  3.187 s]
[INFO] apiman-manager-ui .................................. SUCCESS [  0.081 s]
[INFO] apiman-manager-ui-war .............................. SUCCESS [02:15 min]
[INFO] apiman-manager-ui-war-wildfly8 ..................... SUCCESS [  3.339 s]
[INFO] apiman-gateway-engine-filesystem ................... SUCCESS [  3.628 s]
[INFO] apiman-gateway-engine-storage-common ............... SUCCESS [  2.140 s]
[INFO] apiman-gateway-engine-hazelcast .................... SUCCESS [ 13.467 s]
[INFO] apiman-gateway-engine-ispn ......................... SUCCESS [  2.790 s]
[INFO] apiman-gateway-engine-es ........................... SUCCESS [  2.785 s]
[INFO] apiman-gateway-engine-hawkular ..................... SUCCESS [  1.873 s]
[INFO] apiman-gateway-engine-jdbc ......................... SUCCESS [  4.481 s]
[INFO] apiman-gateway-engine-influxdb ..................... SUCCESS [  1.767 s]
[INFO] apiman-test-policies ............................... SUCCESS [  2.152 s]
[INFO] apiman-gateway-engine-policies ..................... SUCCESS [ 41.400 s]
[INFO] apiman-gateway-platforms ........................... SUCCESS [  0.173 s]
[INFO] apiman-gateway-platforms-servlet ................... SUCCESS [  6.754 s]
[INFO] apiman-gateway-api-rest-impl ....................... SUCCESS [  2.303 s]
[INFO] apiman-gateway-platforms-war ....................... SUCCESS [  2.508 s]
[INFO] apiman-gateway-platforms-war-wildfly8 .............. SUCCESS [  0.107 s]
[INFO] apiman-gateway-platforms-war-wildfly8-api .......... SUCCESS [  1.241 s]
[INFO] apiman-gateway-platforms-war-wildfly8-gateway ...... SUCCESS [  1.228 s]
[INFO] apiman-distro-es ................................... SUCCESS [ 57.189 s]
[INFO] apiman-distro-wildfly10 ............................ SUCCESS [01:07 min]
[INFO] apiman-distro-eap7 ................................. SUCCESS [ 14.177 s]
[INFO] apiman-manager-api-war-tomcat8 ..................... SUCCESS [ 20.051 s]
[INFO] apiman-manager-ui-war-tomcat8 ...................... SUCCESS [  3.645 s]
[INFO] apiman-gateway-platforms-war-tomcat8 ............... SUCCESS [  0.069 s]
[INFO] apiman-gateway-platforms-war-tomcat8-api ........... SUCCESS [  2.570 s]
[INFO] apiman-gateway-platforms-war-tomcat8-gateway ....... SUCCESS [  1.326 s]
[INFO] apiman-distro-tomcat8 .............................. SUCCESS [  1.903 s]
[INFO] apiman-distro-wildfly11 ............................ SUCCESS [06:40 min]
[INFO] apiman-gateway-platforms-vertx3-common ............. SUCCESS [  2.683 s]
[INFO] apiman-gateway-engine-vertx-eb-inmemory ............ SUCCESS [  2.320 s]
[INFO] apiman-gateway-engine-vertx-polling ................ SUCCESS [  7.850 s]
[INFO] apiman-gateway-engine-3scale ....................... SUCCESS [  4.820 s]
[INFO] apiman-gateway-engine-prometheus ................... SUCCESS [  6.630 s]
[INFO] apiman-gateway-platforms-vertx3 .................... SUCCESS [ 59.069 s]
[INFO] apiman-distro-vertx ................................ SUCCESS [  2.083 s]
[INFO] apiman-manager-api-micro ........................... SUCCESS [ 12.538 s]
[INFO] apiman-manager-test ................................ SUCCESS [  0.163 s]
[INFO] apiman-manager-test-api ............................ SUCCESS [01:07 min]
[INFO] apiman-gateway-engine-osgi ......................... SUCCESS [  3.383 s]
[INFO] apiman-gateway-engine-redis ........................ FAILURE [ 48.495 s]
[INFO] apiman-gateway-engine-vertx-shareddata ............. SKIPPED
[INFO] apiman-gateway-platforms-war-micro ................. SKIPPED
[INFO] apiman-gateway-test ................................ SKIPPED
[INFO] apiman-test-suite .................................. SKIPPED
[INFO] apiman-tools ....................................... SKIPPED
[INFO] apiman-tools-ddl ................................... SKIPPED
[INFO] apiman-tools-i18n .................................. SKIPPED
[INFO] apiman-tools-jdbc .................................. SKIPPED
[INFO] apiman-tools-ldap .................................. SKIPPED
[INFO] apiman-tools-services .............................. SKIPPED
[INFO] apiman-tools-server-all ............................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  21:13 min
[INFO] Finished at: 2020-08-03T01:02:46+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.17:test (default-test) on project apiman-gateway-engine-redis: There are test failures.
[ERROR]
[ERROR] Please refer to C:\Users\user\apiman\gateway\engine\redis\target\surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :apiman-gateway-engine-redis
```

**Comment by EricWittmann** [comment]
@msavy any objection to disabling the redis module?  I don't think anyone uses it?  Does it work?

**Comment by msavy** [comment]
I think it was from @outofcoffee

**Comment by EricWittmann** [comment]
@chooikj275 can you provide the test error details?

**Comment by chooikj275** [comment]
-------------------------------------------------------------------------------
Test set: io.apiman.gateway.engine.redis.RedisCacheStoreComponentTest
-------------------------------------------------------------------------------
Tests run: 2, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 15.922 sec <<< FAILURE! - in io.apiman.gateway.engine.redis.RedisCacheStoreComponentTest
putAndGetBinary(io.apiman.gateway.engine.redis.RedisCacheStoreComponentTest)  Time elapsed: 0.044 sec  <<< ERROR!
java.lang.IllegalStateException: Could not find a valid Docker environment. Please see logs and check configuration
	at org.testcontainers.dockerclient.DockerClientProviderStrategy.lambda$getFirstValidStrategy$3(DockerClientProviderStrategy.java:157)
	at java.util.Optional.orElseThrow(Optional.java:290)
	at org.testcontainers.dockerclient.DockerClientProviderStrategy.getFirstValidStrategy(DockerClientProviderStrategy.java:149)
	at org.testcontainers.DockerClientFactory.client(DockerClientFactory.java:105)
	at org.testcontainers.containers.GenericContainer.<init>(GenericContainer.java:170)
	at io.apiman.gateway.engine.redis.support.TestRedisUtil.buildRedisContainer(TestRedisUtil.java:27)
	at io.apiman.gateway.engine.redis.RedisCacheStoreComponentTest.<init>(RedisCacheStoreComponentTest.java:41)

putAndGet(io.apiman.gateway.engine.redis.RedisCacheStoreComponentTest)  Time elapsed: 0 sec  <<< ERROR!
java.lang.IllegalStateException: Previous attempts to find a Docker environment failed. Will not retry. Please see logs and check configuration
	at org.testcontainers.dockerclient.DockerClientProviderStrategy.getFirstValidStrategy(DockerClientProviderStrategy.java:78)
	at org.testcontainers.DockerClientFactory.client(DockerClientFactory.java:105)
	at org.testcontainers.containers.GenericContainer.<init>(GenericContainer.java:170)
	at io.apiman.gateway.engine.redis.support.TestRedisUtil.buildRedisContainer(TestRedisUtil.java:27)
	at io.apiman.gateway.engine.redis.RedisCacheStoreComponentTest.<init>(RedisCacheStoreComponentTest.java:41)

**Comment by chooikj275** [comment]
Problem resolved after installing docker environment

**Comment by EricWittmann** [comment]
If docker is only required for the redis build then we should consider putting the redis component in a profile and only enable it if a docker environment is available.

**Comment by outofcoffee** [comment]
Hi @EricWittmann, yes this was introduced via the [testcontainers](https://www.testcontainers.org/) dependency, which provides the Redis instance for the tests.

One other option we could think about would be to move the data store providers (JDBC, Hazelcast, ISPN, Redis etc.) to plugins, enabling them to have their own development lifecycle. The other benefit would be to trim the main tree to contain the core framework rather than hosting the dependencies for each of the implementations.

WDYT?

**Comment by volkflo** [comment]
Just one additional info: 
We will also need docker in the future. In our elasticsearch migration, we also decided to replace the deprecated embedded elasticsearch with testcontainers. I hope we can contribute our changes soon :)

**Comment by EricWittmann** [comment]
Of course - so it's only needed during testing.  That makes sense for sure.  In that case maybe we could disable the tests within the pom.xml unless a docker environment is available?

I have no problem moving data store providers to plugins, but it seems that just moves the docker requirement to the plugins instead. :)

**Comment by outofcoffee** [comment]
Yes, agreed. If the plugins were factored out into their own repos under the apiman GitHub org then those with special requirements only encumber folks building those specific plugins. This could save a single repo (whether it's this one, or apiman-plugins) continuing to acquire ever greater prerequisites for its consumers over time.
