### ISSUE TITLE
Error while starting apiman

### ISSUE THREAD

**Issue by nishasumesh** [apiman/apiman#881]
Hi,

while deploying the latest build, I am getting below error in logs though apiman is starting . 

```2020-08-05 12:06:02,063 WARN  [org.jboss.as.server.deployment] (MSC service thread 1-2) WFLYSRV0003: Could not index class module-info.class at /content/apimanui.war/WEB-INF/lib/jackson-core-2.10.0.jar: java.lang.IllegalStateException: Unknown tag! pos=3 poolCount = 32
	at org.jboss.jandex.Indexer.processConstantPool(Indexer.java:1416)
	at org.jboss.jandex.Indexer.index(Indexer.java:1450)
	at org.jboss.as.server.deployment.annotation.ResourceRootIndexer.indexResourceRoot(ResourceRootIndexer.java:99)
	at org.jboss.as.server.deployment.annotation.AnnotationIndexProcessor.deploy(AnnotationIndexProcessor.java:51)
	at org.jboss.as.server.deployment.DeploymentUnitPhaseService.start(DeploymentUnitPhaseService.java:147)
	at org.jboss.msc.service.ServiceControllerImpl$StartTask.startService(ServiceControllerImpl.java:1948)
	at org.jboss.msc.service.ServiceControllerImpl$StartTask.run(ServiceControllerImpl.java:1881)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

2020-08-05 12:06:02,712 WARN  [org.jboss.as.server.deployment] (MSC service thread 1-2) WFLYSRV0003: Could not index class module-info.class at /content/apimanui.war/WEB-INF/lib/jackson-annotations-2.10.0.jar: java.lang.IllegalStateException: Unknown tag! pos=3 poolCount = 10
	at org.jboss.jandex.Indexer.processConstantPool(Indexer.java:1416)
	at org.jboss.jandex.Indexer.index(Indexer.java:1450)
	at org.jboss.as.server.deployment.annotation.ResourceRootIndexer.indexResourceRoot(ResourceRootIndexer.java:99)
	at org.jboss.as.server.deployment.annotation.AnnotationIndexProcessor.deploy(AnnotationIndexProcessor.java:51)
	at org.jboss.as.server.deployment.DeploymentUnitPhaseService.start(DeploymentUnitPhaseService.java:147)
	at org.jboss.msc.service.ServiceControllerImpl$StartTask.startService(ServiceControllerImpl.java:1948)
	at org.jboss.msc.service.ServiceControllerImpl$StartTask.run(ServiceControllerImpl.java:1881)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

2020-08-05 12:06:02,744 WARN  [org.jboss.as.server.deployment] (MSC service thread 1-7) WFLYSRV0003: Could not index class module-info.class at /content/apiman-gateway-api.war/WEB-INF/lib/jackson-core-2.10.0.jar: java.lang.IllegalStateException: Unknown tag! pos=3 poolCount = 32
	at org.jboss.jandex.Indexer.processConstantPool(Indexer.java:1416)
	at org.jboss.jandex.Indexer.index(Indexer.java:1450)
	at org.jboss.as.server.deployment.annotation.ResourceRootIndexer.indexResourceRoot(ResourceRootIndexer.java:99)
	at org.jboss.as.server.deployment.annotation.AnnotationIndexProcessor.deploy(AnnotationIndexProcessor.java:51)
	at org.jboss.as.server.deployment.DeploymentUnitPhaseService.start(DeploymentUnitPhaseService.java:147)
	at org.jboss.msc.service.ServiceControllerImpl$StartTask.startService(ServiceControllerImpl.java:1948)
	at org.jboss.msc.service.ServiceControllerImpl$StartTask.run(ServiceControllerImpl.java:1881)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

2020-08-05 12:06:02,746 WARN  [org.jboss.as.server.deployment] (MSC service thread 1-7) WFLYSRV0003: Could not index class META-INF/versions/9/module-info.class at /content/apiman-gateway-api.war/WEB-INF/lib/log4j-api-2.12.0.jar: java.lang.IllegalStateException: Unknown tag! pos=4 poolCount = 33
	at org.jboss.jandex.Indexer.processConstantPool(Indexer.java:1416)
	at org.jboss.jandex.Indexer.index(Indexer.java:1450)
	at org.jboss.as.server.deployment.annotation.ResourceRootIndexer.indexResourceRoot(ResourceRootIndexer.java:99)
	at org.jboss.as.server.deployment.annotation.AnnotationIndexProcessor.deploy(AnnotationIndexProcessor.java:51)
	at org.jboss.as.server.deployment.DeploymentUnitPhaseService.start(DeploymentUnitPhaseService.java:147)
	at org.jboss.msc.service.ServiceControllerImpl$StartTask.startService(ServiceControllerImpl.java:1948)
	at org.jboss.msc.service.ServiceControllerImpl$StartTask.run(ServiceControllerImpl.java:1881)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

2020-08-05 12:06:02,768 WARN  [org.jboss.as.server.deployment] (MSC service thread 1-8) WFLYSRV0003: Could not index class module-info.class at /content/apiman-gateway.war/WEB-INF/lib/jackson-core-2.10.0.jar: java.lang.IllegalStateException: Unknown tag! pos=3 poolCount = 32
	at org.jboss.jandex.Indexer.processConstantPool(Indexer.java:1416)
	at org.jboss.jandex.Indexer.index(Indexer.java:1450)
	at org.jboss.as.server.deployment.annotation.ResourceRootIndexer.indexResourceRoot(ResourceRootIndexer.java:99)
	at org.jboss.as.server.deployment.annotation.AnnotationIndexProcessor.deploy(AnnotationIndexProcessor.java:51)
	at org.jboss.as.server.deployment.DeploymentUnitPhaseService.start(DeploymentUnitPhaseService.java:147)
	at org.jboss.msc.service.ServiceControllerImpl$StartTask.startService(ServiceControllerImpl.java:1948)
	at org.jboss.msc.service.ServiceControllerImpl$StartTask.run(ServiceControllerImpl.java:1881)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

2020-08-05 12:06:02,770 WARN  [org.jboss.as.server.deployment] (MSC service thread 1-8) WFLYSRV0003: Could not index class META-INF/versions/9/module-info.class at /content/apiman-gateway.war/WEB-INF/lib/log4j-api-2.12.0.jar: java.lang.IllegalStateException: Unknown tag! pos=4 poolCount = 33
	at org.jboss.jandex.Indexer.processConstantPool(Indexer.java:1416)
	at org.jboss.jandex.Indexer.index(Indexer.java:1450)
	at org.jboss.as.server.deployment.annotation.ResourceRootIndexer.indexResourceRoot(ResourceRootIndexer.java:99)
	at org.jboss.as.server.deployment.annotation.AnnotationIndexProcessor.deploy(AnnotationIndexProcessor.java:51)
	at org.jboss.as.server.deployment.DeploymentUnitPhaseService.start(DeploymentUnitPhaseService.java:147)
	at org.jboss.msc.service.ServiceControllerImpl$StartTask.startService(ServiceControllerImpl.java:1948)
	at org.jboss.msc.service.ServiceControllerImpl$StartTask.run(ServiceControllerImpl.java:1881)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

2020-08-05 12:06:03,021 WARN  [org.jboss.as.server.deployment] (MSC service thread 1-6) WFLYSRV0003: Could not index class module-info.class at /content/apiman.war/WEB-INF/lib/jakarta.xml.bind-api-2.3.2.jar: java.lang.IllegalStateException: Unknown tag! pos=4 poolCount = 31
	at org.jboss.jandex.Indexer.processConstantPool(Indexer.java:1416)
	at org.jboss.jandex.Indexer.index(Indexer.java:1450)
	at org.jboss.as.server.deployment.annotation.ResourceRootIndexer.indexResourceRoot(ResourceRootIndexer.java:99)
	at org.jboss.as.server.deployment.annotation.AnnotationIndexProcessor.deploy(AnnotationIndexProcessor.java:51)
	at org.jboss.as.server.deployment.DeploymentUnitPhaseService.start(DeploymentUnitPhaseService.java:147)
	at org.jboss.msc.service.ServiceControllerImpl$StartTask.startService(ServiceControllerImpl.java:1948)
	at org.jboss.msc.service.ServiceControllerImpl$StartTask.run(ServiceControllerImpl.java:1881)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

2020-08-05 12:06:03,055 WARN  [org.jboss.as.server.deployment] (MSC service thread 1-1) WFLYSRV0003: Could not index class module-info.class at /content/apiman-es.war/WEB-INF/lib/jackson-core-2.10.0.jar: java.lang.IllegalStateException: Unknown tag! pos=3 poolCount = 32
	at org.jboss.jandex.Indexer.processConstantPool(Indexer.java:1416)
	at org.jboss.jandex.Indexer.index(Indexer.java:1450)
	at org.jboss.as.server.deployment.annotation.ResourceRootIndexer.indexResourceRoot(ResourceRootIndexer.java:99)
	at org.jboss.as.server.deployment.annotation.AnnotationIndexProcessor.deploy(AnnotationIndexProcessor.java:51)
	at org.jboss.as.server.deployment.DeploymentUnitPhaseService.start(DeploymentUnitPhaseService.java:147)
	at org.jboss.msc.service.ServiceControllerImpl$StartTask.startService(ServiceControllerImpl.java:1948)
	at org.jboss.msc.service.ServiceControllerImpl$StartTask.run(ServiceControllerImpl.java:1881)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

2020-08-05 12:06:03,056 WARN  [org.jboss.as.server.deployment] (MSC service thread 1-1) WFLYSRV0003: Could not index class META-INF/versions/9/module-info.class at /content/apiman-es.war/WEB-INF/lib/log4j-api-2.12.0.jar: java.lang.IllegalStateException: Unknown tag! pos=4 poolCount = 33
	at org.jboss.jandex.Indexer.processConstantPool(Indexer.java:1416)
	at org.jboss.jandex.Indexer.index(Indexer.java:1450)
	at org.jboss.as.server.deployment.annotation.ResourceRootIndexer.indexResourceRoot(ResourceRootIndexer.java:99)
	at org.jboss.as.server.deployment.annotation.AnnotationIndexProcessor.deploy(AnnotationIndexProcessor.java:51)
	at org.jboss.as.server.deployment.DeploymentUnitPhaseService.start(DeploymentUnitPhaseService.java:147)
	at org.jboss.msc.service.ServiceControllerImpl$StartTask.startService(ServiceControllerImpl.java:1948)
	at org.jboss.msc.service.ServiceControllerImpl$StartTask.run(ServiceControllerImpl.java:1881)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

2020-08-05 12:06:03,072 ERROR [org.jboss.as.controller.management-operation] (RMI TCP Connection(1)-192.168.1.6) WFLYCTL0013: Operation ("read-resource-description") failed - address: ([
    ("subsystem" => "datasources"),
    ("data-source" => "ExampleDS"),
    ("statistics" => "jdbc")
]) - failure description: "WFLYCTL0030: No resource definition is registered for address [
    (\"subsystem\" => \"datasources\"),
    (\"data-source\" => \"ExampleDS\"),
    (\"statistics\" => \"jdbc\")
]"
2020-08-05 12:06:03,076 ERROR [org.jboss.as.controller.management-operation] (RMI TCP Connection(1)-192.168.1.6) WFLYCTL0013: Operation ("read-resource-description") failed - address: ([
    ("subsystem" => "datasources"),
    ("data-source" => "ExampleDS"),
    ("statistics" => "pool")
]) - failure description: "WFLYCTL0030: No resource definition is registered for address [
    (\"subsystem\" => \"datasources\"),
    (\"data-source\" => \"ExampleDS\"),
    (\"statistics\" => \"pool\")
]"
2020-08-05 12:06:03,082 ERROR [org.jboss.as.controller.management-operation] (RMI TCP Connection(1)-192.168.1.6) WFLYCTL0013: Operation ("read-resource-description") failed - address: ([
    ("subsystem" => "datasources"),
    ("data-source" => "KeycloakDS"),
    ("statistics" => "jdbc")
]) - failure description: "WFLYCTL0030: No resource definition is registered for address [
    (\"subsystem\" => \"datasources\"),
    (\"data-source\" => \"KeycloakDS\"),
    (\"statistics\" => \"jdbc\")
]"
2020-08-05 12:06:03,083 ERROR [org.jboss.as.controller.management-operation] (RMI TCP Connection(1)-192.168.1.6) WFLYCTL0013: Operation ("read-resource-description") failed - address: ([
    ("subsystem" => "datasources"),
    ("data-source" => "KeycloakDS"),
    ("statistics" => "pool")
]) - failure description: "WFLYCTL0030: No resource definition is registered for address [
    (\"subsystem\" => \"datasources\"),
    (\"data-source\" => \"KeycloakDS\"),
    (\"statistics\" => \"pool\")
]"
2020-08-05 12:06:03,253 WARN  [org.jboss.as.server.deployment] (MSC service thread 1-2) WFLYSRV0003: Could not index class module-info.class at /content/apimanui.war/WEB-INF/lib/jackson-databind-2.10.0.jar: java.lang.IllegalStateException: Unknown tag! pos=3 poolCount = 66
	at org.jboss.jandex.Indexer.processConstantPool(Indexer.java:1416)
	at org.jboss.jandex.Indexer.index(Indexer.java:1450)
	at org.jboss.as.server.deployment.annotation.ResourceRootIndexer.indexResourceRoot(ResourceRootIndexer.java:99)
	at org.jboss.as.server.deployment.annotation.AnnotationIndexProcessor.deploy(AnnotationIndexProcessor.java:51)
	at org.jboss.as.server.deployment.DeploymentUnitPhaseService.start(DeploymentUnitPhaseService.java:147)
	at org.jboss.msc.service.ServiceControllerImpl$StartTask.startService(ServiceControllerImpl.java:1948)
	at org.jboss.msc.service.ServiceControllerImpl$StartTask.run(ServiceControllerImpl.java:1881)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

2020-08-05 12:06:03,367 WARN  [org.jboss.as.server.deployment] (MSC service thread 1-6) WFLYSRV0003: Could not index class module-info.class at /content/apiman.war/WEB-INF/lib/jackson-core-2.10.0.jar: java.lang.IllegalStateException: Unknown tag! pos=3 poolCount = 32
	at org.jboss.jandex.Indexer.processConstantPool(Indexer.java:1416)
	at org.jboss.jandex.Indexer.index(Indexer.java:1450)
	at org.jboss.as.server.deployment.annotation.ResourceRootIndexer.indexResourceRoot(ResourceRootIndexer.java:99)
	at org.jboss.as.server.deployment.annotation.AnnotationIndexProcessor.deploy(AnnotationIndexProcessor.java:51)
	at org.jboss.as.server.deployment.DeploymentUnitPhaseService.start(DeploymentUnitPhaseService.java:147)
	at org.jboss.msc.service.ServiceControllerImpl$StartTask.startService(ServiceControllerImpl.java:1948)
	at org.jboss.msc.service.ServiceControllerImpl$StartTask.run(ServiceControllerImpl.java:1881)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

2020-08-05 12:06:03,370 WARN  [org.jboss.as.server.deployment] (MSC service thread 1-6) WFLYSRV0003: Could not index class META-INF/versions/9/module-info.class at /content/apiman.war/WEB-INF/lib/log4j-api-2.12.0.jar: java.lang.IllegalStateException: Unknown tag! pos=4 poolCount = 33
	at org.jboss.jandex.Indexer.processConstantPool(Indexer.java:1416)
	at org.jboss.jandex.Indexer.index(Indexer.java:1450)
	at org.jboss.as.server.deployment.annotation.ResourceRootIndexer.indexResourceRoot(ResourceRootIndexer.java:99)
	at org.jboss.as.server.deployment.annotation.AnnotationIndexProcessor.deploy(AnnotationIndexProcessor.java:51)
	at org.jboss.as.server.deployment.DeploymentUnitPhaseService.start(DeploymentUnitPhaseService.java:147)
	at org.jboss.msc.service.ServiceControllerImpl$StartTask.startService(ServiceControllerImpl.java:1948)
	at org.jboss.msc.service.ServiceControllerImpl$StartTask.run(ServiceControllerImpl.java:1881)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

2020-08-05 12:06:03,887 WARN  [org.jboss.as.server.deployment] (MSC service thread 1-6) WFLYSRV0003: Could not index class module-info.class at /content/apiman.war/WEB-INF/lib/woodstox-core-6.0.1.jar: java.lang.IllegalStateException: Unknown tag! pos=3 poolCount = 70
	at org.jboss.jandex.Indexer.processConstantPool(Indexer.java:1416)
	at org.jboss.jandex.Indexer.index(Indexer.java:1450)
	at org.jboss.as.server.deployment.annotation.ResourceRootIndexer.indexResourceRoot(ResourceRootIndexer.java:99)
	at org.jboss.as.server.deployment.annotation.AnnotationIndexProcessor.deploy(AnnotationIndexProcessor.java:51)
	at org.jboss.as.server.deployment.DeploymentUnitPhaseService.start(DeploymentUnitPhaseService.java:147)
	at org.jboss.msc.service.ServiceControllerImpl$StartTask.startService(ServiceControllerImpl.java:1948)
	at org.jboss.msc.service.ServiceControllerImpl$StartTask.run(ServiceControllerImpl.java:1881)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

2020-08-05 12:06:04,270 WARN  [org.jboss.as.server.deployment] (MSC service thread 1-7) WFLYSRV0003: Could not index class module-info.class at /content/apiman-gateway-api.war/WEB-INF/lib/jackson-dataformat-yaml-2.10.0.jar: java.lang.IllegalStateException: Unknown tag! pos=3 poolCount = 26
	at org.jboss.jandex.Indexer.processConstantPool(Indexer.java:1416)
	at org.jboss.jandex.Indexer.index(Indexer.java:1450)
	at org.jboss.as.server.deployment.annotation.ResourceRootIndexer.indexResourceRoot(ResourceRootIndexer.java:99)
	at org.jboss.as.server.deployment.annotation.AnnotationIndexProcessor.deploy(AnnotationIndexProcessor.java:51)
	at org.jboss.as.server.deployment.DeploymentUnitPhaseService.start(DeploymentUnitPhaseService.java:147)
	at org.jboss.msc.service.ServiceControllerImpl$StartTask.startService(ServiceControllerImpl.java:1948)
	at org.jboss.msc.service.ServiceControllerImpl$StartTask.run(ServiceControllerImpl.java:1881)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

2020-08-05 12:06:04,294 WARN  [org.jboss.as.server.deployment] (MSC service thread 1-8) WFLYSRV0003: Could not index class module-info.class at /content/apiman-gateway.war/WEB-INF/lib/jackson-dataformat-yaml-2.10.0.jar: java.lang.IllegalStateException: Unknown tag! pos=3 poolCount = 26
	at org.jboss.jandex.Indexer.processConstantPool(Indexer.java:1416)
	at org.jboss.jandex.Indexer.index(Indexer.java:1450)
	at org.jboss.as.server.deployment.annotation.ResourceRootIndexer.indexResourceRoot(ResourceRootIndexer.java:99)
	at org.jboss.as.server.deployment.annotation.AnnotationIndexProcessor.deploy(AnnotationIndexProcessor.java:51)
	at org.jboss.as.server.deployment.DeploymentUnitPhaseService.start(DeploymentUnitPhaseService.java:147)
	at org.jboss.msc.service.ServiceControllerImpl$StartTask.startService(ServiceControllerImpl.java:1948)
	at org.jboss.msc.service.ServiceControllerImpl$StartTask.run(ServiceControllerImpl.java:1881)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

2020-08-05 12:06:04,531 WARN  [org.jboss.as.server.deployment] (MSC service thread 1-1) WFLYSRV0003: Could not index class module-info.class at /content/apiman-es.war/WEB-INF/lib/jackson-dataformat-yaml-2.10.0.jar: java.lang.IllegalStateException: Unknown tag! pos=3 poolCount = 26
	at org.jboss.jandex.Indexer.processConstantPool(Indexer.java:1416)
	at org.jboss.jandex.Indexer.index(Indexer.java:1450)
	at org.jboss.as.server.deployment.annotation.ResourceRootIndexer.indexResourceRoot(ResourceRootIndexer.java:99)
	at org.jboss.as.server.deployment.annotation.AnnotationIndexProcessor.deploy(AnnotationIndexProcessor.java:51)
	at org.jboss.as.server.deployment.DeploymentUnitPhaseService.start(DeploymentUnitPhaseService.java:147)
	at org.jboss.msc.service.ServiceControllerImpl$StartTask.startService(ServiceControllerImpl.java:1948)
	at org.jboss.msc.service.ServiceControllerImpl$StartTask.run(ServiceControllerImpl.java:1881)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

2020-08-05 12:06:05,036 ERROR [org.jboss.as.controller.management-operation] (RMI TCP Connection(1)-192.168.1.6) WFLYCTL0013: Operation ("read-resource-description") failed - address: ([
    ("subsystem" => "datasources"),
    ("data-source" => "ExampleDS"),
    ("statistics" => "jdbc")
]) - failure description: "WFLYCTL0030: No resource definition is registered for address [
    (\"subsystem\" => \"datasources\"),
    (\"data-source\" => \"ExampleDS\"),
    (\"statistics\" => \"jdbc\")
]"
2020-08-05 12:06:05,038 ERROR [org.jboss.as.controller.management-operation] (RMI TCP Connection(1)-192.168.1.6) WFLYCTL0013: Operation ("read-resource-description") failed - address: ([
    ("subsystem" => "datasources"),
    ("data-source" => "ExampleDS"),
    ("statistics" => "pool")
]) - failure description: "WFLYCTL0030: No resource definition is registered for address [
    (\"subsystem\" => \"datasources\"),
    (\"data-source\" => \"ExampleDS\"),
    (\"statistics\" => \"pool\")
]"
2020-08-05 12:06:05,059 ERROR [org.jboss.as.controller.management-operation] (RMI TCP Connection(1)-192.168.1.6) WFLYCTL0013: Operation ("read-resource-description") failed - address: ([
    ("subsystem" => "datasources"),
    ("data-source" => "KeycloakDS"),
    ("statistics" => "jdbc")
]) - failure description: "WFLYCTL0030: No resource definition is registered for address [
    (\"subsystem\" => \"datasources\"),
    (\"data-source\" => \"KeycloakDS\"),
    (\"statistics\" => \"jdbc\")
]"
2020-08-05 12:06:05,060 ERROR [org.jboss.as.controller.management-operation] (RMI TCP Connection(1)-192.168.1.6) WFLYCTL0013: Operation ("read-resource-description") failed - address: ([
    ("subsystem" => "datasources"),
    ("data-source" => "KeycloakDS"),
    ("statistics" => "pool")
]) - failure description: "WFLYCTL0030: No resource definition is registered for address [
    (\"subsystem\" => \"datasources\"),
    (\"data-source\" => \"KeycloakDS\"),
    (\"statistics\" => \"pool\")
]"
```

**Comment by nishasumesh** [comment]
It is my bad. There was another h2 instance running which was  blocking my start up.

**Comment by EricWittmann** [comment]
You can safely ignore any of the `Could not index class module-info.class` errors - those are caused by newer JAR dependencies having issues being parsed by the old Wildfly module loader.  This would be resolved if we were to upgrade to a more recent version of Wildfly (something I think we should do).

However, the `No resource definition is registered for address` error is likely a problem.  However, I'm not sure what's causing it without seeing the rest of your configuration.

**Comment by nishasumesh** [comment]
[apiman.txt](https://github.com/apiman/apiman/files/5055530/apiman.txt)

**Comment by nishasumesh** [comment]
[apiman-ds.txt](https://github.com/apiman/apiman/files/5055565/apiman-ds.txt)
[apiman.txt](https://github.com/apiman/apiman/files/5055566/apiman.txt)
[standalone.txt](https://github.com/apiman/apiman/files/5055567/standalone.txt)

attaching my configchanges.

**Comment by EricWittmann** [comment]
OK so I've had a look at the files you attached.  The properties file changes look OK to me.  You've switched from ES to JDBC as the Gateway Registry provider.  That's fine.  You've defined the JNDI location of the datasource for that to be here:

`java:jboss/datasources/apiman-gateway`

That's good but you'll need an `apiman-gateway-ds.xml` file that defines that datasource.  You didn't attach one so I'm not sure if you have it.  In other words - you'll need **two** datasource definition files:

* apiman-ds.xml
* apiman-gateway-ds.xml

Because you'll have two datasources - one for the manager and one for the gateway registry.

Additionally, you've attached the `standalone.xml` file but I'm assuming you actually made changes to the `standalone-apiman.xml` file and should perhaps have attached that instead.  I compared the file you attached with the one that comes with the quickstart and they were identical. :)
