### ISSUE TITLE
apiman-gateway name change

### ISSUE THREAD

**Issue by nishasumesh** [apiman/apiman#882]
Hi,

I want to remove the url base path "http://localhost:8080/apiman-gateway/"

this is the base path of my api endpoint after registering my api's. Is there a way to remove the name "apiman-gateway" from the url.

**Comment by bekihm** [comment]
Hello @nishasumesh,
it seems that the context-root is defined in the jboss-web.xml under gateway\platforms\war\wildfly8\gateway\src\main\webapp\WEB-INF.
Not sure if it works but can you try to change it there?

Regards
Benjamin

**Comment by nishasumesh** [comment]
ok. will try that.

**Comment by nishasumesh** [comment]
can you share the  release 1.5.7.Final  git link. 
I could not find any tagged releases here "https://libraries.io/github/apiman/apiman/tags"
I was using a direct build using below commands 

curl https://download.jboss.org/wildfly/10.1.0.Final/wildfly-10.1.0.Final.zip -o wildfly-10.1.0.Final.zip
curl https://downloads.jboss.org/apiman/1.5.7.Final/apiman-distro-wildfly10-1.5.7.Final-overlay.zip -o apiman-distro-wildfly10-

**Comment by bekihm** [comment]
You mean that?
https://github.com/apiman/apiman/tree/apiman-1.5.7.Final

**Comment by bekihm** [comment]
Here is the link from the code button:
https://github.com/apiman/apiman/archive/apiman-1.5.7.Final.zip

**Comment by EricWittmann** [comment]
This conversation might be interesting to you @nishasumesh :  https://github.com/apiman/apiman/issues/875

**Comment by spsvon** [comment]
I try to leave only a slash in jboss-web.xml
```
<?xml version="1.0" encoding="UTF-8"?>
<jboss-web>
  <context-root>/</context-root>
</jboss-web>
```
But I've received this error with curl when i try to call apiman without apiman-gateway suffix:
ERROR [io.apiman.gateway.engine.impl.DefaultPolicyErrorWriter] (default task-32) Invalid endpoint provided: /: java.lang.IllegalArgumentException: Invalid endpoint provided: /

When I've tried to restore to apiman-gateway and I've received another error:
```
io.apiman.gateway.engine.beans.exceptions.RequestAbortedException: io.apiman.gateway.engine.beans.exceptions.ConnectorException: released
at io.apiman.gateway.engine.impl.ApiRequestExecutorImpl$3.abort(ApiRequestExecutorImpl.java:771)
at io.apiman.gateway.platforms.servlet.GatewayServlet$2.handle(GatewayServlet.java:174)
at io.apiman.gateway.platforms.servlet.GatewayServlet$2.handle(GatewayServlet.java:161)
at io.apiman.gateway.engine.impl.ApiRequestExecutorImpl.handleStream(ApiRequestExecutorImpl.java:743)
at io.apiman.gateway.engine.impl.ApiRequestExecutorImpl.lambda$null$4(ApiRequestExecutorImpl.java:298)
at io.apiman.gateway.engine.policy.Chain.handleHead(Chain.java:238)
at io.apiman.gateway.engine.policy.Chain.doApply(Chain.java:152)
at io.apiman.gateway.engine.impl.ApiRequestExecutorImpl.lambda$execute$5(ApiRequestExecutorImpl.java:300)
at io.apiman.gateway.engine.impl.ApiRequestExecutorImpl.loadPolicies(ApiRequestExecutorImpl.java:641)
at io.apiman.gateway.engine.impl.ApiRequestExecutorImpl.lambda$execute$6(ApiRequestExecutorImpl.java:412)
at io.apiman.gateway.engine.impl.SecureRegistryWrapper$2.handle(SecureRegistryWrapper.java:189)
at io.apiman.gateway.engine.impl.SecureRegistryWrapper$2.handle(SecureRegistryWrapper.java:171)
at io.apiman.gateway.engine.jdbc.CachingJdbcRegistry.getContract(CachingJdbcRegistry.java:102)
at io.apiman.gateway.engine.impl.SecureRegistryWrapper.getContract(SecureRegistryWrapper.java:171)
at io.apiman.gateway.engine.impl.ApiRequestExecutorImpl.execute(ApiRequestExecutorImpl.java:378)
at io.apiman.gateway.platforms.servlet.GatewayServlet.doAction(GatewayServlet.java:178)
at io.apiman.gateway.platforms.servlet.GatewayServlet.service(GatewayServlet.java:79)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:590)
at io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:74)
at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62)
at io.undertow.servlet.handlers.ServletChain$1.handleRequest(ServletChain.java:68)
at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)
at org.wildfly.extension.undertow.security.SecurityContextAssociationHandler.handleRequest(SecurityContextAssociationHandler.java:78)
at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
at io.undertow.servlet.handlers.RedirectDirHandler.handleRequest(RedirectDirHandler.java:68)
at io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:132)
at io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57)
at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46)
at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64)
at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60)
at io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77)
at io.undertow.security.handlers.NotificationReceiverHandler.handleRequest(NotificationReceiverHandler.java:50)
at io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43)
at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
at org.wildfly.extension.undertow.security.jacc.JACCContextIdHandler.handleRequest(JACCContextIdHandler.java:61)
at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
at org.wildfly.extension.undertow.deployment.GlobalRequestControllerHandler.handleRequest(GlobalRequestControllerHandler.java:68)
at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:269)
at io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:78)
at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:133)
at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:130)
at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48)
at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
at org.wildfly.extension.undertow.security.SecurityContextThreadSetupAction.lambda$create$0(SecurityContextThreadSetupAction.java:105)
at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1530)
at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1530)
at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1530)
at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1530)
at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:249)
at io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:78)
at io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:99)
at io.undertow.server.Connectors.executeRootHandler(Connectors.java:370)
at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:830)
at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1982)
at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1486)
at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1377)
at java.lang.Thread.run(Thread.java:748)\nCaused by: io.apiman.gateway.engine.beans.exceptions.ConnectorException: released
at io.apiman.gateway.engine.handler.ErrorHandler.handleConnectionError(ErrorHandler.java:40)
at io.apiman.gateway.platforms.servlet.connectors.HttpApiConnection.handleConnectionError(HttpApiConnection.java:401)
at io.apiman.gateway.platforms.servlet.connectors.HttpApiConnection.end(HttpApiConnection.java:365)
at io.apiman.gateway.engine.impl.ApiRequestExecutorImpl.lambda$null$3(ApiRequestExecutorImpl.java:293)
at io.apiman.gateway.engine.io.AbstractStream.handleEnd(AbstractStream.java:116)
at io.apiman.gateway.engine.policy.Chain.end(Chain.java:220)
at io.apiman.gateway.engine.impl.ApiRequestExecutorImpl$3.end(ApiRequestExecutorImpl.java:756)
at io.apiman.gateway.platforms.servlet.GatewayServlet$2.handle(GatewayServlet.java:172)
... 58 more\nCaused by: java.lang.IllegalStateException: released
at com.squareup.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:152)
at com.squareup.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:126)
at com.squareup.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:95)
at com.squareup.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:281)
at com.squareup.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:224)
at io.apiman.gateway.platforms.servlet.connectors.ok.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:443)
at io.apiman.gateway.platforms.servlet.connectors.ok.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:395)
at io.apiman.gateway.platforms.servlet.connectors.ok.HttpURLConnectionImpl.getHeaders(HttpURLConnectionImpl.java:151)
at io.apiman.gateway.platforms.servlet.connectors.ok.HttpURLConnectionImpl.getHeaderFields(HttpURLConnectionImpl.java:211)
at io.apiman.gateway.platforms.servlet.connectors.HttpApiConnection.end(HttpApiConnection.java:352)
```

**Comment by msavy** [comment]
That should be easier with the Vert.x Gateway instead as that's a separate deployment

**Comment by spsvon** [comment]
Thanks msavy for quick response.
I need to use Docker with /wildfly/jboss approach because its a platform requirement. 
I don't know if nishasumesh  succeeded with jboss-web.xml changes

**Comment by msavy** [comment]
Understood.

I'll try to look at it when I have time and will report back here.

**Comment by spsvon** [comment]
Finally I've success only changing jboss-web.xml and rebooting docker. I think that my echo-service was not correctly configured due localhost to user domain error in my system.

I confirm that if you change .war jboss-web.xml (only leaving the slash in the context root), repack and redeploy it'll work like a charm (no need of using apiman-gateway at url).
However in Manager it still showing apiman-gateway in endpoints:

![image](https://user-images.githubusercontent.com/16747880/141086766-95f450da-8221-4095-ab76-7783e49f5af6.png)

I see here https://www.apiman.io/latest/production-guide.html#_setting_the_api_gateway_public_endpoint that it's possible to set the API Gateway Public Endpoint via apiman-gateway.public-endpoint property in apiman.properties files. 
Is it that still possible in 2.1.0 version of apiman? 
Thanks a lot

**Comment by msavy** [comment]
Well done!

Yes, it should still work.

**Comment by aisrccnsl** [comment]
Hello. I am using APIMAN 3.1.3 on docker compose. I wonder how to remove the port number right after the gateway domain name, since I deployed the APIMAN under cloudflare proxy, tunneling directly gateway port 8080 to the specific domain

<img width="1152" alt="Image" src="https://github.com/user-attachments/assets/29173056-309c-4669-93d9-b8ee8fc50ae8" />
