### ISSUE TITLE
how to bring up apiman without elastic search

### ISSUE THREAD

**Issue by nishasumesh** [apiman/apiman#885]
Hi,

I want to start my apiman without elasticsearch (using only jdbc , postgresql) . Can you share the config files  / docs for that.
I tried "https://apiman.gitbooks.io/apiman-installation-guide/content/installation-guide/registries-and-components/jdbc.html",  but getting many errors and apiman-gateway is not coming up also.

**Comment by EricWittmann** [comment]
That's the best documentation we have on the topic.  Can you share your config and startup log?

**Comment by nishasumesh** [comment]
[apiman-ds.txt](https://github.com/apiman/apiman/files/5056796/apiman-ds.txt)
[apiman.txt](https://github.com/apiman/apiman/files/5056797/apiman.txt)

[server.log](https://github.com/apiman/apiman/files/5056800/server.log)


PFA...

**Comment by EricWittmann** [comment]
I think what you're missing is the `-ds.xml` file that would define the `apiman-gateway` datasource.  Basically you need to make a copy of the `apiman-ds.txt` file and call it `apiman-gateway-ds.xml`.  Then you need to modify that new file and modify line 3 from this:

```    <datasource enabled="true" jndi-name="java:jboss/datasources/apiman-manager" pool-name="apiman-manager-api" use-java-context="true">
```

to this

```    <datasource enabled="true" jndi-name="java:jboss/datasources/apiman-gateway" pool-name="apiman-gateway-api" use-java-context="true">
```

I think that **should** do the trick.

**Comment by nishasumesh** [comment]
hi @EricWittmann , I tried adding apiman-gateway-ds.xml. I am getting an error saying one of the tables is missing . May be the zip i have doesnot have the table mentioned. Can you share the latest ddl file for gateway.

**Comment by nishasumesh** [comment]
[log.txt](https://github.com/apiman/apiman/files/5060714/log.txt)

**Comment by nishasumesh** [comment]
https://github.com/apiman/apiman/blob/master/distro/data/src/main/resources/ddls/apiman-gateway_postgresql9.ddl

trying with this

**Comment by nishasumesh** [comment]
apiman is up now. But client registration is failing with the below error

io.apiman.manager.api.rest.exceptions.ActionException: Failed to register client.
	at io.apiman.manager.api.rest.exceptions.util.ExceptionFactory.actionException(ExceptionFactory.java:293)
	at io.apiman.manager.api.rest.impl.ActionResourceImpl.registerClient(ActionResourceImpl.java:413)
	at io.apiman.manager.api.rest.impl.ActionResourceImpl.performAction(ActionResourceImpl.java:99)
	at io.apiman.manager.api.rest.impl.ActionResourceImpl$Proxy$_$$_WeldClientProxy.performAction(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:139)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:295)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:249)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:236)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:402)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:209)
	at org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.service(ServletContainerDispatcher.java:221)
	at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:56)
	at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:51)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:85)
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:129)
	at io.apiman.common.servlet.RootResourceFilter.doFilter(RootResourceFilter.java:59)
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
	at io.apiman.manager.api.war.TransactionWatchdogFilter.doFilter(TransactionWatchdogFilter.java:57)
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
	at io.apiman.manager.api.security.impl.DefaultSecurityContextFilter.doFilter(DefaultSecurityContextFilter.java:55)
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
	at io.apiman.common.servlet.DisableCachingFilter.doFilter(DisableCachingFilter.java:52)
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
	at io.apiman.common.servlet.ApimanCorsFilter.doFilter(ApimanCorsFilter.java:71)
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
	at io.apiman.common.servlet.LocaleFilter.doFilter(LocaleFilter.java:61)
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
	at io.undertow.servlet.handlers.FilterHandler.handleRequest(FilterHandler.java:84)
	at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62)
	at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)
	at org.wildfly.extension.undertow.security.SecurityContextAssociationHandler.handleRequest(SecurityContextAssociationHandler.java:78)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at org.keycloak.adapters.undertow.UndertowAuthenticatedActionsHandler.handleRequest(UndertowAuthenticatedActionsHandler.java:66)
	at io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:131)
	at io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57)
	at io.undertow.server.handlers.DisableCacheHandler.handleRequest(DisableCacheHandler.java:33)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.security.handlers.AuthenticationConstraintHandler.handleRequest(AuthenticationConstraintHandler.java:53)
	at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46)
	at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64)
	at io.undertow.servlet.handlers.security.ServletSecurityConstraintHandler.handleRequest(ServletSecurityConstraintHandler.java:59)
	at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60)
	at io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77)
	at io.undertow.security.handlers.NotificationReceiverHandler.handleRequest(NotificationReceiverHandler.java:50)
	at io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at org.wildfly.extension.undertow.security.jacc.JACCContextIdHandler.handleRequest(JACCContextIdHandler.java:61)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at org.keycloak.adapters.undertow.ServletPreAuthActionsHandler.handleRequest(ServletPreAuthActionsHandler.java:69)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:292)
	at io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:81)
	at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:138)
	at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:135)
	at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48)
	at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
	at io.undertow.servlet.api.LegacyThreadSetupActionWrapper$1.call(LegacyThreadSetupActionWrapper.java:44)
	at io.undertow.servlet.api.LegacyThreadSetupActionWrapper$1.call(LegacyThreadSetupActionWrapper.java:44)
	at io.undertow.servlet.api.LegacyThreadSetupActionWrapper$1.call(LegacyThreadSetupActionWrapper.java:44)
	at io.undertow.servlet.api.LegacyThreadSetupActionWrapper$1.call(LegacyThreadSetupActionWrapper.java:44)
	at io.undertow.servlet.api.LegacyThreadSetupActionWrapper$1.call(LegacyThreadSetupActionWrapper.java:44)
	at io.undertow.servlet.api.LegacyThreadSetupActionWrapper$1.call(LegacyThreadSetupActionWrapper.java:44)
	at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:272)
	at io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:81)
	at io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:104)
	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:202)
	at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:805)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: Client registration failed: 404
	at io.apiman.manager.api.gateway.rest.GatewayClient.register(GatewayClient.java:189)
	at io.apiman.manager.api.gateway.rest.RestGatewayLink.registerClient(RestGatewayLink.java:197)
	at io.apiman.manager.api.rest.impl.ActionResourceImpl.registerClient(ActionResourceImpl.java:407)
	... 79 more

**Comment by EricWittmann** [comment]
The 404 error means that the manage could not locate the Gateway API (which exists in a separate WAR file).  Please follow this thread here:  https://github.com/apiman/apiman/issues/875

This same problem was encountered there but I'm not sure how it was fixed.  In particular make sure that you can "Test" your gateway connection in the Apiman admin UI.

**Comment by nishasumesh** [comment]
This issue is fixed after recreating the gateway url.

**Comment by nishasumesh** [comment]
Now I am trying to install the same in one of my aws ec2 instance. copied the same working directory to ec2 instance. But getting error . 
[log.txt](https://github.com/apiman/apiman/files/5062852/log.txt)

any idea why this error? i wanted to use db instead of elastic search. it was working in my local system also.

**Comment by EricWittmann** [comment]
I don't recommend putting the quickstart installation into the cloud as a production instance, in case that's what you're doing.  We have reasonable documentation about how to set up a production instance here:  https://apiman.gitbooks.io/apiman-production-guide/content/

That said, the error you are getting is because the embedded instance of Elasticsearch that we include in the Quickstart is not starting up quickly enough.  It's likely that the EC2 instance you're using is a bit slow.  Your best option is to install Elasticsearch on a separate EC2 instance and then modify your Apiman configuration properties to point to that instance instead of the embedded one.  We have some documentation on that as well:  https://apiman.gitbooks.io/apiman-installation-guide/content/installation-guide/how-to/elasticsearch.html#_use_standalone_elasticsearch_instance_cluster

**Comment by nishasumesh** [comment]
This my development instance. Problem with elastic search is that, it needs minimum 8gb memory, we have only 2GB or maximum 4GB availability for this installation. In that I cant install elastic search. That is why I thought of using DB instead of ES.

**Comment by EricWittmann** [comment]
Understood - if you want to remove Elasticsearch **entirely** then there are some additional steps.  Coincidentally I'm going to be updating the Quickstart this week to do precisely that (remove ES entirely from the quickstart).  That may help you get where you need to be.

**Comment by EricWittmann** [comment]
But either way - you will need to remove the `apiman-es.war` file from the deployments directory as a good first step.

**Comment by volkflo** [comment]
@nishasumesh Running elasticsearch in a docker container with max 1GB of RAM is totally fine for a dev environment. Even for a production system we a running an elasticsearch instance with about <4GB totally fine.

**Comment by nishasumesh** [comment]
I tried with docker image

sudo docker pull docker.elastic.co/elasticsearch/elasticsearch:5.6.9

sudo docker run -p 9200:9200 -p 9300:9300 -e "discovery.type=single-node" docker.elastic.co/elasticsearch/elasticsearch:5.6.9

Now I have 2GB memory. But I got memory error as shown below.

sudo docker run -p 9200:9200 -p 9300:9300 -e "discovery.type=single-node" docker.elastic.co/elasticsearch/elasticsearch:5.6.9

OpenJDK 64-Bit Server VM warning: If the number of processors is expected to increase from one, then you should configure the number of parallel GC threads appropriately using -XX:ParallelGCThreads=N
OpenJDK 64-Bit Server VM warning: INFO: os::commit_memory(0x0000000085330000, 2060255232, 0) failed; error='Cannot allocate memory' (errno=12)
#
# There is insufficient memory for the Java Runtime Environment to continue.
# Native memory allocation (mmap) failed to map 2060255232 bytes for committing reserved memory.
# An error report file with more information is saved as:
# /usr/share/elasticsearch/hs_err_pid1.log

**Comment by volkflo** [comment]
Okay I see, you have to set the available memory for elasticsearch in the command.
Please try this:
```bash
docker run -p 9200:9200 -p 9300:9300 -e "discovery.type=single-node" -e "ES_JAVA_OPTS=-Xms512m -Xmx512m" docker.elastic.co/elasticsearch/elasticsearch:5.6.9
```
It will also run just with 512MB of memory :)

**Comment by nishasumesh** [comment]
thanks @volkflo , elastic search worked. 

[ec2-user@ip-xxx~]$ sudo docker pull apiman/on-wildfly11:1.5.7.Final
Error response from daemon: manifest for apiman/on-wildfly11:1.5.7.Final not found: manifest unknown: manifest unknown

is the manifest file missing?

**Comment by nishasumesh** [comment]
https://raw.githubusercontent.com/apiman/apiman-deployer/master/deployer.sh

this file .zip files are not unzipping for me :(

**Comment by volkflo** [comment]
I checked on docker hub and it seems the new image is missing:
![image](https://user-images.githubusercontent.com/13332383/90106331-8dd22f00-dd47-11ea-93b2-6443598c1fb0.png)

It seems that @msavy pushed something.
@EricWittmann Can we make the docker release deployments working again?

Also, I am not sure how actual this script really is. We never used it and if I look into commit history there was not much activity in the last years.

**Comment by EricWittmann** [comment]
Yeah it's on my list to get the docker images built again as part of the release process.  Docker Hub used to automatically build them but I can't get that to work anymore.

Also that deployer script is pretty old. :(

**Comment by nishasumesh** [comment]
I have updated that for 1.5.7.final
[deployment.txt](https://github.com/apiman/apiman/files/5069018/deployment.txt)

**Comment by EricWittmann** [comment]
A PR would be very welcome!  :)

**Comment by EricWittmann** [comment]
By the way - the `1.5.7.Final` versions of the docker images are built and pushed:  https://hub.docker.com/layers/apiman/on-wildfly11/1.5.7.Final/images/sha256-f000c48125f23ed3498ed1433eee734999662957a5b22536835571ab4f5e776b?context=explore

**Comment by EricWittmann** [comment]
That will be the last version of the `apiman/on-wildfly10` and `apiman/on-wildfly11` docker images.  Starting with the next version there will be just one docker image for running on wildfly called `apiman/on-wildfly` and it will use Wildfly 20.

**Comment by EricWittmann** [comment]
I've submitted a PR that removes Elasticsearch entirely from the quickstart.  You can find it here:

https://github.com/apiman/apiman/pull/889

Please be aware that we don't have RDBMS versions of some of the components.  So in those cases I reverted them to their in-memory versions.  This is fine unless you try to cluster the quickstart (NOT RECOMMENDED).  So it should be fine, but I wanted to warn everyone.  To be fair, it's no worse than the previous quickstart - that one used Elasticsearch but by default was configured to go against its own embedded version - so that wouldn't work in a cluster either.  Bottom line - don't use the quickstart for production deployments.

**Comment by nishasumesh** [comment]
:thumbsup:

**Comment by volkflo** [comment]
I think we can close this now, if there are further problems please open a new issue or reopen this one :)
