### ISSUE TITLE
Manager's hibernate can't reconnect ?

### ISSUE THREAD

**Issue by gromero-pivops** [apiman/apiman#898]
Hello,
Our 2 Apimans (gateway and manager/ui) are connected to an SQL Proxy which reboots every saturday morning. During that 2 minutes period, both Apimans complains about losing connection to database, and that's a normal behaviour.
Gateways are still working when database is back but Manager/UI continues complaining for hours until I restart it manually. Stack trace looks like below (database is up since 6:02AM):

```
2020-08-29 06:12:52,932 | WARN  | org.hibernate.engine.jdbc.spi.SqlExceptionHelper | default task-5 | SQL Error: 0, SQLState: 08S01
2020-08-29 06:12:52,932 | ERROR | org.hibernate.engine.jdbc.spi.SqlExceptionHelper | default task-5 | Communications link failure

The last packet successfully received from the server was 1,190,459 milliseconds ago.  The last packet sent successfully to the server was 589,668 milliseconds ago.
2020-08-29 06:12:52,933 | ERROR | io.apiman.manager.api.jpa.JpaStorage | default task-5 | org.hibernate.exception.JDBCConnectionException: could not prepare statement: javax.persistence.PersistenceException: org.hibernate.exception.JDBCConnectionException: could not prepare statement
        at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:154)
        at org.hibernate.query.internal.AbstractProducedQuery.list(AbstractProducedQuery.java:1514)
        at org.hibernate.query.Query.getResultList(Query.java:132)
        at org.hibernate.query.criteria.internal.compile.CriteriaQueryTypeQueryAdapter.getResultList(CriteriaQueryTypeQueryAdapter.java:74)
        at io.apiman.manager.api.jpa.JpaStorage.getPermissions(JpaStorage.java:1962)
...
```

My Wildfly JDBC configuration for Apiman Manager has "autoReconnect=true" statement, but it doesn't seem to work well (it does for Gateway).
Is there a way to configure that reconnection?
Thanks for help!
Guillaume

**Comment by gromero-pivops** [comment]
Adding my apiman.properties info:
# ---------------------------------------------------------------------
# Some hibernate settings only useful when JPA is the storage.type.
# ---------------------------------------------------------------------
apiman.hibernate.connection.datasource=java:jboss/datasources/apiman-manager
apiman.hibernate.dialect=io.apiman.manager.api.jpa.ApimanMySQL5Dialect
apiman.hibernate.hbm2ddl.auto=validate
# API Manager storage settings.
apiman-manager.storage.type=jpa
apiman-manager.storage.jpa.initialize=true

**Comment by EricWittmann** [comment]
There are lots of configuration properties you can use in the Datasource file (e.g. `apiman-ds.xml`) that could potentially help.  See this article:

http://www.mastertheboss.com/jboss-server/jboss-datasource/how-to-automatically-reconnect-to-the-database-in-wildfly

**Comment by gromero-pivops** [comment]
I've tested the background validation and it worked perfectly. Thanks !
