### ISSUE TITLE
Running apiman with only MySQL(v5.7.31 or any other latest version ) in production/debug mode

### ISSUE THREAD

**Issue by iamakashk** [apiman/apiman#900]
Hi ,
I am trying to run apiman only with MySQL v5.7.31. I have tried following steps but running into error.
step 1: Mysql v5.7.31 installation 
step 2: Created schema and users for the same ( able to connect mysql from remote machine) 
step 3:  changed /standalone/deployments/apiman-ds.xml file 
step 4: changed /standalone/configuration apiman.properties
step 5: downloaded mysql-connector-java-5.1.33.jar and placed it /standalone/deployments

Following are the configuration files and log file,
[log.txt](https://github.com/apiman/apiman/files/5179519/log.txt)
[apiman.txt](https://github.com/apiman/apiman/files/5179520/apiman.txt)
[apiman-ds.txt](https://github.com/apiman/apiman/files/5179521/apiman-ds.txt)

MySQL information : 
mysql> show databases;
+--------------------+
| Database           |
+--------------------+
| information_schema |
| apiman             |
| keycloak           |
| mysql              |
| performance_schema |
| sys                |
+--------------------+
6 rows in set (0.00 sec)

mysql> 

Is there any way to completely remove Elasticsearch dependency and run  apiman only with MySQL ?

**Comment by bekihm** [comment]
Hello @iamakashk,
I see in your apiman config that the storage type for metrics is still configured for elasticsearch, can you switch there also to jest?
`# API Manager metrics settings.`
`apiman-manager.metrics.type=es`

Regards
Benjamin

**Comment by volkflo** [comment]
I think what @bekihm means is `jpa`?

```
# API Manager metrics settings.
apiman-manager.metrics.type=jpa
```

**Comment by bekihm** [comment]
@volkflo Thanks for the correction.

**Comment by iamakashk** [comment]
@volkflo @bekihm Thanks for the reply.
I just tried changing it. Here are my apiman property file. 
[apiman-properties.txt](https://github.com/apiman/apiman/files/5181378/apiman-properties.txt)

But I am facing following issue,

`11:58:29,830 INFO  [org.hibernate.jpa.internal.util.LogHelper] (default task-10) HHH000204: Processing PersistenceUnitInfo [
	name: apiman-manager-api-jpa
	...]
11:58:29,928 INFO  [org.hibernate.jpa.internal.util.LogHelper] (default task-10) HHH000204: Processing PersistenceUnitInfo [
	name: apiman-manager-api-jpa
	...]
11:58:29,984 ERROR [io.undertow.request] (default task-10) UT005023: Exception handling request to /apiman/users/currentuser/info: org.jboss.resteasy.spi.UnhandledException: java.lang.RuntimeException: Transaction not active.
	at org.jboss.resteasy.core.ExceptionHandler.handleApplicationException(ExceptionHandler.java:77)
	at org.jboss.resteasy.core.ExceptionHandler.handleException(ExceptionHandler.java:220)
	at org.jboss.resteasy.core.SynchronousDispatcher.writeException(SynchronousDispatcher.java:175)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:418)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:209)
	at org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.service(ServletContainerDispatcher.java:221)
	at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:56)
	at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:51)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:85)
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:129)
	at io.apiman.common.servlet.RootResourceFilter.doFilter(RootResourceFilter.java:59)
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
	at io.apiman.manager.api.war.TransactionWatchdogFilter.doFilter(TransactionWatchdogFilter.java:57)
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
	at io.apiman.manager.api.security.impl.DefaultSecurityContextFilter.doFilter(DefaultSecurityContextFilter.java:55)
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
	at io.apiman.common.servlet.DisableCachingFilter.doFilter(DisableCachingFilter.java:52)
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
	at io.apiman.common.servlet.ApimanCorsFilter.doFilter(ApimanCorsFilter.java:71)
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
	at io.apiman.common.servlet.LocaleFilter.doFilter(LocaleFilter.java:61)
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
	at io.undertow.servlet.handlers.FilterHandler.handleRequest(FilterHandler.java:84)
	at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62)
	at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)
	at org.wildfly.extension.undertow.security.SecurityContextAssociationHandler.handleRequest(SecurityContextAssociationHandler.java:78)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at org.keycloak.adapters.undertow.UndertowAuthenticatedActionsHandler.handleRequest(UndertowAuthenticatedActionsHandler.java:66)
	at io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:131)
	at io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57)
	at io.undertow.server.handlers.DisableCacheHandler.handleRequest(DisableCacheHandler.java:33)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.security.handlers.AuthenticationConstraintHandler.handleRequest(AuthenticationConstraintHandler.java:53)
	at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46)
	at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64)
	at io.undertow.servlet.handlers.security.ServletSecurityConstraintHandler.handleRequest(ServletSecurityConstraintHandler.java:59)
	at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60)
	at io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77)
	at io.undertow.security.handlers.NotificationReceiverHandler.handleRequest(NotificationReceiverHandler.java:50)
	at io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at org.wildfly.extension.undertow.security.jacc.JACCContextIdHandler.handleRequest(JACCContextIdHandler.java:61)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at org.keycloak.adapters.undertow.ServletPreAuthActionsHandler.handleRequest(ServletPreAuthActionsHandler.java:69)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:292)
	at io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:81)
	at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:138)
	at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:135)
	at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48)
	at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
	at io.undertow.servlet.api.LegacyThreadSetupActionWrapper$1.call(LegacyThreadSetupActionWrapper.java:44)
	at io.undertow.servlet.api.LegacyThreadSetupActionWrapper$1.call(LegacyThreadSetupActionWrapper.java:44)
	at io.undertow.servlet.api.LegacyThreadSetupActionWrapper$1.call(LegacyThreadSetupActionWrapper.java:44)
	at io.undertow.servlet.api.LegacyThreadSetupActionWrapper$1.call(LegacyThreadSetupActionWrapper.java:44)
	at io.undertow.servlet.api.LegacyThreadSetupActionWrapper$1.call(LegacyThreadSetupActionWrapper.java:44)
	at io.undertow.servlet.api.LegacyThreadSetupActionWrapper$1.call(LegacyThreadSetupActionWrapper.java:44)
	at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:272)
	at io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:81)
	at io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:104)
	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:202)
	at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:805)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:823)
Caused by: java.lang.RuntimeException: Transaction not active.
	at io.apiman.manager.api.jpa.AbstractJpaStorage.rollbackTx(AbstractJpaStorage.java:114)
	at io.apiman.manager.api.jpa.JpaStorage.rollbackTx(JpaStorage.java:147)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.weld.bean.proxy.AbstractBeanInstance.invoke(AbstractBeanInstance.java:38)
	at org.jboss.weld.bean.proxy.ProxyMethodHandler.invoke(ProxyMethodHandler.java:100)
	at io.apiman.manager.api.core.IStorage$816713466$Proxy$_$$_WeldClientProxy.rollbackTx(Unknown Source)
	at io.apiman.manager.api.rest.impl.UserResourceImpl.getUserInternal(UserResourceImpl.java:132)
	at io.apiman.manager.api.rest.impl.UserResourceImpl.getInfo(UserResourceImpl.java:87)
	at io.apiman.manager.api.rest.impl.UserResourceImpl$Proxy$_$$_WeldClientProxy.getInfo(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:139)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:295)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:249)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:236)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:402)
	... 68 more
`

Here is the complete log file,
[log07092020.txt](https://github.com/apiman/apiman/files/5181383/log07092020.txt)

Thanks in advance!☺

**Comment by volkflo** [comment]
Hi @iamakashk,

I am not the MySQL expert, because we using only elasticsearch :)
Can you try to compare you settings with the ones in this file: `distro/wildfly/src/main/resources/overlay/standalone/configuration/apiman.properties` of the current master branch?
And then please change everything `h2` related to `jpa` as you did it before. 

It seems there are some configs missing :)

**Comment by EricWittmann** [comment]
Hey @iamakashk - the Wildfly based quickstart for Apiman 2.0.0 will **not** include Elasticsearch at all anymore.  It will be 100% H2 based.  I know that's not the same as a 100% MySQL config, but it's close.  Here is the `apiman.properties` file:

https://github.com/apiman/apiman/blob/master/distro/wildfly/src/main/resources/overlay/standalone/configuration/apiman.properties

And here you can find the **two** datasource files (you will need both):

https://github.com/apiman/apiman/tree/master/distro/wildfly/src/main/resources/overlay/standalone/deployments

I hope that helps.

**Comment by iamakashk** [comment]
@EricWittmann Thanks for the help. Waiting for apiman 2.0.0 😍. I was able to run apiman with mysql 5.7. I will soon share a document or a youtube video for the same.

**Comment by EricWittmann** [comment]
Should be this week.  Hopefully tomorrow.

**Comment by EricWittmann** [comment]
Release of apiman 2.0.0 is complete!

**Comment by iamakashk** [comment]
Will try it out !!! Excited!!😍
