### ISSUE TITLE
How to bring up Vert.x gateway without Elasticsearch

### ISSUE THREAD

**Issue by james-bostock** [apiman/apiman#920]
Hi,

An earlier issue, #885, asked how to bring up Apiman without Elasticsearch. However, as far as I could see, the responses all dealt with the servlet implementation (more specifically, the distinction between the gateway and manager components was not made).

I would like to deploy the version 1.5.7.Final Vert.x gateway component using JDBC instead of Elasticsearch (recognizing, as pointed out in issue #885, that some components are not available for JDBC - specifically, the cache store, rate limiter and shared store components).

While the installation guide has a [section](https://apiman.gitbooks.io/apiman-installation-guide/content/installation-guide/how-to/jdbc.html) on configuring the gateway to use JDBC, this is for the servlet implementation and it is not immediately obvious how to translate the information to the JSON configuration file used by the Vert.x version of the gateway.

I was hoping that by starting with a largely empty configuration file, running the gateway would tell me what is missing. However, the gateway is not very forgiving:

```
[INFO ] 2020-10-16 03:13:46.583 [vert.x-eventloop-thread-3] HttpGatewayVerticle - Starting verticle: HTTP. UUID: c9b1d67a-1821-4d4e-92f1-254efd83ed74.HTTP.
java.lang.RuntimeException: java.lang.NullPointerException
        at io.apiman.gateway.platforms.vertx3.engine.VertxConfigDrivenEngineFactory.doInstantiate(VertxConfigDrivenEngineFactory.java:66)
        at io.apiman.gateway.engine.impl.ConfigDrivenEngineFactory.create(ConfigDrivenEngineFactory.java:181)
        at io.apiman.gateway.engine.impl.ConfigDrivenEngineFactory.createRegistry(ConfigDrivenEngineFactory.java:99)
        at io.apiman.gateway.engine.impl.AbstractEngineFactory.createEngine(AbstractEngineFactory.java:56)
        at io.apiman.gateway.platforms.vertx3.verticles.ApimanVerticleWithEngine.start(ApimanVerticleWithEngine.java:48)
        at io.apiman.gateway.platforms.vertx3.verticles.HttpGatewayVerticle.start(HttpGatewayVerticle.java:37)
        at io.vertx.core.impl.DeploymentManager.lambda$doDeploy$8(DeploymentManager.java:552)
        at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:320)
        at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:462)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
        at io.apiman.gateway.platforms.vertx3.engine.VertxConfigDrivenEngineFactory.doInstantiate(VertxConfigDrivenEngineFactory.java:62)
        ... 14 more
```

Thanks in advance

**Comment by volkflo** [comment]
Hi @james-bostock,

an empty configuration file will not work.
You have to change the configuration for the gateway similar to the changes in the `apiman.properties` file.
Unfortunately, I think we do not have an example config for this.

Just out of interest: Is there a big reason why not just use elasticsearch?

**Comment by james-bostock** [comment]
Hi @volkflo,

I did not expect an empty configuration section to work, but I hoped that the program, on finding required information missing, might indicate what was missing.

All the configuration examples that I have seen assume that the gateway is running in a Java EE environment and that the database connection will be provided via JNDI. This is true, too, for the Vert.x gateway whose `AbstractJdbcComponent` class looks up the value of the "datasource.jndi-location" property in the JNDI initial context. Where is the JNDI provider in the Vert.x implementation of the gateway? How does one configure the data source?

The reason for not wanting to use Elasticsearch is that APIMAN 1.5.7 only supports Elasticsearch 5.6.x which is end of life. The reason for not wanting to jump to 2.0.0 is a concern that it is not mature enough, having been released last month and being a *.0.0 version. If we cannot get the Vert.x gateway to work with JDBC, we plan to use the servlet gateway.

Many thanks

**Comment by volkflo** [comment]
I think for the vert.x part @msavy is the expert, maybe he can help :)

For the es-part I am happy that you share your opinion on that.
I hope we can release soon a 2.1.X release of apiman. Including all know bug fixes for elasticsearch and also the new developer portal. On our test system, we run ES7 for over a half of a year without any problems :) 
Would be nice if you could try out the 2.0.0 (maybe only on a test-system) and report bugs if you find some :)

**Comment by msavy** [comment]
I'll try to get back to you guys this weekend. Things are hectic at the moment.

**Comment by james-bostock** [comment]
Hi @msavy,

We have decided to go with Elasticsearch 5 as, even though it is end of life, it is the version used/provided by OpenShift 3.11 which we use. I would still welcome your thoughts on using the Vert.x gateway with JDBC instead of Elasticsearch but there is no urgency.

Thanks!

**Comment by bekihm** [comment]
@james-bostock If you decide at some future point to go with elasticsearch 7 you can easily switch to apiman 2.x version with a complete export of your apiman data via apiman manager. :-)
