### ISSUE TITLE
Unable to create organization using java

### ISSUE THREAD

**Issue by iamakashk** [apiman/apiman#937]
Hi I am trying to create a organization using java program but I am getting 401 error for some reason. I am sure about the username and password. I am able to login in apiman using those credentials and create organization using apiman. But when I do that with java program I am getting 401. 

`@Path("registerOrg")
public class RegisterOrganization {
	
	private static HttpURLConnection con;
	
    @POST
    @Produces(MediaType.TEXT_PLAIN)
	public String registerOrganization(String JSONObject) {
    	
		BaseResponse<RegisteredUser> baseResponse = new BaseResponse<RegisteredUser>();
		Response response = new Response();

		BaseRequest baseRequest = null;
		baseRequest = new BaseRequest();
		Gson gson = new Gson();
		baseRequest = gson.fromJson(JSONObject, baseRequest.getClass());
		
    	
    	
    	
    	
		String url ="http://IP_ADDRESS:8080/auth/realms/apiman/protocol/openid-connect/token";
		String urlParameters ="grant_type=password&username=my_username&password=my_password&client_id=apimanui";
		byte[] postData = urlParameters.getBytes(StandardCharsets.UTF_8);
		
    	try {

			URL myurl = new URL(url);
			con = (HttpURLConnection) myurl.openConnection();

			con.setDoOutput(true);
			con.setRequestMethod("POST");
			con.setRequestProperty("User-Agent", "Java client");
			con.setRequestProperty("Content-Type", "application/x-www-form-urlencoded");

			try (DataOutputStream wr = new DataOutputStream(con.getOutputStream())) {

				wr.write(postData);
			}

			StringBuilder content;

			try (BufferedReader br = new BufferedReader(new InputStreamReader(con.getInputStream()))) {

				String line;
				content = new StringBuilder();

				while ((line = br.readLine()) != null) {
					content.append(line);
					content.append(System.lineSeparator());
				}
			}

			System.out.println(content.toString());
			Token token = new Gson().fromJson(content.toString(), Token.class);
			register(token.getAccess_token());
    	}catch(Exception ex) {
    		ex.printStackTrace();
    	}
		return "register organization";
	}
    
    public static void register(String accessToken) throws IOException {
    	boolean hasUserRoleSet = false;
    	ApimanOrganization organization = new ApimanOrganization();
    	organization.setDescription("This is demo organization");
    	organization.setName("organization demo");
		System.out.println(organization.toString());
		String json = new Gson().toJson(organization);
		String url = "http://APIMAN_IP_ADDRESS:8080/apiman/organizations";
		byte[] postData = json.getBytes(StandardCharsets.UTF_8);
		
		try {
			URL myurl = new URL(url);
			con = (HttpURLConnection) myurl.openConnection();

			con.setDoOutput(true);
			con.setRequestMethod("POST");
			con.setRequestProperty("Content-Type", "application/json");
			con.setRequestProperty("User-Agent", "Java client");
			con.setRequestProperty("Accept", "*/*");
			con.addRequestProperty("Authorization", "Bearer " + accessToken);

			try (DataOutputStream wr = new DataOutputStream(con.getOutputStream())) {

				wr.write(postData);
			}

			StringBuilder content;

			try (BufferedReader br = new BufferedReader(new InputStreamReader(con.getInputStream()))) {

				String line;
				content = new StringBuilder();

				while ((line = br.readLine()) != null) {
					content.append(line);
					content.append(System.lineSeparator());
				}
			}

			int responseCode = con.getResponseCode();

		} finally {

			con.disconnect();
		}
    }

}
`

Following is the error which I am facing with above code: 
`java.io.IOException: Server returned HTTP response code: 401 for URL: http://APIMAN_IP_ADDRESS:8080/apiman/organizations
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1900)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1498)
	at com.etp.hubana.serviceManagementRegistration.RegisterOrganization.register(RegisterOrganization.java:122)
	at com.etp.hubana.serviceManagementRegistration.RegisterOrganization.registerOrganization(RegisterOrganization.java:82)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:143)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:160)
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$TypeOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:203)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:97)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102)
	at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:303)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317)
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:286)
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1072)
	at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:399)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:381)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:344)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:221)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:690)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:373)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1589)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:823)`

**Comment by EricWittmann** [comment]
The reason is that I don't believe the Apiman API (by default) supports BASIC auth.  As I recall, the API is protected by Keycloak bearer token. The way the UI works is that a standard web-based/interactive OAuth flow is used to authenticate the user (i.e. the login page).  This results in an OAuth token being granted for the session to that user.  The UI uses this token to make authenticated calls.

So you have two options I think.  The first is to implement something like OAuth Client Credentials flow in your Java application, which is a way to turn the user/pass (presumably for a service account) into an OAuth token.  You then use that token to make your calls to Apiman.  For example, this is how you can get a token using CURL:  https://stackoverflow.com/questions/50256433/obtaining-an-access-token-via-curl

The other option is to see if you can enable BASIC auth support in the Keycloak adapter that is being used to protect the Apiman API.

The former approach (client credentials flow) is preferred.  And actually I don't know if the latter approach is possible, or if it is how to do it.

For all of this I recommend the Keycloak documentation for more information.

**Comment by tevosouza** [comment]
Did you tried [apiman/apiman-cli](https://github.com/apiman/apiman-cli#manage-organisations) maybe it can do it.
