### ISSUE TITLE
Use of apiman.hibernate.hbm2ddl.auto=update versus import/export

### ISSUE THREAD

**Issue by james-bostock** [apiman/apiman#938]
Hi,

We are upgrading from a snapshot of version 1.5.3 to 1.5.7.Final. The database schema changed between these versions causing the 1.5.7.Final instance to fail to start properly when deployed:
```
Caused by: org.hibernate.tool.schema.spi.SchemaManagementException: Schema-validation: missing column [definition_url] in table [api_versions]
        at org.hibernate.tool.schema.internal.AbstractSchemaValidator.validateTable(AbstractSchemaValidator.java:136)
        at org.hibernate.tool.schema.internal.GroupedSchemaValidatorImpl.validateTables(GroupedSchemaValidatorImpl.java:42)
        at org.hibernate.tool.schema.internal.AbstractSchemaValidator.performValidation(AbstractSchemaValidator.java:89)
        at org.hibernate.tool.schema.internal.AbstractSchemaValidator.doValidation(AbstractSchemaValidator.java:68)
        at org.hibernate.tool.schema.spi.SchemaManagementToolCoordinator.performDatabaseAction(SchemaManagementToolCoordinator.java:184)
        at org.hibernate.tool.schema.spi.SchemaManagementToolCoordinator.process(SchemaManagementToolCoordinator.java:65)
        at org.hibernate.internal.SessionFactoryImpl.<init>(SessionFactoryImpl.java:476)
        at org.hibernate.boot.internal.SessionFactoryBuilderImpl.build(SessionFactoryBuilderImpl.java:422)
        at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.build(EntityManagerFactoryBuilderImpl.java:880)
        ... 108 more
```

The default setting of the `apiman.hibernate.hbm2ddl.auto` in the `apiman.properties` file is `validate` and the [Apiman documentation](https://apiman.gitbooks.io/apiman-installation-guide/content/installation-guide/manager/backup-migration.html#_backup_migration) recommends version upgrades be handled via an export followed by an import.

However, I have seen in several Apiman GitHub issues people reporting having `apiman.hibernate.hbm2ddl.auto` set to `update` without this being commented on (even in the case of issue #489, where reported that it behaved in a thoroughly unexpected way). So, beyond the fact that some internet pages recommend against setting this property to `update`, in the context of Apiman, are there any reasons why we should not set it this way?

Thanks in advance

**Comment by EricWittmann** [comment]
I think as long as you backup your database before upgrading, it's a reasonably safe thing to do (setting that hibernate property to `update`).  Of course please make sure you backup the DB prior to upgrading just in case!
