### ISSUE TITLE
Vert.x gateway seems not to respect the publicEndpoint property.

### ISSUE THREAD

**Issue by james-bostock** [apiman/apiman#939]
Hi,

This is almost certainly a case of user error but I cannot see where I am going wrong. The desired result is that clients be able to reach the managed APIs at https://optima-apiman-gateway:8443/apiman-gateway/Optima/<api> (as opposed to the default of https://optima-apiman-gateway:8443/Optima/<api>) ("Optima" is the organization name).

In the gateway configuration file, I have configured a top-level "publicEndpoint" property:

```
  "hostname": "optima-apiman-gateway",

  "publicEndpoint": "https://optima-apiman-gateway:8443/apiman-gateway",

  "verticles": {
    "http": {
      "port": 8082,
      "count": 0
    },
    "https": {
      "port": 8443,
      "count": "auto"
    },
    "api": {
      "port": 8081,
      "count": 1
    }
  },
```

However, this seems to be being ignored as, when I try to access an API with the "apiman-gateway" path component, I get a 404 response and see the following in the gateway log:

```
** ERROR: API not found. **
io.apiman.gateway.engine.beans.exceptions.ApiNotFoundException: API not found.
        at io.apiman.gateway.engine.impl.ApiRequestExecutorImpl.execute(ApiRequestExecutorImpl.java:350)
        at io.apiman.gateway.platforms.vertx3.http.HttpPolicyAdapter._execute(HttpPolicyAdapter.java:112)
        at io.apiman.gateway.platforms.vertx3.http.HttpPolicyAdapter.execute(HttpPolicyAdapter.java:61)
        at io.apiman.gateway.platforms.vertx3.verticles.HttpsGatewayVerticle.requestHandler(HttpsGatewayVerticle.java:74)
```

When I try to access the same API without the "apiman-gateway" path element, it is found and the request routed to the implementing API.

If I look at the API in the manager UI, it reports the managed endpoint correctly (i.e. with the "apiman-gateway" path component).

Is there a configuration step that I have missed?

Thanks in advance.

**Comment by msavy** [comment]
It's a fair while since I wrote this and last looked at it. I'll try to have a look shortly and get back to you.

**Comment by volkflo** [comment]
If I remember this correctly this is only for the UI if you have a complex setup and not just expose the port and hostname.
Maybe this blog from Marc is helpful here: https://www.apiman.io/blog/apiman/gateway/manager/plugin/extensibility/2018/07/03/custom-url-parser.html

**Comment by james-bostock** [comment]
Sorry for taking so long to respond. From the blog post, it seems fairly simple to support custom paths. However, if the publicEndpoint property is only for the UI, what purpose does it serve?

I have changed jobs and am no longer working with Apiman. I would like to thank @volkflo, @msavy and @EricWittmann for being incredibly helpful with my numerous queries. Thanks guys!

**Comment by EricWittmann** [comment]
So I think the answer here is that `publicEdnpoint` is used when you have a configuration where the gateway is located (for example) behind some sort of load balancer or router that is changing the *context* of the gateway application.  In other words, imagine running the gateway on your local machine so you could access it at `http://localhost:8881/`, but then you install nginx and run that (with proper SSL config) at `https://localhost/` - and you set up a route that maps the `/apiman-gateway` nginx context to `localhost:8881`.  This would allow you to access the Apiman gateway at `https://localhost/apiman-gateway` and all would be great!

However, the Gateway itself would think it was located at `http://localhost:8881/` and that's what it would report to the UI.  So the URL in the UI would be wrong, because neither party knows anything about nginx.  So that's when you set `publicEndpoint` to `https://localhost/apiman-gateway`.

So I **think** the real question you're asking is this:  how do I configure the Gateway to **actually run** on that `/apiman-gateway` subcontext.  For Vert.x I'm not sure offhand (would need to Google how to do it for a Vert.x application).  If you were deploying the Wildfly version, then there is a XML config file contained within the application WAR file that can be changed.

I'm sure there is a way to do it for Vert.x, but I don't know offhand what it is.

But in any case, the `publicEndpoint` feature doesn't change how Vert.x runs the app - it just changes how the Gateway reports itself to the UI layer, in cases where there is some other routing layer (load balancer, kubernetes, etc) at play.

**Comment by EricWittmann** [comment]
@james-bostock  Also, congrats on the new job, and you're welcome. :) :)

**Comment by ncasaux** [comment]
Hello!

> So I **think** the real question you're asking is this: how do I configure the Gateway to **actually run** on that `/apiman-gateway` subcontext. For Vert.x I'm not sure offhand (would need to Google how to do it for a Vert.x application). If you were deploying the Wildfly version, then there is a XML config file contained within the application WAR file that can be changed.

I think I'm facing the same issue with a Vert.x gateway, and I can't really find how I could tell the gateway that it's actually exposed under some subcontext (and not just "/").

Any chance you guys know where I could set this ?

Thanks in advance!
