### ISSUE TITLE
Apiman 1.5.7.Final Vert.x gateway and HTTP/2 - 

### ISSUE THREAD

**Issue by james-bostock** [apiman/apiman#941]
Hi,

I am trying to get the Apiman 1.5.7.Final Vert.x gateway to handle HTTP/2 requests. I am using Java 1.8.0u131 so, to get ALPN working, I am using jetty-alpn-agent and netty-tcnative. Using **curl** to send a request, I see that HTTP/2 is being used:
```
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
```
However, something is going wrong when Apiman invokes the API implementation. I am seeing two different exceptions. The first is:
```
[DEBUG] 2020-12-04 03:20:32.310 [vert.x-eventloop-thread-2] HttpConnector - Connecting to optima-esb-productcatalogms | ssl?: true port: 8,017 verb: GET path: /rest/v1/billdispatchformats
** ERROR: a header name cannot contain the following prohibited characters: =,;: \t\r\n\v\f: :path **
java.lang.IllegalArgumentException: a header name cannot contain the following prohibited characters: =,;: \t\r\n\v\f: :path
        at io.vertx.core.http.impl.HttpUtils.validateHeaderName(HttpUtils.java:759)
        at io.vertx.core.http.impl.HttpUtils.validateHeader(HttpUtils.java:672)
        at io.vertx.core.http.impl.headers.VertxHttpHeaders.add0(VertxHttpHeaders.java:522)
        at io.vertx.core.http.impl.headers.VertxHttpHeaders.add(VertxHttpHeaders.java:68)
        at io.vertx.core.http.impl.headers.VertxHttpHeaders.add(VertxHttpHeaders.java:84)
        at io.vertx.core.http.impl.headers.VertxHttpHeaders.add(VertxHttpHeaders.java:40)
        at io.apiman.gateway.platforms.vertx3.connector.HttpConnector.lambda$connect$3(HttpConnector.java:199)
        at java.lang.Iterable.forEach(Iterable.java:75)
        at io.apiman.gateway.platforms.vertx3.connector.HttpConnector.connect(HttpConnector.java:197)
        at io.apiman.gateway.platforms.vertx3.connector.ConnectorFactory.lambda$createConnector$1(ConnectorFactory.java:101)
        at io.apiman.gateway.engine.impl.ApiRequestExecutorImpl.lambda$null$4(ApiRequestExecutorImpl.java:284)
        at io.apiman.gateway.engine.policy.Chain.handleHead(Chain.java:238)
        at io.apiman.gateway.engine.policy.Chain.doApply(Chain.java:152)
        at com.amdocs.bl.apiman.usage_monitor_policy.UsageMonitorPolicy$1.handle(UsageMonitorPolicy.java:105)
```
The second is:
```
[ERROR] 2020-12-04 03:20:32.378 [vert.x-eventloop-thread-2] ContextImpl - Unhandled exception
java.lang.IllegalStateException: Header already sent
        at io.vertx.core.http.impl.Http2ServerResponseImpl.checkHeadWritten(Http2ServerResponseImpl.java:149) ~[apiman-gateway.jar:?]
        at io.vertx.core.http.impl.Http2ServerResponseImpl.setChunked(Http2ServerResponseImpl.java:205) ~[apiman-gateway.jar:?]
        at io.apiman.gateway.platforms.vertx3.http.HttpPolicyAdapter.handleError(HttpPolicyAdapter.java:137) ~[apiman-gateway.jar:?]
        at io.apiman.gateway.platforms.vertx3.http.HttpPolicyAdapter.lambda$_execute$0(HttpPolicyAdapter.java:78) ~[apiman-gateway.jar:?]
        at io.vertx.core.http.impl.Http2ServerRequestImpl.notifyException(Http2ServerRequestImpl.java:133) ~[apiman-gateway.jar:?]
        at io.vertx.core.http.impl.Http2ServerRequestImpl.handleException(Http2ServerRequestImpl.java:118) ~[apiman-gateway.jar:?]
        at io.vertx.core.http.impl.Http2ConnectionBase.lambda$onConnectionError$0(Http2ConnectionBase.java:135) ~[apiman-gateway.jar:?]
        at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:320) ~[apiman-gateway.jar:?]
        at io.vertx.core.impl.EventLoopContext.execute(EventLoopContext.java:43) ~[apiman-gateway.jar:?]
        at io.vertx.core.impl.ContextImpl.executeFromIO(ContextImpl.java:188) ~[apiman-gateway.jar:?]
        at io.vertx.core.impl.ContextImpl.executeFromIO(ContextImpl.java:180) ~[apiman-gateway.jar:?]
        at io.vertx.core.http.impl.Http2ConnectionBase.onConnectionError(Http2ConnectionBase.java:135) ~[apiman-gateway.jar:?]
        at io.vertx.core.http.impl.VertxHttp2ConnectionHandler.lambda$onConnectionError$2(VertxHttp2ConnectionHandler.java:134) ~[apiman-gateway.jar:?]
        at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:320) ~[apiman-gateway.jar:?]
        at io.vertx.core.impl.EventLoopContext.execute(EventLoopContext.java:43) ~[apiman-gateway.jar:?]
        at io.vertx.core.impl.ContextImpl.executeFromIO(ContextImpl.java:188) ~[apiman-gateway.jar:?]
        at io.vertx.core.impl.ContextImpl.executeFromIO(ContextImpl.java:180) ~[apiman-gateway.jar:?]
        at io.vertx.core.http.impl.VertxHttp2ConnectionHandler.onConnectionError(VertxHttp2ConnectionHandler.java:133) ~[apiman-gateway.jar:?]
        at io.netty.handler.codec.http2.Http2ConnectionHandler.onError(Http2ConnectionHandler.java:617) ~[apiman-gateway.jar:?]
        at io.netty.handler.codec.http2.DefaultHttp2ConnectionEncoder.writeHeaders(DefaultHttp2ConnectionEncoder.java:234) ~[apiman-gateway.jar:?]
        at io.vertx.core.http.impl.VertxHttp2ConnectionHandler._writeHeaders(VertxHttp2ConnectionHandler.java:207) ~[apiman-gateway.jar:?]
        at io.vertx.core.http.impl.VertxHttp2ConnectionHandler.writeHeaders(VertxHttp2ConnectionHandler.java:198) ~[apiman-gateway.jar:?]
        at io.vertx.core.http.impl.VertxHttp2Stream.writeHeaders(VertxHttp2Stream.java:131) ~[apiman-gateway.jar:?]
        at io.vertx.core.http.impl.Http2ServerResponseImpl.checkSendHeaders(Http2ServerResponseImpl.java:428) ~[apiman-gateway.jar:?]
        at io.vertx.core.http.impl.Http2ServerResponseImpl.write(Http2ServerResponseImpl.java:456) ~[apiman-gateway.jar:?]
        at io.vertx.core.http.impl.Http2ServerResponseImpl.end(Http2ServerResponseImpl.java:401) ~[apiman-gateway.jar:?]
        at io.vertx.core.http.impl.Http2ServerResponseImpl.end(Http2ServerResponseImpl.java:375) ~[apiman-gateway.jar:?]
        at io.vertx.core.http.impl.Http2ServerResponseImpl.end(Http2ServerResponseImpl.java:365) ~[apiman-gateway.jar:?]
        at io.apiman.gateway.platforms.vertx3.http.HttpPolicyAdapter$1.write(HttpPolicyAdapter.java:143) ~[apiman-gateway.jar:?]
        at io.apiman.gateway.engine.impl.DefaultPolicyErrorWriter.write(DefaultPolicyErrorWriter.java:96) ~[apiman-gateway.jar:?]
        at io.apiman.gateway.platforms.vertx3.http.HttpPolicyAdapter.handleError(HttpPolicyAdapter.java:138) ~[apiman-gateway.jar:?]
        at io.apiman.gateway.platforms.vertx3.http.HttpPolicyAdapter.lambda$_execute$1(HttpPolicyAdapter.java:87) ~[apiman-gateway.jar:?]
        at io.apiman.gateway.engine.impl.ApiRequestExecutorImpl.lambda$wrapResultHandler$0(ApiRequestExecutorImpl.java:190) ~[apiman-gateway.jar:?]
        at io.apiman.gateway.engine.impl.ApiRequestExecutorImpl.lambda$createPolicyErrorHandler$19(ApiRequestExecutorImpl.java:866) ~[apiman-gateway.jar:?]
        at io.apiman.gateway.engine.policy.Chain.throwError(Chain.java:282) ~[apiman-gateway.jar:?]
        at io.apiman.gateway.engine.policy.Chain.doApply(Chain.java:155) ~[apiman-gateway.jar:?]
        at com.amdocs.bl.apiman.usage_monitor_policy.UsageMonitorPolicy$1.handle(UsageMonitorPolicy.java:105) ~[?:?]
```
In both cases, I have truncated the stack traces at the last call from my code (which is the same in both stacktraces) which is where the last of my plugins invokes the chains's `doApply` method:
```
                        chain.doApply(request);
```
I have attached the full stack traces: [apiman-http2.log](https://github.com/apiman/apiman/files/5640474/apiman-http2.log).

The server that implements the API supports HTTP/2 and, if I send the request to it directly, I get the expected response.

I made a naive modification to the `io.apiman.gateway.platforms.vertx3.connector.HttpConnector` class to skip the adding of headers beginning with a colon:
```
        apiRequest.getHeaders()
            .forEach(e -> {
                if (!connectorConfig.getSuppressedRequestHeaders().contains(e.getKey())) {
                    if (e.getKey().startsWith(":")) {
                        logger.debug("Skipping header: name: {0}, value: {1}", e.getKey(), e.getValue());
                    } else {
                        logger.debug("Adding header: name: {0}, value: {1}", e.getKey(), e.getValue());
                        clientRequest.headers().add(e.getKey(), e.getValue());
                    }
                }
            });
```
With this change, the exceptions disappear, but I still get no response. In this case, I see the following in the gateway log:
```
[DEBUG] 2020-12-04 04:09:12.125 [vert.x-eventloop-thread-3] HttpConnector - Connecting to optima-esb-productcatalogms | ssl?: true port: 8,017 verb: GET path: /rest/v1/billdispatchformats
[DEBUG] 2020-12-04 04:09:12.135 [vert.x-eventloop-thread-3] HttpConnector - Adding header: name: user-agent, value: curl/7.73.0
[DEBUG] 2020-12-04 04:09:12.135 [vert.x-eventloop-thread-3] HttpConnector - Adding header: name: user-id, value: beafe11b-d06b-4206-a8a0-5841f21104d5
[DEBUG] 2020-12-04 04:09:12.136 [vert.x-eventloop-thread-3] HttpConnector - Skipping header: name: :path, value: /Optima/billdispatchformats/1.0
[DEBUG] 2020-12-04 04:09:12.136 [vert.x-eventloop-thread-3] HttpConnector - Adding header: name: Content-Type, value: application/json
[DEBUG] 2020-12-04 04:09:12.136 [vert.x-eventloop-thread-3] HttpConnector - Skipping header: name: :authority, value: optima-apiman-gateway:9443
[DEBUG] 2020-12-04 04:09:12.136 [vert.x-eventloop-thread-3] HttpConnector - Skipping header: name: :method, value: GET
[DEBUG] 2020-12-04 04:09:12.136 [vert.x-eventloop-thread-3] HttpConnector - Adding header: name: authorization, value: Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwi...
[DEBUG] 2020-12-04 04:09:12.137 [vert.x-eventloop-thread-3] HttpConnector - Adding header: name: accept, value: */*
[DEBUG] 2020-12-04 04:09:12.137 [vert.x-eventloop-thread-3] HttpConnector - Adding header: name: user-roles, value: "MANAGER_PARTNER_POS_AGENT",...
[DEBUG] 2020-12-04 04:09:12.137 [vert.x-eventloop-thread-3] HttpConnector - Adding header: name: TenantId, value: 2
[DEBUG] 2020-12-04 04:09:12.137 [vert.x-eventloop-thread-3] HttpConnector - Skipping header: name: :scheme, value: https
[jetty-alpn-agent][debug] Replacing: sun/security/ssl/ClientHandshaker$2
[DEBUG] 2020-12-04 04:09:16.654 [vert.x-eventloop-thread-3] HttpConnector - Resuming
[ERROR] 2020-12-04 04:09:16.664 [vert.x-eventloop-thread-3] ConnectionBase - io.netty.handler.codec.http.HttpStatusClass.valueOf(Ljava/lang/CharSequence;)Lio/netty/handler/codec/http/HttpStatusClass;
[INFO ] 2020-12-04 04:09:16.680 [ESMetricsConsumer] AbstractJestClient - Setting server pool to a list of 1 servers: [http://optima-elasticsearch:9200]
[INFO ] 2020-12-04 04:09:16.680 [ESMetricsConsumer] JestClientFactory - Using multi thread/connection supporting pooling connection manager
[INFO ] 2020-12-04 04:09:16.682 [ESMetricsConsumer] JestClientFactory - Using default GSON instance
[INFO ] 2020-12-04 04:09:16.682 [ESMetricsConsumer] JestClientFactory - Node Discovery disabled...
[INFO ] 2020-12-04 04:09:16.682 [ESMetricsConsumer] JestClientFactory - Idle connection reaping enabled...
[ERROR] 2020-12-04 04:09:16.685 [vert.x-eventloop-thread-3] ConnectionBase - SSLEngine closed already
[INFO ] 2020-12-04 04:09:16.686 [ESMetricsConsumer] JestClientFactory - Authentication cache set for preemptive authentication
```
On the client side, I see:
```
* Connection state changed (MAX_CONCURRENT_STREAMS == 100)!
* Empty reply from server
* Closing connection 0
* TLSv1.2 (OUT), TLS alert, close notify (256):
curl: (52) Empty reply from server
```

Enabling debug logging for Vert.x sheds more light on the first `ConnectionBase` error:
```
[ERROR] 2020-12-04 04:35:51.674 [vert.x-eventloop-thread-3] ConnectionBase - io.netty.handler.codec.http.HttpStatusClass.valueOf(Ljava/lang/CharSequence;)Lio/netty/handler/codec/http/HttpStatusClass;
java.lang.NoSuchMethodError: io.netty.handler.codec.http.HttpStatusClass.valueOf(Ljava/lang/CharSequence;)Lio/netty/handler/codec/http/HttpStatusClass;
        at io.netty.handler.codec.http2.DefaultHttp2ConnectionEncoder.validateHeadersSentState(DefaultHttp2ConnectionEncoder.java:151) ~[apiman-gateway.jar:?]
        at io.netty.handler.codec.http2.DefaultHttp2ConnectionEncoder.writeHeaders(DefaultHttp2ConnectionEncoder.java:193) ~[apiman-gateway.jar:?]
        at io.vertx.core.http.impl.VertxHttp2ConnectionHandler._writeHeaders(VertxHttp2ConnectionHandler.java:207) ~[apiman-gateway.jar:?]
        at io.vertx.core.http.impl.VertxHttp2ConnectionHandler.writeHeaders(VertxHttp2ConnectionHandler.java:198) ~[apiman-gateway.jar:?]
        at io.vertx.core.http.impl.VertxHttp2Stream.writeHeaders(VertxHttp2Stream.java:131) ~[apiman-gateway.jar:?]
        at io.vertx.core.http.impl.Http2ServerResponseImpl.checkSendHeaders(Http2ServerResponseImpl.java:428) ~[apiman-gateway.jar:?]
        at io.vertx.core.http.impl.Http2ServerResponseImpl.write(Http2ServerResponseImpl.java:456) ~[apiman-gateway.jar:?]
        at io.vertx.core.http.impl.Http2ServerResponseImpl.write(Http2ServerResponseImpl.java:359) ~[apiman-gateway.jar:?]
        at io.vertx.core.http.impl.Http2ServerResponseImpl.write(Http2ServerResponseImpl.java:345) ~[apiman-gateway.jar:?]
        at io.apiman.gateway.platforms.vertx3.http.HttpPolicyAdapter.lambda$handleEngineResult$6(HttpPolicyAdapter.java:126) ~[apiman-gateway.jar:?]
        at io.apiman.gateway.engine.io.AbstractStream.write(AbstractStream.java:72) ~[apiman-gateway.jar:?]
        at io.apiman.gateway.engine.impl.ApiRequestExecutorImpl.lambda$null$8(ApiRequestExecutorImpl.java:712) ~[apiman-gateway.jar:?]
        at io.apiman.gateway.engine.io.AbstractStream.handleBody(AbstractStream.java:107) ~[apiman-gateway.jar:?]
        at io.apiman.gateway.engine.policy.Chain.access$000(Chain.java:48) ~[apiman-gateway.jar:?]
        at io.apiman.gateway.engine.policy.Chain$3.handle(Chain.java:122) ~[apiman-gateway.jar:?]
        at io.apiman.gateway.engine.policy.Chain$3.handle(Chain.java:118) ~[apiman-gateway.jar:?]
        at io.apiman.gateway.engine.io.AbstractStream.write(AbstractStream.java:72) ~[apiman-gateway.jar:?]
        at io.apiman.gateway.engine.policies.rewrite.URLRewritingStream.processBuffer(URLRewritingStream.java:150) ~[apiman-gateway.jar:?]
        at io.apiman.gateway.engine.policies.rewrite.URLRewritingStream.write(URLRewritingStream.java:84) ~[apiman-gateway.jar:?]
        at io.apiman.gateway.engine.policy.Chain.write(Chain.java:206) ~[apiman-gateway.jar:?]
        at io.apiman.gateway.engine.impl.ApiRequestExecutorImpl.lambda$null$11(ApiRequestExecutorImpl.java:726) ~[apiman-gateway.jar:?]
        at io.apiman.gateway.platforms.vertx3.connector.HttpConnector.lambda$null$0(HttpConnector.java:173) ~[classes/:?]
        at io.vertx.core.http.impl.HttpClientResponseImpl.handleChunk(HttpClientResponseImpl.java:233) ~[apiman-gateway.jar:?]
```
But not on the second:
```
[ERROR] 2020-12-04 04:35:51.705 [vert.x-eventloop-thread-3] ConnectionBase - SSLEngine closed already
javax.net.ssl.SSLException: SSLEngine closed already
        at io.netty.handler.ssl.SslHandler.wrap(...)(Unknown Source) ~[apiman-gateway.jar:?]
```
Any help with this would be much appreciated.

Thanks in advance.

**Comment by james-bostock** [comment]
Looking at the [release notes for Vert.x 3.7.1](https://github.com/vert-x3/wiki/wiki/3.7.1-Release-Notes), I see [this item](https://github.com/eclipse-vertx/vert.x/issues/2941) (*Do not expose HTTP/2 pseudo headers in header maps*), which might be related to my problem. If I use this version, and undo my modification, I get the same result (i.e. the `java.lang.NoSuchMethodError` error).

**Comment by james-bostock** [comment]
Upgrading netty to version 4.0.34 (the version used by Vert.x 3.7.1) seems to solve the problem: I now get the expected response from the API and no errors in the log.

I suspect that asking for an Apiman version 1.5.8 with an updated Vert.x dependency might be asking too much :-)?

**Comment by james-bostock** [comment]
I hope it wasn't presumptuous of me to close the issue.

**Comment by msavy** [comment]
This used to work, so it's likely a regression based upon versions shifting around.

Which version of Java are you using?

**Comment by msavy** [comment]
There are some complications with Java 8 and HTTP/2, but the Vert.x has some smart solutions to this and I'm not sure if you need to use APLN Boot any more even. Some of this will be swept up when we move support to newer Java (when I get time to finish that task!). 

https://www.rhymewithgravy.com/2016/08/21/Setting-up-Vertx-HTT-P-with-JKS.html

**Comment by james-bostock** [comment]
I am using Java 1.8.0u131 which predates the backporting of the Java 9 ALPN stuff. If I were to move to 1.8.0u252 or later, I think that I could drop the Jetty ALPN boot.

Vert.x 3.7.0 uses Netty 4.1.30.Final whose [JettyAlpnSslEngine](https://github.com/netty/netty/blob/netty-4.1.30.Final/handler/src/main/java/io/netty/handler/ssl/JettyAlpnSslEngine.java) class has a check for ALPN support that checks the Java version: if it is 8 or less, then it assumes ALPN is not supported (this was what prompted my use of netty-tcnative).

Fortunately, Apiman's check for ALPN support does not check the Java version :-).
