### ISSUE TITLE
A lot of java.io.IOException: UT010029: Stream is closed after redeploying apiman

### ISSUE THREAD

**Issue by nowitzkihuang** [apiman/apiman#949]
I built up apiman 1.5.1 as Docker image and after redeploying the image, I got a lot of java.io.IOException: UT010029: Stream is closed, then the apigateway blocked and stop service. Can anyone help me solve the problem? the apiman serves a lot of traffics everyday. It is an api platform for us.

2020-12-21 08:27:56,286 ERROR [stderr] (default task-13) java.io.IOException: UT010029: Stream is closed
2020-12-21 08:27:56,287 ERROR [stderr] (default task-13) 	at io.undertow.servlet.spec.ServletOutputStreamImpl.write(ServletOutputStreamImpl.java:133)
2020-12-21 08:27:56,287 ERROR [stderr] (default task-13) 	at io.undertow.servlet.spec.ServletOutputStreamImpl.write(ServletOutputStreamImpl.java:125)
2020-12-21 08:27:56,287 ERROR [stderr] (default task-13) 	at io.apiman.gateway.platforms.servlet.GatewayServlet$5.write(GatewayServlet.java:364)
2020-12-21 08:27:56,287 ERROR [stderr] (default task-13) 	at io.apiman.gateway.platforms.servlet.GatewayServlet$5.write(GatewayServlet.java:353)
2020-12-21 08:27:56,287 ERROR [stderr] (default task-13) 	at io.apiman.gateway.engine.impl.DefaultPolicyErrorWriter.write(DefaultPolicyErrorWriter.java:92)
2020-12-21 08:27:56,287 ERROR [stderr] (default task-13) 	at io.apiman.gateway.platforms.servlet.GatewayServlet.writeError(GatewayServlet.java:350)
2020-12-21 08:27:56,287 ERROR [stderr] (default task-13) 	at io.apiman.gateway.platforms.servlet.GatewayServlet$1.handle(GatewayServlet.java:156)
2020-12-21 08:27:56,287 ERROR [stderr] (default task-13) 	at io.apiman.gateway.platforms.servlet.GatewayServlet$1.handle(GatewayServlet.java:103)
2020-12-21 08:27:56,287 ERROR [stderr] (default task-13) 	at io.apiman.gateway.engine.impl.ApiRequestExecutorImpl.lambda$wrapResultHandler$0(ApiRequestExecutorImpl.java:190)
2020-12-21 08:27:56,287 ERROR [stderr] (default task-13) 	at io.apiman.gateway.engine.impl.ApiRequestExecutorImpl.lambda$createPolicyErrorHandler$19(ApiRequestExecutorImpl.java:860)
2020-12-21 08:27:56,287 ERROR [stderr] (default task-13) 	at io.apiman.gateway.engine.impl.ApiRequestExecutorImpl.lambda$createResponseChain$17(ApiRequestExecutorImpl.java:837)
2020-12-21 08:27:56,287 ERROR [stderr] (default task-13) 	at io.apiman.gateway.engine.policy.Chain.throwError(Chain.java:282)
2020-12-21 08:27:56,287 ERROR [stderr] (default task-13) 	at io.apiman.gateway.engine.policy.Chain.doApply(Chain.java:155)
2020-12-21 08:27:56,287 ERROR [stderr] (default task-13) 	at io.apiman.gateway.engine.policies.AbstractMappedPolicy.doApply(AbstractMappedPolicy.java:102)
2020-12-21 08:27:56,287 ERROR [stderr] (default task-13) 	at io.apiman.gateway.engine.policies.AbstractMappedPolicy.apply(AbstractMappedPolicy.java:91)
2020-12-21 08:27:56,287 ERROR [stderr] (default task-13) 	at io.apiman.gateway.engine.policy.ResponseChain.lambda$applyPolicy$0(ResponseChain.java:67)
2020-12-21 08:27:56,287 ERROR [stderr] (default task-13) 	at io.apiman.gateway.engine.policy.Chain.executeInPolicyContextLoader(Chain.java:299)
2020-12-21 08:27:56,288 ERROR [stderr] (default task-13) 	at io.apiman.gateway.engine.policy.ResponseChain.applyPolicy(ResponseChain.java:66)
2020-12-21 08:27:56,288 ERROR [stderr] (default task-13) 	at io.apiman.gateway.engine.policy.Chain.doApply(Chain.java:150)
2020-12-21 08:27:56,288 ERROR [stderr] (default task-13) 	at io.apiman.gateway.engine.impl.ApiRequestExecutorImpl.lambda$createApiConnectionResponseHandler$13(ApiRequestExecutorImpl.java:725)
2020-12-21 08:27:56,288 ERROR [stderr] (default task-13) 	at io.apiman.gateway.platforms.servlet.connectors.HttpApiConnection.end(HttpApiConnection.java:363)
2020-12-21 08:27:56,288 ERROR [stderr] (default task-13) 	at io.apiman.gateway.engine.impl.ApiRequestExecutorImpl.lambda$null$2(ApiRequestExecutorImpl.java:278)
2020-12-21 08:27:56,288 ERROR [stderr] (default task-13) 	at io.apiman.gateway.engine.io.AbstractStream.handleEnd(AbstractStream.java:116)
2020-12-21 08:27:56,288 ERROR [stderr] (default task-13) 	at io.apiman.gateway.engine.policy.Chain.end(Chain.java:220)
2020-12-21 08:27:56,288 ERROR [stderr] (default task-13) 	at io.apiman.gateway.engine.impl.ApiRequestExecutorImpl$3.end(ApiRequestExecutorImpl.java:750)
2020-12-21 08:27:56,288 ERROR [stderr] (default task-13) 	at io.apiman.gateway.platforms.servlet.GatewayServlet$2.handle(GatewayServlet.java:172)
2020-12-21 08:27:56,288 ERROR [stderr] (default task-13) 	at io.apiman.gateway.platforms.servlet.GatewayServlet$2.handle(GatewayServlet.java:161)
2020-12-21 08:27:56,288 ERROR [stderr] (default task-13) 	at io.apiman.gateway.engine.impl.ApiRequestExecutorImpl.handleStream(ApiRequestExecutorImpl.java:737)
2020-12-21 08:27:56,288 ERROR [stderr] (default task-13) 	at io.apiman.gateway.engine.impl.ApiRequestExecutorImpl.lambda$null$3(ApiRequestExecutorImpl.java:283)
2020-12-21 08:27:56,288 ERROR [stderr] (default task-13) 	at io.apiman.gateway.engine.policy.Chain.handleHead(Chain.java:238)
2020-12-21 08:27:56,288 ERROR [stderr] (default task-13) 	at io.apiman.gateway.engine.policy.Chain.doApply(Chain.java:152)
2020-12-21 08:27:56,288 ERROR [stderr] (default task-13) 	at io.apiman.gateway.engine.policies.AbstractMappedPolicy.doApply(AbstractMappedPolicy.java:81)
2020-12-21 08:27:56,288 ERROR [stderr] (default task-13) 	at io.apiman.gateway.engine.policies.IPWhitelistPolicy.doApply(IPWhitelistPolicy.java:57)
2020-12-21 08:27:56,288 ERROR [stderr] (default task-13) 	at io.apiman.gateway.engine.policies.IPWhitelistPolicy.doApply(IPWhitelistPolicy.java:33)
2020-12-21 08:27:56,288 ERROR [stderr] (default task-13) 	at io.apiman.gateway.engine.policies.AbstractMappedPolicy.apply(AbstractMappedPolicy.java:73)
2020-12-21 08:27:56,288 ERROR [stderr] (default task-13) 	at io.apiman.gateway.engine.policy.RequestChain.lambda$applyPolicy$0(RequestChain.java:67)
2020-12-21 08:27:56,288 ERROR [stderr] (default task-13) 	at io.apiman.gateway.engine.policy.Chain.executeInPolicyContextLoader(Chain.java:299)
2020-12-21 08:27:56,289 ERROR [stderr] (default task-13) 	at io.apiman.gateway.engine.policy.RequestChain.applyPolicy(RequestChain.java:66)
2020-12-21 08:27:56,289 ERROR [stderr] (default task-13) 	at io.apiman.gateway.engine.policy.Chain.doApply(Chain.java:150)
2020-12-21 08:27:56,289 ERROR [stderr] (default task-13) 	at io.apiman.gateway.engine.impl.ApiRequestExecutorImpl.lambda$execute$4(ApiRequestExecutorImpl.java:285)
2020-12-21 08:27:56,289 ERROR [stderr] (default task-13) 	at io.apiman.gateway.engine.impl.ApiRequestExecutorImpl.lambda$loadPolicies$7(ApiRequestExecutorImpl.java:675)
2020-12-21 08:27:56,289 ERROR [stderr] (default task-13) 	at io.apiman.gateway.engine.policy.PolicyFactoryImpl.loadPolicy(PolicyFactoryImpl.java:95)
2020-12-21 08:27:56,289 ERROR [stderr] (default task-13) 	at io.apiman.gateway.engine.impl.ApiRequestExecutorImpl.loadPolicies(ApiRequestExecutorImpl.java:643)
2020-12-21 08:27:56,289 ERROR [stderr] (default task-13) 	at io.apiman.gateway.engine.impl.ApiRequestExecutorImpl.lambda$execute$6(ApiRequestExecutorImpl.java:406)
2020-12-21 08:27:56,289 ERROR [stderr] (default task-13) 	at io.apiman.gateway.engine.impl.SecureRegistryWrapper$2.handle(SecureRegistryWrapper.java:189)
2020-12-21 08:27:56,289 ERROR [stderr] (default task-13) 	at io.apiman.gateway.engine.impl.SecureRegistryWrapper$2.handle(SecureRegistryWrapper.java:171)
2020-12-21 08:27:56,289 ERROR [stderr] (default task-13) 	at io.apiman.gateway.engine.es.CachingESRegistry.getContract(CachingESRegistry.java:103)
2020-12-21 08:27:56,289 ERROR [stderr] (default task-13) 	at io.apiman.gateway.engine.impl.SecureRegistryWrapper.getContract(SecureRegistryWrapper.java:171)
2020-12-21 08:27:56,289 ERROR [stderr] (default task-13) 	at io.apiman.gateway.engine.impl.ApiRequestExecutorImpl.execute(ApiRequestExecutorImpl.java:372)
2020-12-21 08:27:56,289 ERROR [stderr] (default task-13) 	at io.apiman.gateway.platforms.servlet.GatewayServlet.doAction(GatewayServlet.java:178)
2020-12-21 08:27:56,289 ERROR [stderr] (default task-13) 	at io.apiman.gateway.platforms.servlet.GatewayServlet.service(GatewayServlet.java:79)
2020-12-21 08:27:56,289 ERROR [stderr] (default task-13) 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
2020-12-21 08:27:56,289 ERROR [stderr] (default task-13) 	at io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:85)
2020-12-21 08:27:56,289 ERROR [stderr] (default task-13) 	at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62)
2020-12-21 08:27:56,289 ERROR [stderr] (default task-13) 	at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)
2020-12-21 08:27:56,289 ERROR [stderr] (default task-13) 	at org.wildfly.extension.undertow.security.SecurityContextAssociationHandler.handleRequest(SecurityContextAssociationHandler.java:78)
2020-12-21 08:27:56,289 ERROR [stderr] (default task-13) 	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
2020-12-21 08:27:56,290 ERROR [stderr] (default task-13) 	at io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:131)
2020-12-21 08:27:56,290 ERROR [stderr] (default task-13) 	at io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57)
2020-12-21 08:27:56,290 ERROR [stderr] (default task-13) 	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
2020-12-21 08:27:56,290 ERROR [stderr] (default task-13) 	at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46)
2020-12-21 08:27:56,290 ERROR [stderr] (default task-13) 	at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64)
2020-12-21 08:27:56,290 ERROR [stderr] (default task-13) 	at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60)
2020-12-21 08:27:56,290 ERROR [stderr] (default task-13) 	at io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77)
2020-12-21 08:27:56,290 ERROR [stderr] (default task-13) 	at io.undertow.security.handlers.NotificationReceiverHandler.handleRequest(NotificationReceiverHandler.java:50)
2020-12-21 08:27:56,290 ERROR [stderr] (default task-13) 	at io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43)
2020-12-21 08:27:56,290 ERROR [stderr] (default task-13) 	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
2020-12-21 08:27:56,290 ERROR [stderr] (default task-13) 	at org.wildfly.extension.undertow.security.jacc.JACCContextIdHandler.handleRequest(JACCContextIdHandler.java:61)
2020-12-21 08:27:56,290 ERROR [stderr] (default task-13) 	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
2020-12-21 08:27:56,290 ERROR [stderr] (default task-13) 	at org.wildfly.extension.undertow.deployment.GlobalRequestControllerHandler.handleRequest(GlobalRequestControllerHandler.java:68)
2020-12-21 08:27:56,290 ERROR [stderr] (default task-13) 	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
2020-12-21 08:27:56,290 ERROR [stderr] (default task-13) 	at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:292)
2020-12-21 08:27:56,290 ERROR [stderr] (default task-13) 	at io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:81)
2020-12-21 08:27:56,290 ERROR [stderr] (default task-13) 	at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:138)
2020-12-21 08:27:56,290 ERROR [stderr] (default task-13) 	at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:135)
2020-12-21 08:27:56,291 ERROR [stderr] (default task-13) 	at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48)
2020-12-21 08:27:56,291 ERROR [stderr] (default task-13) 	at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
2020-12-21 08:27:56,291 ERROR [stderr] (default task-13) 	at org.wildfly.extension.undertow.security.SecurityContextThreadSetupAction.lambda$create$0(SecurityContextThreadSetupAction.java:105)
2020-12-21 08:27:56,291 ERROR [stderr] (default task-13) 	at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1508)
2020-12-21 08:27:56,291 ERROR [stderr] (default task-13) 	at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1508)
2020-12-21 08:27:56,291 ERROR [stderr] (default task-13) 	at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1508)
2020-12-21 08:27:56,291 ERROR [stderr] (default task-13) 	at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1508)
2020-12-21 08:27:56,291 ERROR [stderr] (default task-13) 	at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:272)
2020-12-21 08:27:56,291 ERROR [stderr] (default task-13) 	at io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:81)
2020-12-21 08:27:56,291 ERROR [stderr] (default task-13) 	at io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:104)
2020-12-21 08:27:56,291 ERROR [stderr] (default task-13) 	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:326)
2020-12-21 08:27:56,291 ERROR [stderr] (default task-13) 	at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:812)
2020-12-21 08:27:56,291 ERROR [stderr] (default task-13) 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
2020-12-21 08:27:56,291 ERROR [stderr] (default task-13) 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
2020-12-21 08:27:56,291 ERROR [stderr] (default task-13) 	at java.lang.Thread.run(Thread.java:748)

**Comment by msavy** [comment]
Interesting. Did you never see this previously? Which was the last version that you were using?

**Comment by nowitzkihuang** [comment]
> Interesting. Did you never see this previously? Which was the last version that you were using?

The situation happened when redeploying the image every time. The exception was not happened immediately, It always happened several hours later after apigateway up. I am using version 1.5.1. By the way, the apiman we are using includes several custom plugins we developed, I have no idea if it causes the problem. Thank you for your reply.

**Comment by volkflo** [comment]
If I look at the stack trace it is possible that this is caused by a policy.
Is it possible to try the same deployment without the policies and check if this also happens for your APIs?

**Comment by nowitzkihuang** [comment]
> If I look at the stack trace it is possible that this is caused by a policy.
> Is it possible to try the same deployment without the policies and check if this also happens for your APIs?

It is production environment, I can not touch and try it easily. The same deployment was tried on the development environment and it was ok. I guess the situation only happens when the platform serves a lot of request.

**Comment by msavy** [comment]
It's really difficult for us to help you without some debugging.

Is the policy that you are deploying unchanged between the older version of Apiman that seemed to work OK and this newer version of Apiman that you believe is broken?
