### ISSUE TITLE
GET request with body get transfered to managed endpoint

### ISSUE THREAD

**Issue by potehvad** [apiman/apiman#958]
GET request containing body is raising 

14:35:17,499 ERROR [stderr] (default task-3) Caused by: java.net.ProtocolException: method does not support a request body: GET
14:35:17,499 ERROR [stderr] (default task-3)    at deployment.apiman-gateway.war//io.apiman.gateway.platforms.servlet.connectors.ok.HttpURLConnectionImpl.getOutputStream(HttpURLConnectionImpl.java:251)
14:35:17,499 ERROR [stderr] (default task-3)    at deployment.apiman-gateway.war//io.apiman.gateway.platforms.servlet.connectors.HttpApiConnection.write(HttpApiConnection.java:322)

It could be ok, as GET does not support body, but as it fails anyway, it should not pass request forward to managed endpoint.

Version - apiman-1.5.1.Final on wildfly 11, docker image apiman/on-wildfly11:1.5.0.Final

**Comment by tevosouza** [comment]
Hi @potehvad 
If I remember (i can be wrong) apiman not inspect the request body by default, Did you activate payload inspection on apiman endpoint configuration?

**Comment by potehvad** [comment]
No... this exception is catched by custom IPolicyErrorWriter plugin as an exception

**Comment by tevosouza** [comment]
Got it,
I take a fast look into `ApiRequestExecutorImpl.java` and  i found the method ` final IAsyncResultHandler<Object> payloadParserHandler = new IAsyncResultHandler<Object>() ` this method only is called when payload inspection is active 
```java
  // If the API is configured to be "stateful", we need to parse the
  // inbound request body into an object appropriate to the type and
  // format of the API.  This could be a SOAP message, an XML document,
  // or a JSON document
  if (api.isParsePayload()) {
         parsePayload(payloadParserHandler);
  } else {
         loadPolicies(policiesLoadedHandler);
  } ``` 
  
 Maybe we add a condition if http method is GET force the payload parse and if it is not empty throw an exception to the client 
 @volkflo what you think about it?

**Comment by potehvad** [comment]
I have disabled request payload inspection and here is a full stacktrace:
`16:03:14,385 INFO  [stdout] (default task-1) io.apiman.gateway.engine.beans.exceptions.ConnectorException: method does not support a request body: GET
16:03:14,386 ERROR [stderr] (default task-1) io.apiman.gateway.engine.beans.exceptions.RequestAbortedException: io.apiman.gateway.engine.beans.exceptions.ConnectorException: method does not support a request body: GET
16:03:14,386 ERROR [stderr] (default task-1)    at deployment.apiman-gateway.war//io.apiman.gateway.engine.impl.ApiRequestExecutorImpl$3.abort(ApiRequestExecutorImpl.java:765)
16:03:14,386 ERROR [stderr] (default task-1)    at deployment.apiman-gateway.war//io.apiman.gateway.platforms.servlet.GatewayServlet$2.handle(GatewayServlet.java:174)
16:03:14,386 ERROR [stderr] (default task-1)    at deployment.apiman-gateway.war//io.apiman.gateway.platforms.servlet.GatewayServlet$2.handle(GatewayServlet.java:161)
16:03:14,386 ERROR [stderr] (default task-1)    at deployment.apiman-gateway.war//io.apiman.gateway.engine.impl.ApiRequestExecutorImpl.handleStream(ApiRequestExecutorImpl.java:737)
16:03:14,386 ERROR [stderr] (default task-1)    at deployment.apiman-gateway.war//io.apiman.gateway.engine.impl.ApiRequestExecutorImpl.lambda$null$3(ApiRequestExecutorImpl.java:283)
16:03:14,386 ERROR [stderr] (default task-1)    at deployment.apiman-gateway.war//io.apiman.gateway.engine.policy.Chain.handleHead(Chain.java:238)
16:03:14,387 ERROR [stderr] (default task-1)    at deployment.apiman-gateway.war//io.apiman.gateway.engine.policy.Chain.doApply(Chain.java:152)
16:03:14,387 ERROR [stderr] (default task-1)    at io.apiman.plugins.simpleheaderpolicy.SimpleHeaderPolicy.doApply(SimpleHeaderPolicy.java:49)
16:03:14,387 ERROR [stderr] (default task-1)    at io.apiman.plugins.simpleheaderpolicy.SimpleHeaderPolicy.doApply(SimpleHeaderPolicy.java:37)
16:03:14,387 ERROR [stderr] (default task-1)    at deployment.apiman-gateway.war//io.apiman.gateway.engine.policies.AbstractMappedPolicy.apply(AbstractMappedPolicy.java:73)
16:03:14,387 ERROR [stderr] (default task-1)    at deployment.apiman-gateway.war//io.apiman.gateway.engine.policy.RequestChain.lambda$applyPolicy$0(RequestChain.java:67)
16:03:14,387 ERROR [stderr] (default task-1)    at deployment.apiman-gateway.war//io.apiman.gateway.engine.policy.Chain.executeInPolicyContextLoader(Chain.java:299)
16:03:14,387 ERROR [stderr] (default task-1)    at deployment.apiman-gateway.war//io.apiman.gateway.engine.policy.RequestChain.applyPolicy(RequestChain.java:66)
16:03:14,387 ERROR [stderr] (default task-1)    at deployment.apiman-gateway.war//io.apiman.gateway.engine.policy.Chain.doApply(Chain.java:150)
16:03:14,387 ERROR [stderr] (default task-1)    at deployment.apiman-gateway.war//io.apiman.gateway.engine.impl.ApiRequestExecutorImpl.lambda$execute$4(ApiRequestExecutorImpl.java:285)
16:03:14,387 ERROR [stderr] (default task-1)    at deployment.apiman-gateway.war//io.apiman.gateway.engine.impl.ApiRequestExecutorImpl.lambda$loadPolicies$7(ApiRequestExecutorImpl.java:675)
16:03:14,387 ERROR [stderr] (default task-1)    at deployment.apiman-gateway.war//io.apiman.gateway.engine.policy.PolicyFactoryImpl.loadPolicy(PolicyFactoryImpl.java:95)
16:03:14,388 ERROR [stderr] (default task-1)    at deployment.apiman-gateway.war//io.apiman.gateway.engine.impl.ApiRequestExecutorImpl.loadPolicies(ApiRequestExecutorImpl.java:643)
16:03:14,388 ERROR [stderr] (default task-1)    at deployment.apiman-gateway.war//io.apiman.gateway.engine.impl.ApiRequestExecutorImpl.lambda$execute$6(ApiRequestExecutorImpl.java:406)
16:03:14,388 ERROR [stderr] (default task-1)    at deployment.apiman-gateway.war//io.apiman.gateway.engine.impl.SecureRegistryWrapper$2.handle(SecureRegistryWrapper.java:189)
16:03:14,388 ERROR [stderr] (default task-1)    at deployment.apiman-gateway.war//io.apiman.gateway.engine.impl.SecureRegistryWrapper$2.handle(SecureRegistryWrapper.java:171)
16:03:14,388 ERROR [stderr] (default task-1)    at deployment.apiman-gateway.war//io.apiman.gateway.engine.jdbc.CachingJdbcRegistry.getContract(CachingJdbcRegistry.java:102)
16:03:14,388 ERROR [stderr] (default task-1)    at deployment.apiman-gateway.war//io.apiman.gateway.engine.impl.SecureRegistryWrapper.getContract(SecureRegistryWrapper.java:171)
16:03:14,388 ERROR [stderr] (default task-1)    at deployment.apiman-gateway.war//io.apiman.gateway.engine.impl.ApiRequestExecutorImpl.execute(ApiRequestExecutorImpl.java:372)
16:03:14,388 ERROR [stderr] (default task-1)    at deployment.apiman-gateway.war//io.apiman.gateway.platforms.servlet.GatewayServlet.doAction(GatewayServlet.java:178)
16:03:14,389 ERROR [stderr] (default task-1)    at deployment.apiman-gateway.war//io.apiman.gateway.platforms.servlet.GatewayServlet.service(GatewayServlet.java:79)
16:03:14,389 ERROR [stderr] (default task-1)    at javax.servlet.api@2.0.0.Final//javax.servlet.http.HttpServlet.service(HttpServlet.java:590)
16:03:14,389 ERROR [stderr] (default task-1)    at io.undertow.servlet@2.1.0.Final//io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:74)
16:03:14,389 ERROR [stderr] (default task-1)    at io.undertow.servlet@2.1.0.Final//io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62)
16:03:14,389 ERROR [stderr] (default task-1)    at io.undertow.servlet@2.1.0.Final//io.undertow.servlet.handlers.ServletChain$1.handleRequest(ServletChain.java:68)
16:03:14,390 ERROR [stderr] (default task-1)    at io.undertow.servlet@2.1.0.Final//io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)
16:03:14,390 ERROR [stderr] (default task-1)    at org.wildfly.extension.undertow@19.1.0.Final//org.wildfly.extension.undertow.security.SecurityContextAssociationHandler.handleRequest(SecurityContextAssociationHandler.java:78)
16:03:14,390 ERROR [stderr] (default task-1)    at io.undertow.core@2.1.0.Final//io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
16:03:14,390 ERROR [stderr] (default task-1)    at io.undertow.servlet@2.1.0.Final//io.undertow.servlet.handlers.RedirectDirHandler.handleRequest(RedirectDirHandler.java:68)
16:03:14,390 ERROR [stderr] (default task-1)    at io.undertow.servlet@2.1.0.Final//io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:132)
16:03:14,390 ERROR [stderr] (default task-1)    at io.undertow.servlet@2.1.0.Final//io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57)
16:03:14,390 ERROR [stderr] (default task-1)    at io.undertow.core@2.1.0.Final//io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
16:03:14,391 ERROR [stderr] (default task-1)    at io.undertow.core@2.1.0.Final//io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46)
16:03:14,391 ERROR [stderr] (default task-1)    at io.undertow.servlet@2.1.0.Final//io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64)
16:03:14,391 ERROR [stderr] (default task-1)    at io.undertow.core@2.1.0.Final//io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60)
16:03:14,391 ERROR [stderr] (default task-1)    at io.undertow.servlet@2.1.0.Final//io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77)
16:03:14,391 ERROR [stderr] (default task-1)    at io.undertow.core@2.1.0.Final//io.undertow.security.handlers.NotificationReceiverHandler.handleRequest(NotificationReceiverHandler.java:50)
16:03:14,391 ERROR [stderr] (default task-1)    at io.undertow.core@2.1.0.Final//io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43)
16:03:14,391 ERROR [stderr] (default task-1)    at io.undertow.core@2.1.0.Final//io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
16:03:14,391 ERROR [stderr] (default task-1)    at org.wildfly.extension.undertow@19.1.0.Final//org.wildfly.extension.undertow.security.jacc.JACCContextIdHandler.handleRequest(JACCContextIdHandler.java:61)
16:03:14,391 ERROR [stderr] (default task-1)    at io.undertow.core@2.1.0.Final//io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
16:03:14,392 ERROR [stderr] (default task-1)    at org.wildfly.extension.undertow@19.1.0.Final//org.wildfly.extension.undertow.deployment.GlobalRequestControllerHandler.handleRequest(GlobalRequestControllerHandler.java:68)
16:03:14,392 ERROR [stderr] (default task-1)    at io.undertow.core@2.1.0.Final//io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
16:03:14,392 ERROR [stderr] (default task-1)    at io.undertow.servlet@2.1.0.Final//io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:269)
16:03:14,392 ERROR [stderr] (default task-1)    at io.undertow.servlet@2.1.0.Final//io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:78)
16:03:14,392 ERROR [stderr] (default task-1)    at io.undertow.servlet@2.1.0.Final//io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:133)
16:03:14,392 ERROR [stderr] (default task-1)    at io.undertow.servlet@2.1.0.Final//io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:130)
16:03:14,392 ERROR [stderr] (default task-1)    at io.undertow.servlet@2.1.0.Final//io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48)
16:03:14,392 ERROR [stderr] (default task-1)    at io.undertow.servlet@2.1.0.Final//io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
16:03:14,393 ERROR [stderr] (default task-1)    at org.wildfly.extension.undertow@19.1.0.Final//org.wildfly.extension.undertow.security.SecurityContextThreadSetupAction.lambda$create$0(SecurityContextThreadSetupAction.java:105)
16:03:14,393 ERROR [stderr] (default task-1)    at org.wildfly.extension.undertow@19.1.0.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1541)
16:03:14,393 ERROR [stderr] (default task-1)    at org.wildfly.extension.undertow@19.1.0.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1541)
16:03:14,393 ERROR [stderr] (default task-1)    at org.wildfly.extension.undertow@19.1.0.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1541)
16:03:14,393 ERROR [stderr] (default task-1)    at org.wildfly.extension.undertow@19.1.0.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1541)
16:03:14,393 ERROR [stderr] (default task-1)    at io.undertow.servlet@2.1.0.Final//io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:249)
16:03:14,393 ERROR [stderr] (default task-1)    at io.undertow.servlet@2.1.0.Final//io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:78)
16:03:14,394 ERROR [stderr] (default task-1)    at io.undertow.servlet@2.1.0.Final//io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:99)
16:03:14,394 ERROR [stderr] (default task-1)    at io.undertow.core@2.1.0.Final//io.undertow.server.Connectors.executeRootHandler(Connectors.java:370)
16:03:14,394 ERROR [stderr] (default task-1)    at io.undertow.core@2.1.0.Final//io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:830)
16:03:14,394 ERROR [stderr] (default task-1)    at org.jboss.threads@2.3.3.Final//org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
16:03:14,394 ERROR [stderr] (default task-1)    at org.jboss.threads@2.3.3.Final//org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1982)
16:03:14,394 ERROR [stderr] (default task-1)    at org.jboss.threads@2.3.3.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1486)
16:03:14,394 ERROR [stderr] (default task-1)    at org.jboss.threads@2.3.3.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1377)
16:03:14,394 ERROR [stderr] (default task-1)    at java.base/java.lang.Thread.run(Thread.java:834)
16:03:14,395 ERROR [stderr] (default task-1) Caused by: io.apiman.gateway.engine.beans.exceptions.ConnectorException: method does not support a request body: GET
16:03:14,395 ERROR [stderr] (default task-1)    at deployment.apiman-gateway.war//io.apiman.gateway.platforms.servlet.connectors.HttpApiConnection.handleConnectionError(HttpApiConnection.java:412)
16:03:14,395 ERROR [stderr] (default task-1)    at deployment.apiman-gateway.war//io.apiman.gateway.platforms.servlet.connectors.HttpApiConnection.write(HttpApiConnection.java:331)
16:03:14,395 ERROR [stderr] (default task-1)    at deployment.apiman-gateway.war//io.apiman.gateway.engine.impl.ApiRequestExecutorImpl.lambda$null$1(ApiRequestExecutorImpl.java:274)
16:03:14,395 ERROR [stderr] (default task-1)    at deployment.apiman-gateway.war//io.apiman.gateway.engine.io.AbstractStream.handleBody(AbstractStream.java:107)
16:03:14,395 ERROR [stderr] (default task-1)    at deployment.apiman-gateway.war//io.apiman.gateway.engine.policy.Chain.write(Chain.java:208)
16:03:14,395 ERROR [stderr] (default task-1)    at deployment.apiman-gateway.war//io.apiman.gateway.engine.impl.ApiRequestExecutorImpl$3.write(ApiRequestExecutorImpl.java:745)
16:03:14,395 ERROR [stderr] (default task-1)    at deployment.apiman-gateway.war//io.apiman.gateway.platforms.servlet.GatewayServlet$2.handle(GatewayServlet.java:169)
16:03:14,396 ERROR [stderr] (default task-1)    ... 67 more
16:03:14,396 ERROR [stderr] (default task-1) Caused by: java.net.ProtocolException: method does not support a request body: GET
16:03:14,397 ERROR [stderr] (default task-1)    at deployment.apiman-gateway.war//io.apiman.gateway.platforms.servlet.connectors.ok.HttpURLConnectionImpl.getOutputStream(HttpURLConnectionImpl.java:251)
16:03:14,397 ERROR [stderr] (default task-1)    at deployment.apiman-gateway.war//io.apiman.gateway.platforms.servlet.connectors.HttpApiConnection.write(HttpApiConnection.java:322)
16:03:14,397 ERROR [stderr] (default task-1)    ... 72 more
`

**Comment by msavy** [comment]
It's a bit odd to send a payload with a `GET` request. The underlying library used in the servlet implementation doesn't want to let you do it.

I take it that it's a hard requirement for that to remain a `GET`?

**Comment by potehvad** [comment]
I mean apiman rejects GET with payload (and it does it now), but anyway sends request to managed endpoint. 
Why it transfers request to 3rd party service, if later will fail it with error about payload.

Expected apiman behavior is: 
- it should fail GET with payload, without sending to managed endpoint,
- it should send such request to managed endpoint (3rd party service) and respond with response from 3rd party service.

**Comment by msavy** [comment]
Okay, I understand. That is very surprising behaviour!

It might be because the library receiving the request is different to the one dispatching it.

**Comment by tevosouza** [comment]
@msavy 
I dig into this issue and did some tests and included this piece of code to "block" this behavior.

```java
//GatewayServlet.java
protected ApiRequest readRequest(HttpServletRequest request) throws Exception {
        ApiRequestPathInfo pathInfo = getEngine().getApiRequestPathParser().parseEndpoint(request.getPathInfo(), wrapMultiMap(request));//parseApiRequestPath(request);
        
        if (request.getMethod() == "GET" && request.getContentLength() > 0)
        {
        	throw new Exception(Messages.i18n.format("GatewayServlet.InvalidRequestMethod"));
        }
```

What is your opinion about this approach?
