### ISSUE TITLE
Apiman Gateway Vertx Configuration for Mysql

### ISSUE THREAD

**Issue by shekarnode** [apiman/apiman#975]
Hi ,
I am currently using **Apiman version 1.5.7 final.**

For api-gateway I'm using **vertx version of gateway**.
I m trying to create a config file for mysql version.

But facing error while doing the same ,
I have tried to convert the apiman.properties configuration in json format.

Following are the code snippit  for _intializers_ and _registry_

```
{ // Example ElasticSearch based config
  "variables": {
    "apiman": {
      "es": {
        "protocol": "http",
        "host": "localhost",
        "port": 9200,
        "username": "elastic",
        "password": "changeme",
        "timeout": 10000
      }
    }
  },

  "initializers":{
     "class" : "io.apiman.gateway.engine.jdbc.JdbcInitializer",
       "config": {
        "initializers" :"jdbc",
        "datasource": {
            "jndi-location" : "java:jboss/datasources/apiman-gateway",
            "type" : "mysql5"
        }
     }
  },
 

  "registry": {
    "class": "io.apiman.gateway.engine.jdbc.PollCachingJdbcRegistry",
     "config": {
      "jndi-location" : "java:jboss/datasources/apiman-gateway",
      "cache-polling-interval": 15,
      "client": {
         
          "initialize": true
          
          //"index": ""
        }
    }
  }

```

Reference from apiman.properties file .

```
apiman-gateway.registry=io.apiman.gateway.engine.jdbc.PollCachingJdbcRegistry
apiman-gateway.registry.datasource.jndi-location=java:jboss/datasources/apiman-gateway
apiman-gateway.registry.client.initialize=true
apiman-gateway.registry.cache-polling-interval=15

# Initializer for the Gateway JDBC
# ################################
apiman.jdbc.datasource.jndi-location=java:jboss/datasources/apiman-gateway
apiman-gateway.initializers=jdbc
apiman-gateway.initializers.jdbc=io.apiman.gateway.engine.jdbc.JdbcInitializer
apiman-gateway.initializers.jdbc.datasource.jndi-location=${apiman.jdbc.datasource.jndi-location}
apiman-gateway.initializers.jdbc.datasource.type=mysql5
```

Error  while running gateway:
```
$ java -jar apiman-gateway.jar --conf configs/conf-mysql.json
INFO  [vert.x-eventloop-thread-0]: Starting verticle: INITIALISER. UUID: 025d4302-2156-4c79-8672-4afade1887c3.INITIALISER.
INFO  [vert.x-eventloop-thread-0]: Will deploy 1 of type API
INFO  [vert.x-eventloop-thread-1]: Starting verticle: API. UUID: bd4db2c4-ff60-490c-b61b-702c366c9aca.API.
INFO  [vert.x-eventloop-thread-0]: Will deploy 4 of type HTTP
INFO  [vert.x-eventloop-thread-2]: Starting verticle: HTTP. UUID: 4a4e09c3-a69d-4c9c-a0ec-31d306efaf35.HTTP.
INFO  [vert.x-eventloop-thread-3]: Starting verticle: HTTP. UUID: b89d156a-c03d-4601-ab48-a4352ede3d71.HTTP.
INFO  [vert.x-eventloop-thread-4]: Starting verticle: HTTP. UUID: 878ee04f-b132-4e68-a87f-9a36b3f3c96d.HTTP.
INFO  [vert.x-eventloop-thread-0]: Will deploy 0 of type HTTPS
INFO  [vert.x-eventloop-thread-5]: Starting verticle: HTTP. UUID: 37c8ff8c-40b2-4369-8edc-dc4156a1f47f.HTTP.
java.lang.RuntimeException: java.lang.NullPointerException
        at io.apiman.gateway.platforms.vertx3.engine.VertxConfigDrivenEngineFactory.doInstantiate(VertxConfigDrivenEngineFactory.java:66)
        at io.apiman.gateway.engine.impl.ConfigDrivenEngineFactory.create(ConfigDrivenEngineFactory.java:181)
        at io.apiman.gateway.engine.impl.ConfigDrivenEngineFactory.createRegistry(ConfigDrivenEngineFactory.java:99)
        at io.apiman.gateway.engine.impl.AbstractEngineFactory.createEngine(AbstractEngineFactory.java:56)
        at io.apiman.gateway.platforms.vertx3.verticles.ApimanVerticleWithEngine.start(ApimanVerticleWithEngine.java:48)
        at io.apiman.gateway.platforms.vertx3.verticles.HttpGatewayVerticle.start(HttpGatewayVerticle.java:37)
        at io.vertx.core.impl.DeploymentManager.lambda$doDeploy$8(DeploymentManager.java:552)
        at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:320)
        at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:462)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
        at io.apiman.gateway.platforms.vertx3.engine.VertxConfigDrivenEngineFactory.doInstantiate(VertxConfigDrivenEngineFactory.java:62)
        ... 14 more
FATAL [vert.x-eventloop-thread-0]: Failed to deploy verticles: java.lang.NullPointerException
java.lang.RuntimeException: java.lang.NullPointerException
        at io.apiman.gateway.platforms.vertx3.engine.VertxConfigDrivenEngineFactory.doInstantiate(VertxConfigDrivenEngineFactory.java:66)
        at io.apiman.gateway.engine.impl.ConfigDrivenEngineFactory.create(ConfigDrivenEngineFactory.java:181)
        at io.apiman.gateway.engine.impl.ConfigDrivenEngineFactory.createRegistry(ConfigDrivenEngineFactory.java:99)
        at io.apiman.gateway.engine.impl.AbstractEngineFactory.createEngine(AbstractEngineFactory.java:56)
        at io.apiman.gateway.platforms.vertx3.verticles.ApimanVerticleWithEngine.start(ApimanVerticleWithEngine.java:48)
        at io.apiman.gateway.platforms.vertx3.verticles.HttpGatewayVerticle.start(HttpGatewayVerticle.java:37)
        at io.vertx.core.impl.DeploymentManager.lambda$doDeploy$8(DeploymentManager.java:552)
        at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:320)
        at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:462)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
        at io.apiman.gateway.platforms.vertx3.engine.VertxConfigDrivenEngineFactory.doInstantiate(VertxConfigDrivenEngineFactory.java:62)
        ... 14 more
ERROR [vert.x-eventloop-thread-6]: Failed in deploying verticle
java.lang.RuntimeException: java.lang.NullPointerException
        at io.apiman.gateway.platforms.vertx3.engine.VertxConfigDrivenEngineFactory.doInstantiate(VertxConfigDrivenEngineFactory.java:66) ~[apiman-gateway.jar:?]
        at io.apiman.gateway.engine.impl.ConfigDrivenEngineFactory.create(ConfigDrivenEngineFactory.java:181) ~[apiman-gateway.jar:?]
        at io.apiman.gateway.engine.impl.ConfigDrivenEngineFactory.createRegistry(ConfigDrivenEngineFactory.java:99) ~[apiman-gateway.jar:?]
        at io.apiman.gateway.engine.impl.AbstractEngineFactory.createEngine(AbstractEngineFactory.java:56) ~[apiman-gateway.jar:?]
        at io.apiman.gateway.platforms.vertx3.verticles.ApimanVerticleWithEngine.start(ApimanVerticleWithEngine.java:48) ~[apiman-gateway.jar:?]
        at io.apiman.gateway.platforms.vertx3.verticles.HttpGatewayVerticle.start(HttpGatewayVerticle.java:37) ~[apiman-gateway.jar:?]
        at io.vertx.core.impl.DeploymentManager.lambda$doDeploy$8(DeploymentManager.java:552) ~[apiman-gateway.jar:?]
        at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:320) ~[apiman-gateway.jar:?]
        at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38) ~[apiman-gateway.jar:?]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) [apiman-gateway.jar:?]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404) [apiman-gateway.jar:?]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:462) [apiman-gateway.jar:?]
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897) [apiman-gateway.jar:?]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [apiman-gateway.jar:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_281]
Caused by: java.lang.NullPointerException
        at io.apiman.gateway.platforms.vertx3.engine.VertxConfigDrivenEngineFactory.doInstantiate(VertxConfigDrivenEngineFactory.java:62) ~[apiman-gateway.jar:?]
        ... 14 more
java.lang.RuntimeException: java.lang.NullPointerException
        at io.apiman.gateway.platforms.vertx3.engine.VertxConfigDrivenEngineFactory.doInstantiate(VertxConfigDrivenEngineFactory.java:66)
        at io.apiman.gateway.engine.impl.ConfigDrivenEngineFactory.create(ConfigDrivenEngineFactory.java:181)
        at io.apiman.gateway.engine.impl.ConfigDrivenEngineFactory.createRegistry(ConfigDrivenEngineFactory.java:99)
        at io.apiman.gateway.engine.impl.AbstractEngineFactory.createEngine(AbstractEngineFactory.java:56)
        at io.apiman.gateway.platforms.vertx3.verticles.ApimanVerticleWithEngine.start(ApimanVerticleWithEngine.java:48)
        at io.apiman.gateway.platforms.vertx3.verticles.HttpGatewayVerticle.start(HttpGatewayVerticle.java:37)
        at io.vertx.core.impl.DeploymentManager.lambda$doDeploy$8(DeploymentManager.java:552)
        at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:320)
        at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:462)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
        at io.apiman.gateway.platforms.vertx3.engine.VertxConfigDrivenEngineFactory.doInstantiate(VertxConfigDrivenEngineFactory.java:62)
        ... 14 more
```

Please help me to get the configuration right.
Thank you

**Comment by tevosouza** [comment]
Maybe I'm very very wrong but i think it could be related to [#955](https://github.com/apiman/apiman/issues/955#issue-796517493).
I solved the "problem" by initializing the database by myself running the DDLs scripts and changing the hibernate dialect.

**Comment by shekarnode** [comment]
@tevosouza  , sorry but it's not relatable , here i m asking config file changes for Vert.X distro of apiman gateway.
As the configuration already present for Elastic Search , but there is no configuration for Mysql , as i m planning to store the metrics data in Mysql db.
